       PROCESS APOST.                                                   CBLHDRK1
      ***************************************************************   CBLHDRK1
       IDENTIFICATION DIVISION.                                         CBLHDRK1
     H/TITLE Prt BACs List             Print file                       CBLHDRK1
     Z* CRTCBLPGM                                                       CBLHDRK1
     Z* CVTOPT(*DATETIME)                                               CBLHDRK1
      *                                                                 CBLHDRK1
     H* SYNOPSIS :                                                      PRTFILK1
     H* - Print report of file contents                                 PRTFILK1
     H* Generated by  : COOL:2E  Version: 62070                         CBLHDRK1
     H* Function type : Print file  Version:   0.1                      CBLHDRK1
      *                                                                 CBLHDRK1
     H* Company    : Renault (UK) Applications                          CBLHDRK1
     H* System     : Renault (UK) Applications                          CBLHDRK1
     H* User name  : AG00475                                            CBLHDRK1
     H* Date       : 22/05/03 time: 13:35:09                            CBLHDRK1
     H* Copyright  : Renault (UK) Applications                          CBLHDRK1
      *                                                                 CBLHDRK1
      *==============================================================   CBLHDRK1
     M* MAINTENANCE   :                                                 CBLHDRK1
      *==============================================================   CBLHDRK1
       PROGRAM-ID.  ACBACSLSTS.                                         CBLHDRK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       ENVIRONMENT DIVISION.                                            CBLHDRK1
       CONFIGURATION SECTION.                                           CBLHDRK1
       SOURCE-COMPUTER.  IBM-AS400.                                     CBLHDRK1
       OBJECT-COMPUTER.  IBM-AS400.                                     CBLHDRK1
       SPECIAL-NAMES.  OPEN-FEEDBACK IS OPEN-FEEDBACK-AREA,             CBLHDRK1
           I-O-FEEDBACK IS I-O-FEEDBACK-AREA.                           CBLHDRK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       INPUT-OUTPUT SECTION.                                            CBLHDRK1
       FILE-CONTROL.                                                    CBLHDRK1
      *                                                                 CBLHDRK1
           SELECT MRBACSTRL2                                            CBLUPDK1
             ASSIGN TO DATABASE-MRBACSTRL2                              CBLUPDK1
             ORGANIZATION IS INDEXED                                    CBLUPDK1
             ACCESS MODE IS DYNAMIC                                     CBLUPDK1
             RECORD KEY IS EXTERNALLY-DESCRIBED-KEY                     CBLUPDK1
             FILE STATUS IS FILE-STATUS.                                CBLUPDK1
      *    RSQ : MR BACS Payment           Batch Number (D)             CBLUPDK1
      *                                                                 CBLUPDK1
           SELECT ACBACSLSTP                                            CBLUPDK1
             ASSIGN TO FORMATFILE-ACBACSLSTP-SI                         CBLUPDK1
             FILE STATUS IS FILE-STATUS.                                CBLUPDK1
      *    PRT: Prt BACs List             Print file                    CBLUPDK1
      *                                                                 CBLUPDK1
       I-O-CONTROL.                                                     CBLHDRK1
      *                                                                 CBLHDRK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       DATA DIVISION.                                                   CBLHDRK1
       FILE SECTION.                                                    CBLHDRK1
      *                                                                 CBLHDRK1
      *                                                                 CBLUPDK1
       FD  ACBACSLSTP                                                   CBLUPDK1
           LABEL RECORDS ARE STANDARD.                                  CBLUPDK1
       01  ACBACSLSTP-F.                                                CBLUPDK1
           COPY DDS-ALL-FORMATS OF ACBACSLSTP.                          CBLUPDK1
      *                                                                 CBLUPDK1
       FD  MRBACSTRL2                                                   CBLUPDK1
           LABEL RECORDS ARE STANDARD.                                  CBLUPDK1
       01  MRBACSTRL2-R.                                                CBLUPDK1
           COPY DDS-ALL-FORMATS OF MRBACSTRL2.                          CBLUPDK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       WORKING-STORAGE SECTION.                                         CBLHDRK1
      *                                                                 CBLHDRK1
      *    Job context                                                  CBLHDRK1
       01  JOB-CONTEXT.                                                 CBLHDRK1
           COPY DDS-ALL-FORMATS OF Y2PGDSPK.                            CBLHDRK1
      *    Job date/time                                                CBLHDRK1
           03  IJBDTTM.                                                 CBLHDRK1
           05  ZZJDT PIC S9(7).                                         CBLHDRK1
           05  ZZJDTE REDEFINES ZZJDT.                                  CBLHDRK1
           07  ZZJCC PIC S9(1).                                         CBLHDRK1
           07  ZZJYY PIC S9(2).                                         CBLHDRK1
           07  ZZJMM PIC S9(2).                                         CBLHDRK1
           07  ZZJDD PIC S9(2).                                         CBLHDRK1
           05  ZZJTM PIC S9(6).                                         CBLHDRK1
           05  ZZJTME REDEFINES ZZJTM.                                  CBLHDRK1
           07  ZZJHH PIC S9(2).                                         CBLHDRK1
           07  ZZJNN PIC S9(2).                                         CBLHDRK1
           07  ZZJSS PIC S9(2).                                         CBLHDRK1
           03  ZZFQL PIC X(21).                                         CBLHDRK1
           03  ZZFLB PIC X(10).                                         CBLHDRK1
           03  ZZFFL PIC X(10).                                         CBLHDRK1
           03  ZZFMB PIC X(10).                                         CBLHDRK1
           03  ZZCDB PIC X(18).                                         CBLHDRK1
           03  ZZLDB PIC X(18).                                         CBLHDRK1
           03  ZZTMS PIC X(26).                                         CBLHDRK1
       01  ZZTIME.                                                      CBLHDRK1
           03  ZZHNS PIC S9(6).                                         CBLHDRK1
           03  ZZHH PIC S9(2).                                          CBLHDRK1
      *                                                                 CBLHDRK1
       77  C-IND-OFF PIC 1(1) VALUE B'0'.                               CBLHDRK1
       77  C-IND-ON PIC 1(1) VALUE B'1'.                                CBLHDRK1
      *                                                                 CBLHDRK1
       01  FILE-STATUS PIC X(2).                                        CBLHDRK1
           88  C-IO-OK VALUE '00'.                                      CBLHDRK1
           88  C-EOF VALUE '10' '46'.                                   CBLHDRK1
           88  C-NO-MOD-SFLRCDS VALUE '12'.                             CBLHDRK1
           88  C-IO-ERR VALUE '21' '22' '24' '30' '34' '90' '91' '92' '9CBLHDRK1
      -     '4' '95' '9A' '9H' '9I' '9K' '9M' '9N' '9P'.                CBLHDRK1
           88  C-NO-RECORD VALUE '23'.                                  CBLHDRK1
           88  C-RECORD-LOCKED VALUE '9D'.                              CBLHDRK1
      *                                                                 CBLHDRK1
       01  UNTIL-CONDITION PIC 1(1).                                    CBLHDRK1
           88  C-UNTIL-FALSE VALUE B'0'.                                CBLHDRK1
           88  C-UNTIL-TRUE VALUE B'1'.                                 CBLHDRK1
      *                                                                 CBLHDRK1
       01  FOREVER PIC 1(1) VALUE B'1'.                                 CBLHDRK1
           88  C-FOREVER VALUE B'1'.                                    CBLHDRK1
      *                                                                 CBLHDRK1
       01  WRK-IO-TRASH-AREA PIC X(1).                                  CBLHDRK1
      *                                                                 CBLHDRK1
       01  W0RTN PIC X(7).                                              CBLHDRK1
       01  W0RSF PIC X(1).                                              CBLHDRK1
       01  W0ENV PIC X(3).                                              CBLHDRK1
       01  W0RTW PIC S9(9) COMP-4.                                      CBLHDRK1
       01  W0ICL PIC X(1).                                              CBLHDRK1
       01  W0PFM PIC X(1).                                              PRTFILK1
       01  W0NEWP PIC X(1).                                             PRTFILK1
       01  YXWRK PIC S9(5) COMP-3.                                      PRTFILK1
       01  YXHDL PIC S9(5) COMP-3.                                      PRTFILK1
       01  W0PGL PIC S9(5) COMP-3.                                      PRTFILK1
       01  W0OFL PIC S9(5) COMP-3.                                      PRTFILK1
       01  W0FSUM PIC S9(3) COMP-3.                                     PRTFILK1
       01  W0DTLN PIC S9(3) COMP-3.                                     PRTFILK1
       01  W0COLN PIC S9(3) COMP-3.                                     PRTFILK1
       01  W0AL1P PIC X(1).                                             PRTOBJK1
       01  W0AP1P PIC X(1).                                             PRTOBJK1
       01  W0AL00 PIC X(1).                                             PRTOBJK1
       01  W0AP00 PIC X(1).                                             PRTOBJK1
       01  W0ACDT PIC X(1).                                             PRTOBJK1
       01  W0APDT PIC X(1).                                             PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
       01  WQKA01 PIC S9(5) COMP-3.                                     PRTOBJK1
       01  KRSA.                                                        PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           03  S8VABATNO PIC S9(5) COMP-3.                              PRTOBJK1
      *                                                                 PRTOBJK1
      *..............................................................   PRTOBJK1
      *    Define Full Externally Described Keylist                     PRTOBJK1
       01  KRSA-EXT.                                                    PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           03  S8VABATNO PIC S9(5) COMP-3.                              PRTOBJK1
      *..............................................................   PRTOBJK1
       01  KRSA-TMP.                                                    PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           03  S8VABATNO PIC S9(5) COMP-3.                              PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
       01  WZA001 PIC S9(5) COMP-3.                                     PRTOBJK1
       01  W0EOFA PIC 1(1).                                             PRTOBJK1
       01  W0RSL PIC X(1).                                              PRTOBJK1
       01  ACBACSLSTP-I-O-PRTF.                                         CBLUPDK1
           COPY DDS-ALL-FORMATS OF Y2IPRTFIO.                           CBLUPDK1
      *    Printer file I/O feedback area                               CBLUPDK1
      *                                                                 CBLUPDK1
       01  ACBACSLSTP-OPEN.                                             CBLUPDK1
           COPY DDS-ALL-FORMATS OF Y2IOPEN.                             CBLUPDK1
      *    Open feedback area                                           CBLUPDK1
      *                                                                 CBLUPDK1
       01  MRBACSTRL2-OPEN.                                             CBLUPDK1
           COPY DDS-ALL-FORMATS OF Y2IOPEN.                             CBLUPDK1
      *    Open feedback area                                           CBLUPDK1
      *                                                                 CBLUPDK1
       01  W0OPN PIC X(1).                                              CBLUPDK1
       01  W0PMT PIC X(1).                                              CBLUPDK1
      *    First Time Through                                           ACTCTXK4
       01  WORK-CONTEXT.                                                ACTCTXK4
           03  YL0001 PIC X(1).                                         ACTCTXK4
       01  ACBACSLSTP-WS-O.                                             PRTOBJK1
           03 ZAPAGHDR-WS-O.                                            PRTOBJK1
           COPY DDS-ZAPAGHDR-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
           03 ZEENDRPT-WS-O.                                            PRTOBJK1
           COPY DDS-ZEENDRPT-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
           03 ZDFINTTL-WS-O.                                            PRTOBJK1
           COPY DDS-ZDFINTTL-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
           03 ZBKEYHDR-WS-O.                                            PRTOBJK1
           COPY DDS-ZBKEYHDR-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
           03 ZCDTLRCD-WS-O.                                            PRTOBJK1
           COPY DDS-ZCDTLRCD-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
           03 ZCCOLHDG-WS-O.                                            PRTOBJK1
           COPY DDS-ZCCOLHDG-O OF ACBACSLSTP.                           PRTOBJK1
                 06 FILLER            PIC X(1).                         PRTOBJK1
      *                                                                 CBLHDRK1
      *    Indicators                                                   CBLHDRK1
       01  INDICS.                                                      CBLHDRK1
           03  IND PIC 1(1) OCCURS 99 INDICATOR 1.                      CBLHDRK1
           88  C-INDICATOR-ON VALUE B'1'.                               CBLHDRK1
           88  C-INDICATOR-OFF VALUE B'0'.                              CBLHDRK1
      *                                                                 CBLHDRK1
      /EJECT                                                            DCLPARK1
      *    Parameter declarations                                       DCLPARK1
      /EJECT                                                            DCLPARK1
      ***************************************************************   DCLPARK1
       LINKAGE SECTION.                                                 DCLPARK1
      *    Return code                                                  DCLPARK1
       01  P0RTN PIC X(7).                                              DCLPARK1
       01  P1PARM.                                                      DCLPARK1
      *    Batch Number                                                 DCLPARK1
           03  P1VABATNO PIC S9(5) COMP-3.                              DCLPARK1
      ***************************************************************   CBLHDRK1
       PROCEDURE DIVISION USING                                         CBLHDRK1
             P0RTN                                                      DCLPARK1
      *    KEY: MR BACS Payment           Batch Number (D)              DCLPARK1
      *    I : RST Batch Number                                         DCLPARK1
      *    KEY : MR BACS Payment                                        DCLPARK1
             P1PARM                                                     DCLPARK1
           .                                                            DCLPARK1
      ***************************************************************   CBLHDRK1
           CONTINUE.                                                    CBLHDRK1
       MAINLINE SECTION.                                                CBLHDRK1
      *    Initialize                                                   CBLHDRK1
           PERFORM ZZINIT                                               CBLHDRK1
      *                                                                 CBLHDRK1
      *    Prt BACs List: Mainline                                      PRTOBJK1
           PERFORM A0MAIN                                               PRTOBJK1
      *    Print headers then End of report format                      PRTFILK1
           PERFORM Q0PRNT                                               PRTFILK1
           WRITE ACBACSLSTP-F FROM ZEENDRPT-WS-O                        PRTFILK1
             FORMAT IS 'ZEENDRPT' INDICATORS ARE INDICS                 PRTFILK1
           END-WRITE                                                    PRTFILK1
           ACCEPT ACBACSLSTP-I-O-PRTF FROM I-O-FEEDBACK-AREA FOR        PRTFILK1
             ACBACSLSTP                                                 PRTFILK1
      *    Exit program                                                 PRTFILK1
           PERFORM ZXEXPG                                               PRTFILK1
      *--------------------------------------------------------------   PRTFILK1
      /EJECT                                                            PRTOBJK1
       A0MAIN SECTION.                                                  PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Prt BACs List                                                PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Initialise Full Externally Described Keylist                 PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           MOVE 99999 TO S8VABATNO OF KRSA-EXT                          PRTOBJK1
      *    Setup key                                                    PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           MOVE P1VABATNO TO S8VABATNO OF KRSA                          PRTOBJK1
      *    Establish starting position                                  PRTOBJK1
           MOVE CORRESPONDING                                           PRTOBJK1
             KRSA-EXT TO                                                PRTOBJK1
             FBACSID OF MRBACSTRL2-R                                    PRTOBJK1
           MOVE CORRESPONDING                                           PRTOBJK1
             KRSA TO                                                    PRTOBJK1
             FBACSID OF MRBACSTRL2-R                                    PRTOBJK1
           START MRBACSTRL2 KEY NOT < EXTERNALLY-DESCRIBED-KEY          PRTOBJK1
             FORMAT IS 'FBACSID'                                        PRTOBJK1
           END-START                                                    PRTOBJK1
           IF (C-IO-ERR) THEN                                           PRTOBJK1
               STOP RUN                                                 PRTOBJK1
           END-IF                                                       PRTOBJK1
      *    Read next record with user selection                         PRTOBJK1
           PERFORM A3READ                                               PRTOBJK1
           IF (W0EOFA NOT = C-IND-OFF) THEN                             PRTOBJK1
               CONTINUE                                                 PRTOBJK1
           ELSE                                                         PRTOBJK1
      *        Request all headings                                     PRTOBJK1
      *        First page                                               PRTOBJK1
               MOVE 'Y' TO W0AL1P                                       PRTOBJK1
      *        Batch Number                                             PRTOBJK1
               MOVE 'Y' TO W0AL00                                       PRTOBJK1
      *        Set column headings flag                                 PRTOBJK1
               MOVE 'Y' TO W0ACDT                                       PRTOBJK1
      *        Print report body                                        PRTOBJK1
               PERFORM UNTIL NOT (W0EOFA = C-IND-OFF)                   PRTOBJK1
      *            Prepare heading formats for printing                 PRTOBJK1
                   PERFORM A1PHDR                                       PRTOBJK1
      *            Print report detail line                             PRTOBJK1
                   PERFORM A2PDTL                                       PRTOBJK1
      *            Read next record with user selection                 PRTOBJK1
                   PERFORM A3READ                                       PRTOBJK1
      *            Print totals                                         PRTOBJK1
                   PERFORM A4PTOT                                       PRTOBJK1
               END-PERFORM                                              PRTOBJK1
           END-IF                                                       PRTOBJK1
      *==============================================================   PRTOBJK1
           CONTINUE.                                                    PRTOBJK1
       A0EXIT.                                                          PRTOBJK1
           EXIT.                                                        PRTOBJK1
      /EJECT                                                            PRTOBJK1
       A1PHDR SECTION.                                                  PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Prepare heading formats for printing                         PRTOBJK1
      *==============================================================   PRTOBJK1
           IF (W0AL1P = 'Y') THEN                                       PRTOBJK1
      *        Load related totals format                               PRTOBJK1
      *        BACs Renault Name                                        PRTOBJK1
               MOVE SPACES TO ZDCFTT OF ZDFINTTL-WS-O                   PRTOBJK1
      *        BACs Renault Code                                        PRTOBJK1
               MOVE ZERO TO ZDJBNU OF ZDFINTTL-WS-O                     PRTOBJK1
      *        BACs Renault Account No                                  PRTOBJK1
               MOVE ZERO TO ZDJCNU OF ZDFINTTL-WS-O                     PRTOBJK1
      *        Total BACs Amount                                        PRTOBJK1
               MOVE ZERO TO ZDYLVA OF ZDFINTTL-WS-O                     PRTOBJK1
      *        Record Counter                                           PRTOBJK1
               MOVE ZERO TO ZDBBNU OF ZDFINTTL-WS-O                     PRTOBJK1
      *        Signal that format is now ready to print                 PRTOBJK1
               MOVE 'Y' TO W0AP1P                                       PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
           IF (W0AL00 = 'Y') THEN                                       PRTOBJK1
      *        Load key header format                                   PRTOBJK1
      *        Batch Number                                             PRTOBJK1
               MOVE S8VABATNO OF FBACSID TO ZBVABATNO OF ZBKEYHDR-WS-O  PRTOBJK1
      *        Signal that format is now ready to print                 PRTOBJK1
               MOVE 'Y' TO W0AP00                                       PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *==============================================================   PRTOBJK1
           CONTINUE.                                                    PRTOBJK1
       A1EXIT.                                                          PRTOBJK1
           EXIT.                                                        PRTOBJK1
      /EJECT                                                            PRTOBJK1
       A2PDTL SECTION.                                                  PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Process detail record                                        PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Load details format                                          PRTOBJK1
      *    MR Company Number                                            PRTOBJK1
           MOVE S8COMNBR OF FBACSID TO ZCCOMNBR OF ZCDTLRCD-WS-O        PRTOBJK1
      *    MR Contract Account Nbr                                      PRTOBJK1
           MOVE S8MRCONAN OF FBACSID TO ZCMRCONAN OF ZCDTLRCD-WS-O      PRTOBJK1
      *    MR Purch/Invoice Number                                      PRTOBJK1
           MOVE S8PURNUM OF FBACSID TO ZCPURNUM OF ZCDTLRCD-WS-O        PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           MOVE S8VABATNO OF FBACSID TO ZCVABATNO OF ZCDTLRCD-WS-O      PRTOBJK1
      *    BACs Sort Code                                               PRTOBJK1
           MOVE S8CCCE OF FBACSID TO ZCCCCE OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Account No.                                             PRTOBJK1
           MOVE S8CDCE OF FBACSID TO ZCCDCE OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Account type                                            PRTOBJK1
           MOVE S8JANU OF FBACSID TO ZCJANU OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Transaction Type                                        PRTOBJK1
           MOVE S8CECE OF FBACSID TO ZCCECE OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Renault Code                                            PRTOBJK1
           MOVE S8JBNU OF FBACSID TO ZCJBNU OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Renault Account No                                      PRTOBJK1
           MOVE S8JCNU OF FBACSID TO ZCJCNU OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Filler                                                  PRTOBJK1
           MOVE S8JDNU OF FBACSID TO ZCJDNU OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Renault Name                                            PRTOBJK1
           MOVE S8CFTT OF FBACSID TO ZCCFTT OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Renault Ref No                                          PRTOBJK1
           MOVE S8CGTT OF FBACSID TO ZCCGTT OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Recipient Name                                          PRTOBJK1
           MOVE S8CHTT OF FBACSID TO ZCCHTT OF ZCDTLRCD-WS-O            PRTOBJK1
      *    MR Payment Process Status                                    PRTOBJK1
           MOVE S8GISS OF FBACSID TO ZCGISS OF ZCDTLRCD-WS-O            PRTOBJK1
      *    BACs Amount                                                  PRTOBJK1
           MOVE S8YKVA OF FBACSID TO ZCYKVA OF ZCDTLRCD-WS-O            PRTOBJK1
      *    *USER                                                        PRTOBJK1
           MOVE S8USR OF FBACSID TO ZCUSR OF ZCDTLRCD-WS-O              PRTOBJK1
      *    *PROGRAM                                                     PRTOBJK1
           MOVE S8PGM OF FBACSID TO ZCPGM OF ZCDTLRCD-WS-O              PRTOBJK1
      *    *JOB                                                         PRTOBJK1
           MOVE S8JOB OF FBACSID TO ZCJOB OF ZCDTLRCD-WS-O              PRTOBJK1
      *    Job Date (8)                                                 PRTOBJK1
           MOVE S8JOBDTE8 OF FBACSID TO ZCJOBDTE8 OF ZCDTLRCD-WS-O      PRTOBJK1
      *    *Job time                                                    PRTOBJK1
           MOVE S8JTM OF FBACSID TO ZCJTM OF ZCDTLRCD-WS-O              PRTOBJK1
      *    Signal that format is now ready to print                     PRTOBJK1
           MOVE 'Y' TO W0APDT                                           PRTOBJK1
      *    Call print routine                                           PRTOBJK1
           PERFORM Q0PRNT                                               PRTOBJK1
      *                                                                 PRTOBJK1
      *==============================================================   PRTOBJK1
           CONTINUE.                                                    PRTOBJK1
       A2EXIT.                                                          PRTOBJK1
           EXIT.                                                        PRTOBJK1
      /EJECT                                                            PRTOBJK1
       A3READ SECTION.                                                  PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Read next record                                             PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Hold current values                                          PRTOBJK1
           MOVE S8VABATNO OF FBACSID TO WZA001                          PRTOBJK1
      *    Read next record                                             PRTOBJK1
           SET C-UNTIL-FALSE TO TRUE                                    PRTOBJK1
           PERFORM UNTIL (C-UNTIL-TRUE)                                 PRTOBJK1
               SET C-INDICATOR-OFF(90) TO TRUE                          PRTOBJK1
               READ MRBACSTRL2 NEXT                                     PRTOBJK1
                 FORMAT IS 'FBACSID'                                    PRTOBJK1
               END-READ                                                 PRTOBJK1
               IF (C-EOF) THEN                                          PRTOBJK1
                   SET C-INDICATOR-ON(90) TO TRUE                       PRTOBJK1
               ELSE                                                     PRTOBJK1
                   IF (C-IO-ERR) THEN                                   PRTOBJK1
                       STOP RUN                                         PRTOBJK1
                   ELSE                                                 PRTOBJK1
                       MOVE CORRESPONDING                               PRTOBJK1
                         FBACSID OF MRBACSTRL2-R TO                     PRTOBJK1
                         KRSA-EXT                                       PRTOBJK1
                       MOVE KRSA-EXT TO KRSA-TMP                        PRTOBJK1
                       IF (KRSA NOT = KRSA-TMP) THEN                    PRTOBJK1
                           SET C-INDICATOR-ON(90) TO TRUE               PRTOBJK1
                       END-IF                                           PRTOBJK1
                   END-IF                                               PRTOBJK1
               END-IF                                                   PRTOBJK1
      *        Initialise Full Externally Described Keylist             PRTOBJK1
      *        Batch Number                                             PRTOBJK1
               MOVE 99999 TO S8VABATNO OF KRSA-EXT                      PRTOBJK1
      *        Transfer error indicator to EOF flag                     PRTOBJK1
               MOVE IND(90) TO W0EOFA                                   PRTOBJK1
      *        Quit if no record read                                   PRTOBJK1
               IF (W0EOFA NOT = C-IND-ON) THEN                          PRTOBJK1
      *            Select record unless user action states otherwise    PRTOBJK1
                   MOVE 'Y' TO W0RSL                                    PRTOBJK1
               END-IF                                                   PRTOBJK1
           IF (W0RSL = 'Y' OR                                           PRTOBJK1
               W0EOFA = C-IND-ON)                                       PRTOBJK1
             SET C-UNTIL-TRUE TO TRUE                                   PRTOBJK1
           END-IF                                                       PRTOBJK1
           END-PERFORM                                                  PRTOBJK1
      *                                                                 PRTOBJK1
      *    Reset key level breaks                                       PRTOBJK1
      *    Batch Number                                                 PRTOBJK1
           MOVE SPACES TO W0AL00                                        PRTOBJK1
           IF (W0EOFA = C-IND-ON) THEN                                  PRTOBJK1
      *        End of file - Signal all level breaks                    PRTOBJK1
      *        Batch Number                                             PRTOBJK1
               MOVE 'Y' TO W0AL00                                       PRTOBJK1
           ELSE                                                         PRTOBJK1
      *        Next record - Detect level breaks                        PRTOBJK1
               IF (S8VABATNO OF FBACSID NOT = WZA001) THEN              PRTOBJK1
      *            Set on level break indicator                         PRTOBJK1
                   MOVE 'Y' TO W0AL00                                   PRTOBJK1
               END-IF                                                   PRTOBJK1
           END-IF                                                       PRTOBJK1
      *==============================================================   PRTOBJK1
           CONTINUE.                                                    PRTOBJK1
       A3EXIT.                                                          PRTOBJK1
           EXIT.                                                        PRTOBJK1
      /EJECT                                                            PRTOBJK1
       A4PTOT SECTION.                                                  PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Print report Totals                                          PRTOBJK1
      *==============================================================   PRTOBJK1
      *    Print level break totals as required                         PRTOBJK1
           IF (W0AL00 = 'Y') THEN                                       PRTOBJK1
      *        Signal header format is no longer ready                  PRTOBJK1
               MOVE SPACES TO W0AP00                                    PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
           IF (W0EOFA = C-IND-ON) THEN                                  PRTOBJK1
      *        If there is not enough space on the                      PRTOBJK1
      *        physical page for this format:                           PRTOBJK1
               SUBTRACT YXCLN OF ACBACSLSTP-I-O-PRTF FROM YXPGL OF      PRTOBJK1
                 ACBACSLSTP-OPEN GIVING YXWRK                           PRTOBJK1
               IF (YXWRK NOT > 7) THEN                                  PRTOBJK1
      *            Signal new page required                             PRTOBJK1
                   MOVE 'Y' TO W0NEWP                                   PRTOBJK1
      *            Start new page                                       PRTOBJK1
                   PERFORM Q0PRNT                                       PRTOBJK1
               END-IF                                                   PRTOBJK1
      *        Print format                                             PRTOBJK1
               WRITE ACBACSLSTP-F FROM ZDFINTTL-WS-O                    PRTOBJK1
                 FORMAT IS 'ZDFINTTL' INDICATORS ARE INDICS             PRTOBJK1
               END-WRITE                                                PRTOBJK1
               ACCEPT ACBACSLSTP-I-O-PRTF FROM I-O-FEEDBACK-AREA FOR    PRTOBJK1
                 ACBACSLSTP                                             PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *==============================================================   PRTOBJK1
           CONTINUE.                                                    PRTOBJK1
       A4EXIT.                                                          PRTOBJK1
           EXIT.                                                        PRTOBJK1
      /EJECT                                                            PRTFILK1
       Q0PRNT SECTION.                                                  PRTFILK1
      *==============================================================   PRTFILK1
      *    Print report formats                                         PRTFILK1
      *==============================================================   PRTFILK1
      *    Select formats to print                                      PRTFILK1
           PERFORM Q1FSEL                                               PRTFILK1
      *    Calculate length of formats selected for printing            PRTFILK1
           PERFORM Q2PLEN                                               PRTFILK1
      *    Add column heading length to print length                    PRTFILK1
           ADD W0COLN TO W0FSUM                                         PRTFILK1
           IF (W0NEWP NOT = 'Y') THEN                                   PRTFILK1
      *        Signal overflow if requested headings would cause        PRTFILK1
      *        detail format to start past the overflow line            PRTFILK1
               IF (W0FSUM > W0OFL) THEN                                 PRTFILK1
                   MOVE 'Y' TO W0NEWP                                   PRTFILK1
               ELSE                                                     PRTFILK1
      *            Signal overflow if requested headings would cause    PRTFILK1
      *            Detail format to be printed past end of page         PRTFILK1
                   ADD W0DTLN TO W0FSUM                                 PRTFILK1
                   IF (W0FSUM > W0PGL) THEN                             PRTFILK1
                       MOVE 'Y' TO W0NEWP                               PRTFILK1
                   END-IF                                               PRTFILK1
               END-IF                                                   PRTFILK1
           END-IF                                                       PRTFILK1
      *    Set new page flag if external overflow occured               PRTFILK1
           IF (C-INDICATOR-ON(97)) THEN                                 PRTFILK1
               MOVE 'Y' TO W0NEWP                                       PRTFILK1
           END-IF                                                       PRTFILK1
      *    Print Standard report header of Prt BACs List                PRTOBJK1
      *    If it is ready to print, then do so,                         PRTOBJK1
           IF (W0NEWP = 'Y') THEN                                       PRTOBJK1
               PERFORM Q3PTNP                                           PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *    Print First Page Format of Prt BACs List                     PRTOBJK1
      *    If it is ready to print, then do so,                         PRTOBJK1
      *    or if new page & print on new page selected &                PRTOBJK1
      *    active then set print format flag                            PRTOBJK1
           IF (W0AP1P = 'Y' OR                                          PRTOBJK1
               W0NEWP = 'Y' AND                                         PRTOBJK1
               W0AP1P = 'P') THEN                                       PRTOBJK1
      *        Reset format print flag                                  PRTOBJK1
               MOVE SPACES TO W0AP1P                                    PRTOBJK1
      *        Clear first page flag.                                   PRTOBJK1
               MOVE SPACES TO W0AL1P                                    PRTOBJK1
           END-IF                                                       PRTOBJK1
      *    Print Batch Number of Prt BACs List                          PRTOBJK1
      *    If it is ready to print, then do so,                         PRTOBJK1
      *    or if new page & print on new page selected &                PRTOBJK1
      *    active then set print format flag                            PRTOBJK1
           IF (W0AP00 = 'Y' OR                                          PRTOBJK1
               W0NEWP = 'Y' AND                                         PRTOBJK1
               W0AP00 = 'P') THEN                                       PRTOBJK1
      *        Print format                                             PRTOBJK1
               WRITE ACBACSLSTP-F FROM ZBKEYHDR-WS-O                    PRTOBJK1
                 FORMAT IS 'ZBKEYHDR' INDICATORS ARE INDICS             PRTOBJK1
               END-WRITE                                                PRTOBJK1
               ACCEPT ACBACSLSTP-I-O-PRTF FROM I-O-FEEDBACK-AREA FOR    PRTOBJK1
                 ACBACSLSTP                                             PRTOBJK1
      *        Set column headings flag                                 PRTOBJK1
               MOVE 'Y' TO W0ACDT                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *        Reset format print flag                                  PRTOBJK1
               MOVE SPACES TO W0AP00                                    PRTOBJK1
           END-IF                                                       PRTOBJK1
      *    Print Detail line. of Prt BACs List                          PRTOBJK1
      *    If new page then set column headings active                  PRTOBJK1
           IF (W0NEWP = 'Y') THEN                                       PRTOBJK1
               MOVE 'Y' TO W0ACDT                                       PRTOBJK1
           END-IF                                                       PRTOBJK1
      *    If it is ready to print, then do so,                         PRTOBJK1
      *    or if new page & print on new page selected &                PRTOBJK1
      *    active then set print format flag                            PRTOBJK1
           IF (W0APDT = 'Y' OR                                          PRTOBJK1
               W0NEWP = 'Y' AND                                         PRTOBJK1
               W0APDT = 'P') THEN                                       PRTOBJK1
               MOVE 'Y' TO W0PFM                                        PRTOBJK1
      *        USER: On print of detail format                          MSGACTK2
      *        Set Originator values first time through                 MSGACTK2
      *        CASE: LCL.First Time Through is Yes                      MSGACTK2
      *        *IF                                                      CBLIFXK1
               IF (YL0001 OF WORK-CONTEXT = 'Y') THEN                   CBLIFXK1
      *            BACs Renault Name                                    CBLMOVK1
                   MOVE ZCCFTT OF ZCDTLRCD-WS-O TO ZDCFTT OF            CBLMOVK1
                     ZDFINTTL-WS-O                                      CBLMOVK1
      *            BACs Renault Code                                    CBLMOVK1
                   MOVE ZCJBNU OF ZCDTLRCD-WS-O TO ZDJBNU OF            CBLMOVK1
                     ZDFINTTL-WS-O                                      CBLMOVK1
      *            BACs Renault Account No                              CBLMOVK1
                   MOVE ZCJCNU OF ZCDTLRCD-WS-O TO ZDJCNU OF            CBLMOVK1
                     ZDFINTTL-WS-O                                      CBLMOVK1
      *            First Time Through                                   CBLMOVK1
                   MOVE 'N' TO YL0001 OF WORK-CONTEXT                   CBLMOVK1
               END-IF                                                   MSGACTK2
      *        Record Counter                                           CBLADDK1
               ADD ZDBBNU OF ZDFINTTL-WS-O, 1 GIVING ZDBBNU OF          CBLADDK1
                 ZDFINTTL-WS-O                                          CBLADDK1
      *        Total BACs Amount                                        CBLSUMK1
               ADD ZCYKVA OF ZCDTLRCD-WS-O TO ZDYLVA OF ZDFINTTL-WS-O   CBLSUMK1
               IF (W0PFM = 'Y') THEN                                    PRTOBJK1
      *            Print column headings if required                    PRTOBJK1
                   IF (W0ACDT = 'Y') THEN                               PRTOBJK1
                       WRITE ACBACSLSTP-F FROM ZCCOLHDG-WS-O            PRTOBJK1
                         FORMAT IS 'ZCCOLHDG' INDICATORS ARE INDICS     PRTOBJK1
                       END-WRITE                                        PRTOBJK1
                       ACCEPT ACBACSLSTP-I-O-PRTF FROM                  PRTOBJK1
                         I-O-FEEDBACK-AREA FOR ACBACSLSTP               PRTOBJK1
      *                Clear column headings control flag               PRTOBJK1
                       MOVE SPACES TO W0ACDT                            PRTOBJK1
                   END-IF                                               PRTOBJK1
      *            Print format                                         PRTOBJK1
                   WRITE ACBACSLSTP-F FROM ZCDTLRCD-WS-O                PRTOBJK1
                     FORMAT IS 'ZCDTLRCD' INDICATORS ARE INDICS         PRTOBJK1
                   END-WRITE                                            PRTOBJK1
                   ACCEPT ACBACSLSTP-I-O-PRTF FROM I-O-FEEDBACK-AREA    PRTOBJK1
                     FOR ACBACSLSTP                                     PRTOBJK1
               END-IF                                                   PRTOBJK1
      *                                                                 PRTOBJK1
      *        Reset format print flag                                  PRTOBJK1
               MOVE SPACES TO W0APDT                                    PRTOBJK1
           END-IF                                                       PRTOBJK1
      *    Clear new page flag                                          PRTFILK1
           MOVE SPACES TO W0NEWP                                        PRTFILK1
      *==============================================================   PRTFILK1
           CONTINUE.                                                    PRTFILK1
       Q0EXIT.                                                          PRTFILK1
           EXIT.                                                        PRTFILK1
      /EJECT                                                            PRTFILK1
       Q1FSEL SECTION.                                                  PRTFILK1
      *==============================================================   PRTFILK1
      *    Format select                                                PRTFILK1
      *==============================================================   PRTFILK1
      *==============================================================   PRTFILK1
           CONTINUE.                                                    PRTFILK1
       Q1EXIT.                                                          PRTFILK1
           EXIT.                                                        PRTFILK1
      /EJECT                                                            PRTFILK1
       Q2PLEN SECTION.                                                  PRTFILK1
      *==============================================================   PRTFILK1
      *    Evaluate print length                                        PRTFILK1
      *==============================================================   PRTFILK1
           MOVE YXCLN OF ACBACSLSTP-I-O-PRTF TO W0FSUM                  PRTFILK1
           MOVE ZERO TO W0DTLN                                          PRTFILK1
           MOVE ZERO TO W0COLN                                          PRTFILK1
      *    * First Page Format of Prt BACs List                         PRTOBJK1
           IF (W0AP1P = 'Y') THEN                                       PRTOBJK1
               ADD 0 TO W0FSUM                                          PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *    * Batch Number of Prt BACs List                              PRTOBJK1
           IF (W0AP00 = 'Y') THEN                                       PRTOBJK1
               ADD 2 TO W0FSUM                                          PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *    Detail line. OF Prt BACs List                                PRTOBJK1
           IF (W0APDT = 'Y') THEN                                       PRTOBJK1
               MOVE 1 TO W0DTLN                                         PRTOBJK1
               IF (W0ACDT = 'Y') THEN                                   PRTOBJK1
                   MOVE 3 TO W0COLN                                     PRTOBJK1
               END-IF                                                   PRTOBJK1
           END-IF                                                       PRTOBJK1
      *                                                                 PRTOBJK1
      *==============================================================   PRTFILK1
           CONTINUE.                                                    PRTFILK1
       Q2EXIT.                                                          PRTFILK1
           EXIT.                                                        PRTFILK1
      /EJECT                                                            PRTFILK1
       Q3PTNP SECTION.                                                  PRTFILK1
      *==============================================================   PRTFILK1
      *    Print report formats                                         PRTFILK1
      *==============================================================   PRTFILK1
      *    Print format                                                 PRTFILK1
           WRITE ACBACSLSTP-F FROM ZAPAGHDR-WS-O                        PRTFILK1
             FORMAT IS 'ZAPAGHDR' INDICATORS ARE INDICS                 PRTFILK1
           END-WRITE                                                    PRTFILK1
           ACCEPT ACBACSLSTP-I-O-PRTF FROM I-O-FEEDBACK-AREA FOR        PRTFILK1
             ACBACSLSTP                                                 PRTFILK1
      *    Clear page overflow indicator                                PRTFILK1
           SET C-INDICATOR-OFF(97) TO TRUE                              PRTFILK1
      *==============================================================   PRTFILK1
           CONTINUE.                                                    PRTFILK1
       Q3EXIT.                                                          PRTFILK1
           EXIT.                                                        PRTFILK1
      /EJECT                                                            MSGACTK2
       UA1SUBR SECTION.                                                 MSGACTK2
      *==============================================================   MSGACTK2
      *    Program Banner                                               MSGACTK2
      *==============================================================   MSGACTK2
      *    K. Sutton - 22/04/03                                         MSGACTK2
      *    BACs List created to check BACs file creation for Major      MSGACTK2
      *      Rentals                                                    MSGACTK2
      *    Buy back payment automation.                                 MSGACTK2
      *    BACs file and list are created on the day of invoice         MSGACTK2
      *      reconciliation                                             MSGACTK2
      *    but the BACs file is not processed for two working days      MSGACTK2
      *      (then taking                                               MSGACTK2
      *    three days to go through) to fulfil the requirement of a fiveMSGACTK2
      *    working day turn around.                                     MSGACTK2
      *==============================================================   MSGACTK2
           CONTINUE.                                                    MSGACTK2
       UA1EXIT.                                                         MSGACTK2
           EXIT.                                                        MSGACTK2
      /EJECT                                                            PRTFILK1
       ZXEXPG SECTION.                                                  PRTFILK1
      *==============================================================   PRTFILK1
      *    Exit program                                                 PRTFILK1
      *==============================================================   PRTFILK1
           MOVE SPACES TO P0RTN                                         PRTFILK1
           PERFORM ZYEXPG                                               PRTFILK1
      *==============================================================   PRTFILK1
           CONTINUE.                                                    PRTFILK1
       ZXEXIT.                                                          PRTFILK1
           EXIT.                                                        PRTFILK1
      /EJECT                                                            CBLUPDK1
       ZYEXPG SECTION.                                                  CBLUPDK1
      *==============================================================   CBLUPDK1
      *    Exit program: Direct                                         CBLUPDK1
      *==============================================================   CBLUPDK1
           CLOSE ACBACSLSTP                                             CBLUPDK1
           CLOSE MRBACSTRL2                                             CBLUPDK1
      *    Reset entry parameters as appropriate                        CBLUPDK1
           PERFORM ZZEXPM.                                              CBLUPDK1
      *    Exit program                                                 CBLUPDK1
           CONTINUE.                                                    CBLUPDK1
       ZYEXPG-EXIT.                                                     CBLUPDK1
           GOBACK.                                                      CBLUPDK1
      *==============================================================   CBLUPDK1
           CONTINUE.                                                    CBLUPDK1
       ZYEXIT.                                                          CBLUPDK1
           EXIT.                                                        CBLUPDK1
      /EJECT                                                            DCLPARK1
       ZZEXPM SECTION.                                                  DCLPARK1
      *==============================================================   DCLPARK1
      *    Return parameters from work fields                           DCLPARK1
      *==============================================================   DCLPARK1
      *==============================================================   DCLPARK1
           CONTINUE.                                                    DCLPARK1
       ZZPEXT.                                                          DCLPARK1
           EXIT.                                                        DCLPARK1
      /EJECT                                                            CBLHDRK1
       ZZINIT SECTION.                                                  CBLHDRK1
      *==============================================================   CBLHDRK1
      *    Initialisation                                               CBLHDRK1
      *==============================================================   CBLHDRK1
           IF (W0ICL = SPACES) THEN                                     CBLHDRK1
      *        *Initial call                                            CBLHDRK1
               MOVE 'Y' TO W0ICL                                        CBLHDRK1
           ELSE                                                         CBLHDRK1
               MOVE 'N' TO W0ICL                                        CBLHDRK1
           END-IF                                                       CBLHDRK1
           MOVE SPACES TO P0RTN                                         CBLHDRK1
           MOVE SPACES TO W0RTN                                         CBLHDRK1
           MOVE ZEROS  TO W0RTW                                         CBLHDRK1
           MOVE SPACES TO W0RSF                                         CBLHDRK1
           MOVE '400' TO W0ENV                                          CBLHDRK1
           MOVE ALL B'0' TO INDICS                                      CBLHDRK1
           MOVE SPACES TO ZZPGM OF JOB-CONTEXT                          CBLHDRK1
      *    Retrieve job attributes                                      CBLHDRK1
           CALL 'Y2RTJCR' USING                                         CBLHDRK1
             JOB-CONTEXT                                                CBLHDRK1
           END-CALL                                                     CBLHDRK1
      *    Setup job date/time                                          CBLHDRK1
           MOVE ZZSD7 OF JOB-CONTEXT TO ZZJDT                           CBLHDRK1
           ACCEPT ZZTIME FROM TIME                                      CBLHDRK1
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT                           CBLHDRK1
           MOVE 'ACBACSLSTS' TO ZZPGM OF JOB-CONTEXT                    CBLHDRK1
      *    Open files                                                   CBLUPDK1
           OPEN OUTPUT ACBACSLSTP                                       CBLUPDK1
           ACCEPT ACBACSLSTP-OPEN FROM OPEN-FEEDBACK-AREA FOR ACBACSLSTPCBLUPDK1
      *    Move main file information to JOB context                    CBLUPDK1
           MOVE CORRESPONDING OPENFA OF ACBACSLSTP-OPEN TO JOB-CONTEXT  CBLUPDK1
           CALL 'Y2QLVNR' USING                                         CBLUPDK1
             ZZFFL OF JOB-CONTEXT                                       CBLUPDK1
             ZZFLB OF JOB-CONTEXT                                       CBLUPDK1
             ZZFQL OF JOB-CONTEXT                                       CBLUPDK1
           END-CALL                                                     CBLUPDK1
           OPEN INPUT MRBACSTRL2                                        CBLUPDK1
           ACCEPT MRBACSTRL2-OPEN FROM OPEN-FEEDBACK-AREA FOR MRBACSTRL2CBLUPDK1
           MOVE 'Y' TO W0OPN                                            CBLUPDK1
           MOVE 'N' TO W0PMT                                            CBLUPDK1
      *    Define local work field First Time Through                   ACTCTXK4
           MOVE SPACES TO YL0001 OF WORK-CONTEXT                        ACTCTXK4
           MOVE ZZPGM OF JOB-CONTEXT TO ZAPGM OF ZAPAGHDR-WS-O          PRTFILK1
           MOVE SPACES TO W0PFM                                         PRTFILK1
           MOVE ZERO TO YXWRK                                           PRTFILK1
           MOVE ZERO TO YXHDL                                           PRTFILK1
      *    Adjust page length and overflow as necessary                 PRTFILK1
           SUBTRACT 2 FROM YXPGL OF ACBACSLSTP-OPEN GIVING W0PGL        PRTFILK1
           IF (YXOFL OF ACBACSLSTP-OPEN < W0PGL) THEN                   PRTFILK1
               MOVE YXOFL OF ACBACSLSTP-OPEN TO W0OFL                   PRTFILK1
           ELSE                                                         PRTFILK1
               SUBTRACT 2 FROM W0PGL GIVING W0OFL                       PRTFILK1
           END-IF                                                       PRTFILK1
      *    Clear overflow indicator                                     PRTFILK1
           SET C-INDICATOR-OFF(97) TO TRUE                              PRTFILK1
      *    Request new page                                             PRTFILK1
           MOVE 'Y' TO W0NEWP                                           PRTFILK1
      *    USER: Initialize program                                     MSGACTK2
      *    Program Banner                                               MSGACTK2
           PERFORM UA1SUBR                                              MSGACTK2
      *    First Time Through                                           CBLMOVK1
           MOVE 'Y' TO YL0001 OF WORK-CONTEXT                           CBLMOVK1
      *==============================================================   CBLHDRK1
           CONTINUE.                                                    CBLHDRK1
       ZZEXIT.                                                          CBLHDRK1
           EXIT.                                                        CBLHDRK1
