       PROCESS APOST.                                                   CBLHDRK1
      ***************************************************************   CBLHDRK1
       IDENTIFICATION DIVISION.                                         CBLHDRK1
     H/TITLE Pmt replace invalid a/c   Prompt & validate record         CBLHDRK1
     Z* CRTCBLPGM                                                       CBLHDRK1
     Z* OPTION(*SRCDBG) CVTOPT(*DATETIME)                               CBLHDRK1
      *                                                                 CBLHDRK1
     H* SYNOPSIS :                                                      PMTVALK1
     H* - Prompts fields, allowing user changes                         PMTVALK1
     H* - Validates fields                                              PMTVALK1
     H* - If valid, performs an action                                  PMTVALK1
     H* Generated by  : COOL:2E  Version:  1135                         CBLHDRK1
     H* Function type : Prompt & validate record  Version:   0.1        CBLHDRK1
      *                                                                 CBLHDRK1
     H* Company    : Vehicle Finance                                    CBLHDRK1
     H* System     : Vehicle Finance                                    CBLHDRK1
     H* User name  : AG00191                                            CBLHDRK1
     H* Date       : 16/05/07 time: 16:39:16                            CBLHDRK1
     H* Copyright  : Vehicle Finance                                    CBLHDRK1
      *                                                                 CBLHDRK1
      *==============================================================   CBLHDRK1
     M* MAINTENANCE   :                                                 CBLHDRK1
      *==============================================================   CBLHDRK1
       PROGRAM-ID.  ACI000200S.                                         CBLHDRK1
       SECURITY.    (C) COPYRIGHT Renault UK Ltd. 2007                  CBLUFNK1
                    Reproduction is not allowed without prior permissionCBLUFNK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       ENVIRONMENT DIVISION.                                            CBLHDRK1
       CONFIGURATION SECTION.                                           CBLHDRK1
       SOURCE-COMPUTER.  IBM-AS400.                                     CBLHDRK1
       OBJECT-COMPUTER.  IBM-AS400.                                     CBLHDRK1
       SPECIAL-NAMES.  OPEN-FEEDBACK IS OPEN-FEEDBACK-AREA,             CBLHDRK1
           I-O-FEEDBACK IS I-O-FEEDBACK-AREA.                           CBLHDRK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       INPUT-OUTPUT SECTION.                                            CBLHDRK1
       FILE-CONTROL.                                                    CBLHDRK1
      *                                                                 CBLHDRK1
           SELECT ACI000200D                                            CBLUPDK1
             ASSIGN TO WORKSTATION-ACI000200D-SI                        CBLUPDK1
             ORGANIZATION IS TRANSACTION                                CBLUPDK1
             FILE STATUS IS FILE-STATUS, MAJOR-MINOR-CODE.              CBLUPDK1
      *    DSP: Pmt replace invalid a/c   Prompt & validate record      CBLUPDK1
      *                                                                 CBLUPDK1
           SELECT JSVLLSL9                                              CVTSTSK1
             ASSIGN TO DATABASE-JSVLLSL9                                CVTSTSK1
             ORGANIZATION IS INDEXED                                    CVTSTSK1
             ACCESS MODE IS DYNAMIC                                     CVTSTSK1
             RECORD KEY IS EXTERNALLY-DESCRIBED-KEY                     CVTSTSK1
             FILE STATUS IS FILE-STATUS.                                CVTSTSK1
      *    Values list details file                                     CVTSTSK1
      *                                                                 CVTSTSK1
       I-O-CONTROL.                                                     CBLHDRK1
      *                                                                 CBLHDRK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       DATA DIVISION.                                                   CBLHDRK1
       FILE SECTION.                                                    CBLHDRK1
      *                                                                 CBLHDRK1
      *                                                                 CVTSTSK1
       FD  JSVLLSL9                                                     CVTSTSK1
           LABEL RECORDS ARE STANDARD.                                  CVTSTSK1
       01  JSVLLSL9-R.                                                  CVTSTSK1
           COPY DD-ALL-FORMATS OF JSVLLSL9.                             CVTSTSK1
      *                                                                 CBLUPDK1
       FD  ACI000200D                                                   CBLUPDK1
           LABEL RECORDS ARE STANDARD.                                  CBLUPDK1
       01  ACI000200D-F.                                                CBLUPDK1
           COPY DDS-ALL-FORMATS OF ACI000200D.                          CBLUPDK1
           05 FILLER            PIC X(100).                             CBLUPDK1
      /EJECT                                                            CBLHDRK1
      ***************************************************************   CBLHDRK1
       WORKING-STORAGE SECTION.                                         CBLHDRK1
      *                                                                 CBLHDRK1
      *    Job context                                                  CBLHDRK1
       01  JOB-CONTEXT.                                                 CBLHDRK1
           COPY DDS-ALL-FORMATS OF Y2PGDSPK.                            CBLHDRK1
      *    Job date/time                                                CBLHDRK1
           03  IJBDTTM.                                                 CBLHDRK1
           05  ZZJDT PIC S9(7).                                         CBLHDRK1
           05  ZZJDTE REDEFINES ZZJDT.                                  CBLHDRK1
           07  ZZJCC PIC S9(1).                                         CBLHDRK1
           07  ZZJYY PIC S9(2).                                         CBLHDRK1
           07  ZZJMM PIC S9(2).                                         CBLHDRK1
           07  ZZJDD PIC S9(2).                                         CBLHDRK1
           05  ZZJTM PIC S9(6).                                         CBLHDRK1
           05  ZZJTME REDEFINES ZZJTM.                                  CBLHDRK1
           07  ZZJHH PIC S9(2).                                         CBLHDRK1
           07  ZZJNN PIC S9(2).                                         CBLHDRK1
           07  ZZJSS PIC S9(2).                                         CBLHDRK1
           03  ZZFQL PIC X(21).                                         CBLHDRK1
           03  ZZFLB PIC X(10).                                         CBLHDRK1
           03  ZZFFL PIC X(10).                                         CBLHDRK1
           03  ZZFMB PIC X(10).                                         CBLHDRK1
           03  ZZCDB PIC X(18).                                         CBLHDRK1
           03  ZZLDB PIC X(18).                                         CBLHDRK1
           03  ZZTMS PIC X(26).                                         CBLHDRK1
       01  ZZTIME.                                                      CBLHDRK1
           03  ZZHNS PIC S9(6).                                         CBLHDRK1
           03  ZZHH PIC S9(2).                                          CBLHDRK1
      *                                                                 CBLHDRK1
       77  C-IND-OFF PIC 1(1) VALUE B'0'.                               CBLHDRK1
       77  C-IND-ON PIC 1(1) VALUE B'1'.                                CBLHDRK1
      *                                                                 CBLHDRK1
       01  FILE-STATUS PIC X(2).                                        CBLHDRK1
           88  C-IO-OK VALUE '00'.                                      CBLHDRK1
           88  C-EOF VALUE '10' '46'.                                   CBLHDRK1
           88  C-NO-MOD-SFLRCDS VALUE '12'.                             CBLHDRK1
           88  C-IO-ERR VALUE '21' '22' '24' '30' '34' '90' '91' '92' '9CBLHDRK1
      -     '4' '95' '9A' '9H' '9I' '9K' '9M' '9N' '9P'.                CBLHDRK1
           88  C-NO-RECORD VALUE '23'.                                  CBLHDRK1
           88  C-RECORD-LOCKED VALUE '9D'.                              CBLHDRK1
      *                                                                 CBLHDRK1
       01  UNTIL-CONDITION PIC 1(1).                                    CBLHDRK1
           88  C-UNTIL-FALSE VALUE B'0'.                                CBLHDRK1
           88  C-UNTIL-TRUE VALUE B'1'.                                 CBLHDRK1
      *                                                                 CBLHDRK1
       01  FOREVER PIC 1(1) VALUE B'1'.                                 CBLHDRK1
           88  C-FOREVER VALUE B'1'.                                    CBLHDRK1
      *                                                                 CBLHDRK1
       01  WRK-IO-TRASH-AREA PIC X(1).                                  CBLHDRK1
      *                                                                 CBLHDRK1
       01  W0RTN PIC X(7).                                              CBLHDRK1
       01  W0RSF PIC X(1).                                              CBLHDRK1
       01  W0ENV PIC X(3).                                              CBLHDRK1
       01  W0RTW PIC S9(9) COMP-4.                                      CBLHDRK1
       01  W0ICL PIC X(1).                                              CBLHDRK1
       01  W0TRN PIC X(1).                                              PMTVALK1
       01  W0HLP PIC X(1).                                              DSPHLPK1
       01  W0HPMB PIC X(10).                                            DSPHLPK1
       01  YYHPFL PIC X(10).                                            DSPHLPK1
       01  YYHPLB PIC X(10).                                            DSPHLPK1
       01  ZHCSRW PIC S9(5) COMP-3.                                     DSPHLPK1
       01  ZHCSCL PIC S9(5) COMP-3.                                     DSPHLPK1
       01  ZZZCSRW PIC S9(3) COMP-3.                                    DSPHLPK1
       01  ZZZCSCL PIC S9(3) COMP-3.                                    DSPHLPK1
       01  YYHLVN PIC X(10).                                            DSPHLPK1
       01  W0GRP PIC X(10).                                             DSPHLPK1
       01  YYUSOP PIC X(10).                                            DSPHLPK1
       01  YYRW PIC S9(5) COMP-3.                                       DSPHLPK1
       01  YYCL PIC S9(5) COMP-3.                                       DSPHLPK1
       01  YYLGCT PIC S9(5) COMP-3.                                     DSPHLPK1
       01  YYLGVN PIC X(10).                                            DSPHLPK1
       01  ZAPGMQ PIC X(10).                                            PMTVALK1
       01  ZAPGRL PIC X(5).                                             PMTVALK1
       01  ZAFSMS PIC X(1).                                             PMTVALK1
       01  W0DCF PIC X(1).                                              PMTVALK1
      *    *PROGRAM                                                     SYSCTXK4
       01  YRWG00 PIC X(10).                                            SYSCTXK4
       01  ZAMSDA PIC X(132).                                           CBLMDAK1
      *    Message data for 'CHGDTAARA (char)'                          CBLMDAK1
       01  ZA0001-01 REDEFINES ZAMSDA.                                  CBLMDAK1
           03  ZA0001 PIC X(10).                                        CBLMDAK1
           03  ZA0002 PIC X(10).                                        CBLMDAK1
           03  ZA0003 PIC X(2000).                                      CBLMDAK1
       01  ZAMSID PIC X(7).                                             CBLEXMK1
       01  ZAMSGF PIC X(10).                                            CBLEXMK1
       01  ZADFMF PIC X(10).                                            CBLEXMK1
       01  DATA-AREA-NAME PIC X(10).                                    CBLEXMK1
      *    Workspace for zone operations in check numeric               CHKNBRK1
       01  XGBINB.                                                      CHKNBRK1
           03  XGBIND PIC X(1).                                         CHKNBRK1
           03  XGBINC PIC X(1).                                         CHKNBRK1
       01  XGBINV REDEFINES XGBINB.                                     CHKNBRK1
           03  XGBIN PIC S9(4) COMP-4.                                  CHKNBRK1
       01  XGZONE PIC S9(3) COMP-3.                                     CHKNBRK1
      *    Workspace for running through string in check numeric        CHKNBRK1
       01  XGCDVL PIC X(15).                                            CHKNBRK1
       01  XGCDLN PIC S9(3) COMP-3.                                     CHKNBRK1
       01  XGCHNO PIC S9(3) COMP-3.                                     CHKNBRK1
      *    Indicates whether error is found                             CHKNBRK1
       01  YXG-A.                                                       CHKNBRK1
           03  YXG PIC X(1) OCCURS 15.                                  CHKNBRK1
       01  WN30-A.                                                      CNFPMTK2
           03  WN30 PIC 1(1) OCCURS 30.                                 CNFPMTK2
       01  W0EXVL PIC X(25).                                            CHKSTSK1
       01  IND-COUNT PIC S9(5) COMP-3.                                  CNFPMTK2
      *    U:Object Name                                                CBLCLLK1
       01  WQ0001 PIC X(10).                                            CBLCLLK1
      *    U:Data area value (256)                                      CBLCLLK1
       01  WQ0002 PIC X(256).                                           CBLCLLK1
       01  W0CLPG PIC X(10).                                            CBLCLLK1
       01  YPMTFD PIC X(10).                                            GENF4K10
       01  YAFSCH PIC S9(4) COMP-3.                                     GENF4K10
       01  YZSFRC PIC S9(4) COMP-3.                                     GENF4K10
       01  YZSFDL PIC S9(4) COMP-3.                                     GENF4K10
       01  ZHSTRW PIC S9(4) COMP-3.                                     GENF4K10
       01  ZHNDRW PIC S9(4) COMP-3.                                     GENF4K10
       01  ZHRLEN PIC S9(4) COMP-3.                                     GENF4K10
       01  YPMRRN PIC S9(4) COMP-3.                                     GENF4K10
       01  ZHF4RW PIC S9(4) COMP-3.                                     GENF4K10
       01  ZHWK1Z PIC S9(4) COMP-3.                                     GENF4K10
       01  YSETCS PIC X(1).                                             CBLSETK2
       01  WCSRLC PIC X(3).                                             CBLSETK2
      *    *Cursor field                                                ACTCTXK4
       01  W0CFL PIC X(10).                                             ACTCTXK4
      *    *Cursor row                                                  ACTCTXK4
       01  W0CRW PIC S9(5) COMP-3.                                      ACTCTXK4
      *    *Cursor column                                               ACTCTXK4
       01  W0CCL PIC S9(5) COMP-3.                                      ACTCTXK4
       01  ZINPOS PIC S9(5) COMP-3.                                     CBLCSRK1
       01  ZAMSTP PIC X(7).                                             CBLUPDK1
      *                                                                 CBLUPDK1
       01  ACI000200D-I-O-DSPF.                                         CBLUPDK1
           COPY DDS-ALL-FORMATS OF Y2IDSPFIO.                           CBLUPDK1
      *    Subfile I/O feedback area                                    CBLUPDK1
      *                                                                 CBLUPDK1
       01  MAJOR-MINOR-CODE.                                            CBLUPDK1
           COPY DDS-ALL-FORMATS OF Y2IMAJMIN.                           CBLUPDK1
      *    Display major/minor code for timeouts                        CBLUPDK1
      *                                                                 CBLUPDK1
       01  ACI000200D-WS-O.                                             CBLUPDK1
           03  ZRCDDTL1-WS-O.                                           CBLUPDK1
           COPY DDS-ZRCDDTL1-O OF ACI000200D.                           CBLUPDK1
             06 FILLER            PIC X(1).                             CBLUPDK1
           03  ZCMDTXT1-WS-O.                                           CBLUPDK1
           COPY DDS-ZCMDTXT1-O OF ACI000200D.                           CBLUPDK1
             06 FILLER            PIC X(1).                             CBLUPDK1
           03  ZMSGCTL-WS-O.                                            CBLUPDK1
           COPY DDS-ZMSGCTL-O OF ACI000200D.                            CBLUPDK1
             06 FILLER            PIC X(1).                             CBLUPDK1
           03  ZCONFIRM-WS-O.                                           CBLUPDK1
           COPY DDS-ZCONFIRM-O OF ACI000200D.                           CBLUPDK1
             06 FILLER            PIC X(1).                             CBLUPDK1
       01  ACI000200D-WS-I.                                             CBLUPDK1
           03  ZRCDDTL1-WS-I.                                           CBLUPDK1
           COPY DDS-ZRCDDTL1-I OF ACI000200D.                           CBLUPDK1
             06  FILLER        PIC X.                                   CBLUPDK1
           03  ZCMDTXT1-WS-I.                                           CBLUPDK1
           COPY DDS-ZCMDTXT1-I OF ACI000200D.                           CBLUPDK1
             06  FILLER        PIC X.                                   CBLUPDK1
           03  ZMSGCTL-WS-I.                                            CBLUPDK1
           COPY DDS-ZMSGCTL-I OF ACI000200D.                            CBLUPDK1
             06  FILLER        PIC X.                                   CBLUPDK1
           03  ZCONFIRM-WS-I.                                           CBLUPDK1
           COPY DDS-ZCONFIRM-I OF ACI000200D.                           CBLUPDK1
             06  FILLER        PIC X.                                   CBLUPDK1
       01  W0OPN PIC X(1).                                              CBLUPDK1
       01  W0PMT PIC X(1).                                              CBLUPDK1
      *    U:Data Area Name                                             ACTCTXK4
       01  WORK-CONTEXT.                                                ACTCTXK4
           03  WUDTAARA PIC X(10).                                      ACTCTXK4
      *    GX GL code                                                   ACTCTXK4
           03  WUGXGLCDE PIC X(6).                                      ACTCTXK4
       01  KINEX.                                                       CVTSTSK1
      *    List number                                                  CVTSTSK1
           03  Y2LSNO PIC S9(7) COMP-3.                                 CVTSTSK1
      *    Internal value                                               CVTSTSK1
           03  Y2INVL PIC X(25).                                        CVTSTSK1
       01  KEXIN.                                                       CHKSTSK1
      *    List number                                                  CHKSTSK1
           03  Y2LSNO PIC S9(7) COMP-3.                                 CHKSTSK1
      *    External value                                               CHKSTSK1
           03  Y2EXVL PIC X(25).                                        CHKSTSK1
       01  W0NSRQ PIC X(1).                                             CHKSTSK1
      *                                                                 CBLHDRK1
      *    Indicators                                                   CBLHDRK1
       01  INDICS.                                                      CBLHDRK1
           03  IND PIC 1(1) OCCURS 99 INDICATOR 1.                      CBLHDRK1
           88  C-INDICATOR-ON VALUE B'1'.                               CBLHDRK1
           88  C-INDICATOR-OFF VALUE B'0'.                              CBLHDRK1
      *                                                                 CBLHDRK1
      * Utl set screen sysid (Pmt                                       CBLUFNK1
      *.Start.of.User.source........................................... CBLUFNK1
       01  RUK-DTAARA-NAME             PIC X(10).                       CBLUFNK1
      *.End.of.user.source............................................. CBLUFNK1
      /EJECT                                                            DCLPARK1
      ***************************************************************   DCLPARK1
       LINKAGE SECTION.                                                 DCLPARK1
      *    Return code                                                  DCLPARK1
       01  P0RTN PIC X(7).                                              DCLPARK1
      ***************************************************************   CBLHDRK1
       PROCEDURE DIVISION USING                                         CBLHDRK1
             P0RTN                                                      DCLPARK1
           .                                                            DCLPARK1
      ***************************************************************   CBLHDRK1
           CONTINUE.                                                    CBLHDRK1
       MAINLINE SECTION.                                                CBLHDRK1
      *    Initialize                                                   CBLHDRK1
           PERFORM ZZINIT                                               CBLHDRK1
      *                                                                 CBLHDRK1
      *    Conduct screen conversation                                  PMTVALK1
           PERFORM UNTIL NOT (C-FOREVER)                                PMTVALK1
      *        Start new transaction                                    PMTVALK1
               MOVE 'Y' TO W0TRN                                        PMTVALK1
      *        Process current transaction                              PMTVALK1
               PERFORM UNTIL NOT (W0TRN = 'Y')                          PMTVALK1
      *            Display screen                                       PMTVALK1
                   PERFORM CAEXFM                                       PMTVALK1
      *            Process response                                     PMTVALK1
      *            EVALUATE                                             PMTVALK1
      *                Cancel & exit program                            PMTVALK1
                       IF (C-INDICATOR-ON(03) OR                        PMTVALK1
                           C-INDICATOR-ON(12)) THEN                     PMTVALK1
                           PERFORM ZXEXPG                               PMTVALK1
      *                HOME: Reset screen fields                        PMTVALK1
                       ELSE IF (C-INDICATOR-ON(05)) THEN                PMTVALK1
                           PERFORM MALDSC                               PMTVALK1
      *                Process screen input                             PMTVALK1
                       ELSE                                             PMTVALK1
                           PERFORM DAPRSC                               PMTVALK1
                   END-IF END-IF                                        PMTVALK1
      *                                                                 PMTVALK1
               END-PERFORM                                              PMTVALK1
      *                                                                 PMTVALK1
           END-PERFORM                                                  PMTVALK1
           .                                                            PMTVALK1
      ***************************************************************   PMTVALK1
      /EJECT                                                            PMTVALK1
       CAEXFM SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Display screen and process HELP requests                     PMTVALK1
      *==============================================================   PMTVALK1
           SET C-UNTIL-FALSE TO TRUE                                    PMTVALK1
           PERFORM UNTIL (C-UNTIL-TRUE)                                 PMTVALK1
               MOVE 'N' TO W0HLP                                        PMTVALK1
      *        Enable PUTOVR                                            PMTVALK1
               SET C-INDICATOR-ON(86) TO TRUE                           PMTVALK1
      *        Set cursor by *SET CURSOR data                           CBLEXFK1
               IF (YSETCS = 'Y') THEN                                   CBLEXFK1
                   PERFORM Y0SET                                        CBLEXFK1
               END-IF                                                   CBLEXFK1
               WRITE ACI000200D-F FROM ZMSGCTL-WS-O                     CBLEXFK1
                 FORMAT IS 'ZMSGCTL' INDICATORS ARE INDICS              CBLEXFK1
               END-WRITE                                                CBLEXFK1
               WRITE ACI000200D-F FROM ZCMDTXT1-WS-O                    CBLEXFK1
                 FORMAT IS 'ZCMDTXT1' INDICATORS ARE INDICS             CBLEXFK1
               END-WRITE                                                CBLEXFK1
               WRITE ACI000200D-F FROM ZRCDDTL1-WS-O                    CBLEXFK1
                 FORMAT IS 'ZRCDDTL1' INDICATORS ARE INDICS             CBLEXFK1
               END-WRITE                                                CBLEXFK1
               READ ACI000200D                                          CBLEXFK1
                 FORMAT IS 'ZRCDDTL1' INDICATORS ARE INDICS             CBLEXFK1
               END-READ                                                 CBLEXFK1
               MOVE ACI000200D-F TO                                     CBLEXFK1
                 ZRCDDTL1-WS-I                                          CBLEXFK1
               MOVE CORRESPONDING                                       CBLEXFK1
                 ZRCDDTL1-I OF ZRCDDTL1-WS-I TO                         CBLEXFK1
                 ZRCDDTL1-O OF ZRCDDTL1-WS-O                            CBLEXFK1
      *        Test cursor                                              PMTVALK1
               PERFORM Y8TST                                            PMTVALK1
      *        Check if prompt requested                                PMTVALK1
               PERFORM ZDVPMT                                           PMTVALK1
      *        Reset help request                                       DSPHLPK1
      *        Clear set cursor DDS indicator                           DSPHLPK1
               IF (WCSRLC = 'OFF') THEN                                 DSPHLPK1
                   SET C-INDICATOR-OFF(94) TO TRUE                      DSPHLPK1
               END-IF                                                   DSPHLPK1
               MOVE SPACES TO WCSRLC                                    DSPHLPK1
      *        If help requested, display help text                     DSPHLPK1
               IF (C-INDICATOR-ON(25)) THEN                             DSPHLPK1
                   PERFORM ZHHPKY                                       DSPHLPK1
               END-IF                                                   DSPHLPK1
           IF (W0HLP = 'N')                                             PMTVALK1
             SET C-UNTIL-TRUE TO TRUE                                   PMTVALK1
           END-IF                                                       PMTVALK1
           END-PERFORM                                                  PMTVALK1
      *    Update job time                                              PMTVALK1
           ACCEPT ZZTIME FROM TIME                                      PMTVALK1
           MOVE ZZHNS TO ZZJTM                                          PMTVALK1
      *    Clear messages from program message queue                    PMTVALK1
           MOVE ZZPGM OF JOB-CONTEXT TO ZAPGMQ                          PMTVALK1
           MOVE '*SAME' TO ZAPGRL                                       PMTVALK1
           CALL 'Y2CLMSC' USING                                         PMTVALK1
             ZAPGMQ                                                     PMTVALK1
             ZAPGRL                                                     PMTVALK1
           END-CALL                                                     PMTVALK1
      *    Reset first message only flag                                PMTVALK1
           MOVE 'Y' TO ZAFSMS                                           PMTVALK1
           SET C-INDICATOR-OFF(99) TO TRUE                              PMTVALK1
           IF (YSETCS = 'Y') THEN                                       PMTVALK1
               PERFORM Y9CLR                                            PMTVALK1
           END-IF                                                       PMTVALK1
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       CAEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            PMTVALK1
       DAPRSC SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Process screen input                                         PMTVALK1
      *==============================================================   PMTVALK1
      *    Confirm/update is not deferred                               PMTVALK1
           MOVE 'N' TO W0DCF                                            PMTVALK1
      *    Validate screen input                                        PMTVALK1
           PERFORM DBVLSC                                               PMTVALK1
      *    If error, exit                                               PMTVALK1
           IF (C-INDICATOR-ON(99)) THEN                                 PMTVALK1
             GO DAEXIT                                                  PMTVALK1
           END-IF                                                       PMTVALK1
      *    Defer confirm/update requested                               PMTVALK1
           IF (W0DCF = 'Y') THEN                                        PMTVALK1
             GO DAEXIT                                                  PMTVALK1
           END-IF                                                       PMTVALK1
      *    Prompt for confirmation                                      PMTVALK1
           PERFORM DHPMCF                                               PMTVALK1
      *    Quit if not confirmed                                        PMTVALK1
           IF (C-INDICATOR-ON(99)) THEN                                 PMTVALK1
             GO DAEXIT                                                  PMTVALK1
           END-IF                                                       PMTVALK1
      *    USER: User defined action                                    MSGACTK2
      *    Setup message data for message                               CBLEXMK1
      *    U:Data Area Name                                             CBLEXMK1
           MOVE WUDTAARA OF WORK-CONTEXT TO ZA0001                      CBLEXMK1
      *    U:Library name                                               CBLEXMK1
           MOVE '*LIBL' TO ZA0002                                       CBLEXMK1
      *    GX GL code                                                   CBLEXMK1
           MOVE Z1GXGLCDE OF ZRCDDTL1-WS-O TO ZA0003                    CBLEXMK1
      *                                                                 CBLEXMK1
      *    Execute message                                              CBLEXMK1
      *    Default message file                                         CBLEXMK1
           MOVE ZADFMF TO ZAMSGF                                        CBLEXMK1
           MOVE 'JSM1659' TO ZAMSID                                     CBLEXMK1
      *                                                                 CBLEXMK1
           MOVE 'Y2EXMCC' TO YRWG00                                     CBLEXMK1
           CALL YRWG00 USING                                            CBLEXMK1
      *    Return code                                                  CBLEXMK1
             W0RTN                                                      CBLEXMK1
      *    Message ID                                                   CBLEXMK1
             ZAMSID                                                     CBLEXMK1
      *    Message file                                                 CBLEXMK1
             ZAMSGF                                                     CBLEXMK1
      *    Message data                                                 CBLEXMK1
             ZAMSDA                                                     CBLEXMK1
           MOVE SPACES TO ZAMSGF                                        CBLEXMK1
           MOVE SPACES TO ZAMSDA                                        CBLEXMK1
      *    Error on program call will terminate run unit                CBLEXMK1
           IF (W0RTN NOT = SPACES) THEN                                 CBLEXMK1
      *        Error detected during execution                          CBLEXMK1
               SET C-INDICATOR-ON(99) TO TRUE                           CBLEXMK1
               SET C-INDICATOR-ON(31) TO TRUE                           CBLEXMK1
           END-IF                                                       CBLEXMK1
      *                                                                 CBLEXMK1
      *    GX GL code                                                   CBLMOVK1
           MOVE Z1GXGLCDE OF ZRCDDTL1-WS-O TO WUGXGLCDE OF WORK-CONTEXT CBLMOVK1
      *    Request new transaction                                      PMTVALK1
           MOVE 'N' TO W0TRN                                            PMTVALK1
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       DAEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            PMTVALK1
       DBVLSC SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Validate screen input                                        PMTVALK1
      *==============================================================   PMTVALK1
      *    Check GX GL code is numeric                                  CHKNBRK1
           MOVE Z1GXGLCDE OF ZRCDDTL1-WS-O TO XGCDVL                    CHKNBRK1
           MOVE 06 TO XGCDLN                                            CHKNBRK1
           MOVE XGCDVL TO YXG-A                                         CHKNBRK1
           MOVE 1 TO XGCHNO                                             CHKNBRK1
           IF (XGCDVL NOT = SPACES AND                                  CHKNBRK1
               YXG(XGCHNO) NOT = '?') THEN                              CHKNBRK1
      *        Check to see if any characters are numeric               CHKNBRK1
               SET C-UNTIL-FALSE TO TRUE                                CHKNBRK1
               PERFORM UNTIL (C-UNTIL-TRUE)                             CHKNBRK1
      *            Obtain zone                                          CHKNBRK1
                   MOVE ZEROS TO XGBIN                                  CHKNBRK1
                   MOVE YXG(XGCHNO) TO XGBINC                           CHKNBRK1
                   DIVIDE 16 INTO XGBIN GIVING XGZONE                   CHKNBRK1
      *            Check for numeric digit                              CHKNBRK1
                   IF (XGZONE NOT = 15) THEN                            CHKNBRK1
      *                Send message '*Field must be numeric'            SNDMSGK1
      *                Message ID                                       SNDMSGK1
                       MOVE 'Y2U0010' TO ZAMSID                         SNDMSGK1
      *                Message file                                     SNDMSGK1
                       MOVE 'Y2USRMSG' TO ZAMSGF                        SNDMSGK1
                       PERFORM ZASNMS                                   SNDMSGK1
                       SET C-INDICATOR-ON(99) TO TRUE                   CHKNBRK1
                       SET C-INDICATOR-ON(31) TO TRUE                   CHKNBRK1
                       ADD XGCDLN,1 GIVING XGCHNO                       CHKNBRK1
                   ELSE                                                 CHKNBRK1
                       ADD 1 TO XGCHNO                                  CHKNBRK1
                   END-IF                                               CHKNBRK1
               IF (XGCHNO > XGCDLN)                                     CHKNBRK1
                 SET C-UNTIL-TRUE TO TRUE                               CHKNBRK1
               END-IF                                                   CHKNBRK1
               END-PERFORM                                              CHKNBRK1
           END-IF                                                       CHKNBRK1
      *    Bypass ref file checks if error already detected             PMTVALK1
           IF (C-INDICATOR-ON(99)) THEN                                 PMTVALK1
             GO DBEXIT                                                  PMTVALK1
           END-IF                                                       PMTVALK1
           IF (YPMTFD = SPACES) THEN                                    PMTVALK1
      *        USER: Validate relations                                 MSGACTK2
      *        CASE: DTL.GX GL code EQ WRK.GX GL code                   MSGACTK2
      *        *IF                                                      CBLIFXK1
               IF (Z1GXGLCDE OF ZRCDDTL1-WS-O = WUGXGLCDE OF            CBLIFXK1
                 WORK-CONTEXT) THEN                                     CBLIFXK1
      *            *Return code                                         CBLEXTK1
                   MOVE SPACES TO P0RTN                                 CBLEXTK1
                   PERFORM ZYEXPG                                       CBLEXTK1
               END-IF                                                   MSGACTK2
           END-IF                                                       PMTVALK1
      *    GX GL code required                                          PMTVALK1
           IF (Z1GXGLCDE OF ZRCDDTL1-WS-O = SPACES AND                  PMTVALK1
               YPMTFD = SPACES) THEN                                    PMTVALK1
               SET C-INDICATOR-ON(99) TO TRUE                           PMTVALK1
               SET C-INDICATOR-ON(31) TO TRUE                           PMTVALK1
      *        Send message '*Value required'                           SNDMSGK1
      *        Message ID                                               SNDMSGK1
               MOVE 'Y2U0001' TO ZAMSID                                 SNDMSGK1
      *        Message file                                             SNDMSGK1
               MOVE 'Y2USRMSG' TO ZAMSGF                                SNDMSGK1
               PERFORM ZASNMS                                           SNDMSGK1
           END-IF                                                       PMTVALK1
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       DBEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            PMTVALK1
       DHPMCF SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Prompt for confirmation                                      PMTVALK1
      *==============================================================   PMTVALK1
      *    Enable PUTOVR                                                PMTVALK1
           SET C-INDICATOR-ON(86) TO TRUE                               PMTVALK1
      *    Refresh screen                                               PMTVALK1
           MOVE 'N' TO ZZCFCD OF ACI000200D-WS-O                        CNFPMTK2
      *    Save CMD keys                                                CNFPMTK2
           MOVE INDICS TO WN30-A                                        CNFPMTK2
      *    Convert *CONFIRM to external value                           CVTSTSK1
      *    List number                                                  CVTSTSK1
           MOVE 1001713 TO Y2LSNO OF KINEX                              CVTSTSK1
      *    Internal value                                               CVTSTSK1
           MOVE SPACES TO Y2INVL OF KINEX                               CVTSTSK1
      *    *CONFIRM                                                     CVTSTSK1
           MOVE ZZCFCD OF ACI000200D-WS-O TO Y2INVL OF KINEX            CVTSTSK1
           MOVE CORRESPONDING                                           CVTSTSK1
             KINEX TO                                                   CVTSTSK1
             YY2INEX OF JSVLLSL9-R                                      CVTSTSK1
           MOVE 'Y' TO Y2VLMP OF YY2INEX                                CVTSTSK1
           READ JSVLLSL9                                                CVTSTSK1
             FORMAT IS 'YY2INEX'                                        CVTSTSK1
           END-READ                                                     CVTSTSK1
           IF (C-NO-RECORD) THEN                                        CVTSTSK1
               SET C-INDICATOR-ON(90) TO TRUE                           CVTSTSK1
           ELSE                                                         CVTSTSK1
               SET C-INDICATOR-OFF(90) TO TRUE                          CVTSTSK1
           END-IF                                                       CVTSTSK1
      *                                                                 CVTSTSK1
           IF (C-INDICATOR-OFF(90)) THEN                                CVTSTSK1
      *        *CONFIRM                                                 CVTSTSK1
               MOVE Y2EXVL OF YY2INEX OF JSVLLSL9 TO VZCFCD OF          CVTSTSK1
                 ACI000200D-WS-O                                        CVTSTSK1
           END-IF                                                       CVTSTSK1
      *                                                                 CVTSTSK1
           SET C-UNTIL-FALSE TO TRUE                                    CNFPMTK2
           PERFORM UNTIL (C-UNTIL-TRUE)                                 CNFPMTK2
               SET C-INDICATOR-OFF(29) TO TRUE                          CNFPMTK2
               WRITE ACI000200D-F FROM ZMSGCTL-WS-O                     CBLEXFK1
                 FORMAT IS 'ZMSGCTL' INDICATORS ARE INDICS              CBLEXFK1
               END-WRITE                                                CBLEXFK1
               WRITE ACI000200D-F FROM ZCMDTXT1-WS-O                    CBLEXFK1
                 FORMAT IS 'ZCMDTXT1' INDICATORS ARE INDICS             CBLEXFK1
               END-WRITE                                                CBLEXFK1
               WRITE ACI000200D-F FROM ZRCDDTL1-WS-O                    CBLEXFK1
                 FORMAT IS 'ZRCDDTL1' INDICATORS ARE INDICS             CBLEXFK1
               END-WRITE                                                CBLEXFK1
               WRITE ACI000200D-F FROM ZCONFIRM-WS-O                    CBLEXFK1
                 FORMAT IS 'ZCONFIRM' INDICATORS ARE INDICS             CBLEXFK1
               END-WRITE                                                CBLEXFK1
               READ ACI000200D                                          CBLEXFK1
                 FORMAT IS 'ZCONFIRM' INDICATORS ARE INDICS             CBLEXFK1
               END-READ                                                 CBLEXFK1
               MOVE ACI000200D-F TO                                     CBLEXFK1
                 ZCONFIRM-WS-I                                          CBLEXFK1
               MOVE CORRESPONDING                                       CBLEXFK1
                 ZCONFIRM-I OF ZCONFIRM-WS-I TO                         CBLEXFK1
                 ZCONFIRM-O OF ZCONFIRM-WS-O                            CBLEXFK1
      *        Reset help request                                       DSPHLPK1
      *        Clear set cursor DDS indicator                           DSPHLPK1
               IF (WCSRLC = 'OFF') THEN                                 DSPHLPK1
                   SET C-INDICATOR-OFF(94) TO TRUE                      DSPHLPK1
               END-IF                                                   DSPHLPK1
               MOVE SPACES TO WCSRLC                                    DSPHLPK1
      *        If help requested, display help text                     DSPHLPK1
               IF (C-INDICATOR-ON(25)) THEN                             DSPHLPK1
                   PERFORM ZHHPKY                                       DSPHLPK1
               END-IF                                                   DSPHLPK1
      *        Validate *CONFIRM                                        CHKSTSK1
               MOVE SPACES TO W0RTN                                     CHKSTSK1
      *        Name search required?                                    CHKSTSK1
      *        *CONFIRM                                                 CHKSTSK1
               MOVE VZCFCD OF ACI000200D-WS-O TO W0NSRQ                 CHKSTSK1
      *        Search required                                          CHKSTSK1
               IF (W0NSRQ = '?' OR                                      CHKSTSK1
                   'VZCFCD OF ' = YPMTFD) THEN                          CHKSTSK1
                   MOVE VZCFCD OF ACI000200D-WS-O TO W0EXVL             CHKSTSK1
                   MOVE 1001713 TO Y2LSNO OF KEXIN                      CHKSTSK1
                   SET C-INDICATOR-OFF(90) TO TRUE                      CHKSTSK1
                   CALL 'JSVLLSR' USING                                 CHKSTSK1
      *            Return code                                          CHKSTSK1
                     W0RTN                                              CHKSTSK1
      *            List number                                          CHKSTSK1
                     Y2LSNO OF KEXIN                                    CHKSTSK1
      *            *CONFIRM                                             CHKSTSK1
                     W0EXVL                                             CHKSTSK1
                        ON OVERFLOW                                     CHKSTSK1
                           SET C-INDICATOR-ON(90) TO TRUE               CHKSTSK1
                   END-CALL                                             CHKSTSK1
      *                                                                 CHKSTSK1
                   IF (C-INDICATOR-ON(90)) THEN                         CHKSTSK1
                       MOVE 'Y2U0021' TO W0RTN                          CHKSTSK1
                   END-IF                                               CHKSTSK1
      *            Error on program call will terminate run unit        CHKSTSK1
                   MOVE W0EXVL TO VZCFCD OF ACI000200D-WS-O             CHKSTSK1
      *            Defer confirm                                        CHKSTSK1
                   MOVE 'Y' TO W0DCF                                    CHKSTSK1
                   IF (W0NSRQ NOT = '?') THEN                           CHKSTSK1
                       MOVE '*DONE' TO YPMTFD                           CHKSTSK1
                   END-IF                                               CHKSTSK1
               END-IF                                                   CHKSTSK1
      *        Check external value of *CONFIRM                         CHKSTSK1
      *        Convert *CONFIRM to internal value                       CHKSTSK1
      *        List number                                              CHKSTSK1
               MOVE 1001713 TO Y2LSNO OF KEXIN                          CHKSTSK1
      *        External value                                           CHKSTSK1
               MOVE SPACES TO Y2EXVL OF KEXIN                           CHKSTSK1
      *        *CONFIRM                                                 CHKSTSK1
               MOVE VZCFCD OF ACI000200D-WS-O TO Y2EXVL OF KEXIN        CHKSTSK1
               MOVE CORRESPONDING                                       CHKSTSK1
                 KEXIN TO                                               CHKSTSK1
                 YY2EXIN OF JSVLLSL9-R                                  CHKSTSK1
               READ JSVLLSL9                                            CHKSTSK1
                 FORMAT IS 'YY2EXIN'                                    CHKSTSK1
               END-READ                                                 CHKSTSK1
               MOVE CORRESPONDING                                       CHKSTSK1
                 YY2EXIN OF JSVLLSL9-R TO                               CHKSTSK1
                 KINEX                                                  CHKSTSK1
               IF (C-NO-RECORD) THEN                                    CHKSTSK1
                   SET C-INDICATOR-ON(90) TO TRUE                       CHKSTSK1
               ELSE                                                     CHKSTSK1
                   SET C-INDICATOR-OFF(90) TO TRUE                      CHKSTSK1
               END-IF                                                   CHKSTSK1
      *                                                                 CHKSTSK1
      *                                                                 CHKSTSK1
               IF (C-INDICATOR-ON(90)) THEN                             CHKSTSK1
      *            Not found                                            CHKSTSK1
                   MOVE SPACES TO ZZCFCD OF ACI000200D-WS-O             CHKSTSK1
                   IF (YPMTFD = SPACES) THEN                            CHKSTSK1
                       SET C-INDICATOR-ON(96) TO TRUE                   CHKSTSK1
                       WRITE ACI000200D-F FROM ZCONFIRM-WS-O            CHKSTSK1
                         FORMAT IS 'ZCONFIRM' INDICATORS ARE INDICS     CHKSTSK1
                       END-WRITE                                        CHKSTSK1
                       SET C-INDICATOR-OFF(96) TO TRUE                  CHKSTSK1
                   END-IF                                               CHKSTSK1
               ELSE                                                     CHKSTSK1
      *            *CONFIRM                                             CHKSTSK1
                   MOVE Y2INVL OF KINEX TO ZZCFCD OF ACI000200D-WS-O    CHKSTSK1
               END-IF                                                   CHKSTSK1
      *                                                                 CHKSTSK1
           IF (W0HLP = 'N' AND                                          CNFPMTK2
               C-INDICATOR-OFF(90) AND                                  CNFPMTK2
               C-INDICATOR-OFF(29))                                     CNFPMTK2
             SET C-UNTIL-TRUE TO TRUE                                   CNFPMTK2
           END-IF                                                       CNFPMTK2
           END-PERFORM                                                  CNFPMTK2
      *    Restore CMD keys                                             CNFPMTK2
           MOVE 1 TO IND-COUNT                                          CNFPMTK2
           SET C-UNTIL-FALSE TO TRUE                                    CNFPMTK2
           PERFORM UNTIL (C-UNTIL-TRUE)                                 CNFPMTK2
               MOVE WN30(IND-COUNT) TO IND(IND-COUNT)                   CNFPMTK2
               ADD 1 TO IND-COUNT                                       CNFPMTK2
           IF (IND-COUNT > 30)                                          CNFPMTK2
             SET C-UNTIL-TRUE TO TRUE                                   CNFPMTK2
           END-IF                                                       CNFPMTK2
           END-PERFORM                                                  CNFPMTK2
      *    Update job time                                              CNFPMTK2
           ACCEPT ZZTIME FROM TIME                                      CNFPMTK2
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT                           CNFPMTK2
           IF (ZZCFCD OF ACI000200D-WS-O NOT = 'Y') THEN                CNFPMTK2
                 SET C-INDICATOR-ON(99) TO TRUE                         CNFPMTK2
           ELSE                                                         CNFPMTK2
      *        Clear messages from program message queue                CNFPMTK2
               MOVE ZZPGM OF JOB-CONTEXT TO ZAPGMQ                      CNFPMTK2
               MOVE '*SAME' TO ZAPGRL                                   CNFPMTK2
               CALL 'Y2CLMSC' USING                                     CNFPMTK2
                 ZAPGMQ                                                 CNFPMTK2
                 ZAPGRL                                                 CNFPMTK2
               END-CALL                                                 CNFPMTK2
      *        Reset first message only flag                            CNFPMTK2
               MOVE 'Y' TO ZAFSMS                                       CNFPMTK2
                 SET C-INDICATOR-OFF(99) TO TRUE                        CNFPMTK2
           END-IF                                                       CNFPMTK2
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       DHEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            PMTVALK1
       MALDSC SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Load screen from passed parameters                           PMTVALK1
      *==============================================================   PMTVALK1
           MOVE SPACES TO Z1GXGLCDE OF ZRCDDTL1-WS-O                    PMTVALK1
      *    USER: Load screen                                            MSGACTK2
      *    Rtv *DTAARA value <= 256 - #Standard Functions  *            MSGACTK2
           SET C-INDICATOR-OFF(90) TO TRUE                              CBLCLLK1
           MOVE WUDTAARA OF WORK-CONTEXT TO WQ0001                      CBLCLLK1
           MOVE SPACES TO WQ0002                                        CBLCLLK1
      *                                                                 CBLCLLK1
           CALL 'Y2RTDAC' USING                                         CBLCLLK1
      *    U:Object Name                                                CBLCLLK1
             WQ0001                                                     CBLCLLK1
      *    U:Data area value (256)                                      CBLCLLK1
             WQ0002                                                     CBLCLLK1
                    ON OVERFLOW                                         CBLCLLK1
                    SET C-INDICATOR-ON(90) TO TRUE                      CBLCLLK1
           END-CALL                                                     CBLCLLK1
      *                                                                 CBLCLLK1
           MOVE WQ0002 TO WUGXGLCDE OF WORK-CONTEXT                     CBLCLLK1
      *                                                                 CBLCLLK1
      *    Error on program call will terminate run unit                CBLCLLK1
           IF (C-INDICATOR-ON(90)) THEN                                 CBLCLLK1
               MOVE 'Y2U0032' TO W0RTN                                  CBLCLLK1
               MOVE 'Y2RTDAC' TO W0CLPG                                 CBLCLLK1
      *        Send message '*Error occured on CALL...'                 SNDMSGK1
      *        Message ID                                               SNDMSGK1
               MOVE 'Y2U0032' TO ZAMSID                                 SNDMSGK1
      *        Message file                                             SNDMSGK1
               MOVE 'Y2USRMSG' TO ZAMSGF                                SNDMSGK1
      *        Message data                                             SNDMSGK1
               MOVE W0CLPG TO ZAMSDA                                    SNDMSGK1
               PERFORM ZASNMS                                           SNDMSGK1
               SET C-INDICATOR-ON(99) TO TRUE                           CBLCLLK1
           END-IF                                                       CBLCLLK1
      *    GX GL code                                                   CBLMOVK1
           MOVE WUGXGLCDE OF WORK-CONTEXT TO Z1GXGLCDE OF ZRCDDTL1-WS-O CBLMOVK1
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       MAEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            CBLSETK2
       Y0SET  SECTION.                                                  CBLSETK2
      *==============================================================   CBLSETK2
      *    Set cursor by *SET CURSOR data                               CBLSETK2
      *==============================================================   CBLSETK2
      *==============================================================   CBLSETK2
           CONTINUE.                                                    CBLSETK2
       Y0EXIT.                                                          CBLSETK2
           EXIT.                                                        CBLSETK2
      /EJECT                                                            CBLCSRK1
       Y8TST  SECTION.                                                  CBLCSRK1
      *==============================================================   CBLCSRK1
      *    Test cursor                                                  CBLCSRK1
      *==============================================================   CBLCSRK1
           ACCEPT ACI000200D-I-O-DSPF FROM I-O-FEEDBACK-AREA            CBLCSRK1
            FOR ACI000200D                                              CBLCSRK1
           MOVE ZZRWCL OF ACI000200D-I-O-DSPF TO ZINPOS                 CBLCSRK1
           MOVE SPACES TO W0CFL                                         CBLCSRK1
           DIVIDE ZINPOS BY 256 GIVING W0CRW REMAINDER W0CCL            CBLCSRK1
      *==============================================================   CBLCSRK1
           CONTINUE.                                                    CBLCSRK1
       Y8EXIT.                                                          CBLCSRK1
           EXIT.                                                        CBLCSRK1
      /EJECT                                                            CBLSETK2
       Y9CLR  SECTION.                                                  CBLSETK2
      *==============================================================   CBLSETK2
      *    Clear *SET CURSOR data                                       CBLSETK2
      *==============================================================   CBLSETK2
      *==============================================================   CBLSETK2
           CONTINUE.                                                    CBLSETK2
       Y9EXIT.                                                          CBLSETK2
           EXIT.                                                        CBLSETK2
      /EJECT                                                            CBLUPDK1
       ZASNMS SECTION.                                                  CBLUPDK1
      *==============================================================   CBLUPDK1
      *    Send message to program's message queue                      CBLUPDK1
      *==============================================================   CBLUPDK1
      *    Send if first error message or not an error message          CBLUPDK1
           IF (ZAMSTP NOT = SPACES OR                                   CBLUPDK1
               ZAFSMS NOT = 'N') THEN                                   CBLUPDK1
               IF (ZAMSTP = SPACES) THEN                                CBLUPDK1
      *            Signal first error message sent                      CBLUPDK1
                   MOVE 'N' TO ZAFSMS                                   CBLUPDK1
               END-IF                                                   CBLUPDK1
               IF (ZAPGMQ = SPACES) THEN                                CBLUPDK1
                   MOVE ZZPGM OF JOB-CONTEXT TO ZAPGMQ                  CBLUPDK1
               END-IF                                                   CBLUPDK1
      *        If no message file specified, use default                CBLUPDK1
               IF (ZAMSGF = SPACES) THEN                                CBLUPDK1
                   MOVE ZADFMF TO ZAMSGF                                CBLUPDK1
               END-IF                                                   CBLUPDK1
               CALL 'Y2SNMGC' USING                                     CBLUPDK1
      *        Program queue                                            CBLUPDK1
                 ZAPGMQ                                                 CBLUPDK1
      *        Relative queue                                           CBLUPDK1
                 ZAPGRL                                                 CBLUPDK1
      *        Message ID                                               CBLUPDK1
                 ZAMSID                                                 CBLUPDK1
      *        Message file                                             CBLUPDK1
                 ZAMSGF                                                 CBLUPDK1
      *        Message data                                             CBLUPDK1
                 ZAMSDA                                                 CBLUPDK1
      *        Message type                                             CBLUPDK1
                 ZAMSTP                                                 CBLUPDK1
               END-CALL                                                 CBLUPDK1
           END-IF                                                       CBLUPDK1
      *    Clear all fields for default mechanism next time             CBLUPDK1
      *    Program queue                                                CBLUPDK1
           MOVE SPACES TO ZAPGMQ                                        CBLUPDK1
      *    Relative queue                                               CBLUPDK1
           MOVE SPACES TO ZAPGRL                                        CBLUPDK1
      *    Message ID                                                   CBLUPDK1
           MOVE SPACES TO ZAMSID                                        CBLUPDK1
      *    Message file                                                 CBLUPDK1
           MOVE SPACES TO ZAMSGF                                        CBLUPDK1
      *    Message data                                                 CBLUPDK1
           MOVE SPACES TO ZAMSDA                                        CBLUPDK1
      *    Message type                                                 CBLUPDK1
           MOVE SPACES TO ZAMSTP                                        CBLUPDK1
      *==============================================================   CBLUPDK1
           CONTINUE.                                                    CBLUPDK1
       ZAEXIT.                                                          CBLUPDK1
           EXIT.                                                        CBLUPDK1
      /EJECT                                                            GENF4K10
       ZDVPMT SECTION.                                                  GENF4K10
      *==============================================================   GENF4K10
      *    Process prompt request                                       GENF4K10
      *==============================================================   GENF4K10
      *                                                                 GENF4K10
      *    Initialise prompt workfields                                 GENF4K10
           MOVE SPACES TO YPMTFD                                        GENF4K10
           MOVE ZERO TO YAFSCH                                          GENF4K10
           MOVE ZERO TO YPMRRN                                          GENF4K10
      *                                                                 GENF4K10
           IF (C-INDICATOR-ON(04)) THEN                                 GENF4K10
               SET C-INDICATOR-ON(04) TO TRUE                           GENF4K10
      *                                                                 GENF4K10
      *        Extract cursor row and column                            GENF4K10
               ACCEPT ACI000200D-I-O-DSPF                               GENF4K10
               FROM I-O-FEEDBACK-AREA FOR ACI000200D                    GENF4K10
               DIVIDE ZZRWCL BY 256 GIVING ZHCSRW REMAINDER ZHCSCL      GENF4K10
      *        Save cursor position for redisplay                       GENF4K10
      *        Row                                                      GENF4K10
               MOVE ZEROS TO ZZZCSRW                                    GENF4K10
               MOVE ZHCSRW TO ZZZCSRW                                   GENF4K10
      *        Column                                                   GENF4K10
               MOVE ZEROS TO ZZZCSCL                                    GENF4K10
               MOVE ZHCSCL TO ZZZCSCL                                   GENF4K10
      *                                                                 GENF4K10
               IF (YPMTFD = SPACES) THEN                                GENF4K10
      *            Error if user defined prompting is not specified.    GENF4K10
                   IF (W0PMT = 'N') THEN                                GENF4K10
                       MOVE '*NONE' TO YPMTFD                           GENF4K10
                       MOVE 'Y' TO W0HLP                                GENF4K10
                       MOVE 'Y' TO ZAFSMS                               GENF4K10
      *                Send error message.                              SNDMSGK1
      *                Message ID                                       SNDMSGK1
                       MOVE 'Y2U0101' TO ZAMSID                         SNDMSGK1
      *                Message file                                     SNDMSGK1
                       MOVE 'Y2USRMSG' TO ZAMSGF                        SNDMSGK1
                       PERFORM ZASNMS                                   SNDMSGK1
                   END-IF                                               GENF4K10
               END-IF                                                   GENF4K10
      *                                                                 GENF4K10
           END-IF                                                       GENF4K10
      *==============================================================   GENF4K10
           CONTINUE.                                                    GENF4K10
       ZDEXIT.                                                          GENF4K10
           EXIT.                                                        GENF4K10
      /EJECT                                                            DSPHLPK1
       ZHHPKY SECTION.                                                  DSPHLPK1
      *==============================================================   DSPHLPK1
      *    Display HELP text                                            DSPHLPK1
      *==============================================================   DSPHLPK1
      *    Signal help request                                          DSPHLPK1
           MOVE 'Y' TO W0HLP                                            DSPHLPK1
      *                                                                 DSPHLPK1
      *    Extract cursor row and column                                DSPHLPK1
           ACCEPT ACI000200D-I-O-DSPF FROM I-O-FEEDBACK-AREA FOR        DSPHLPK1
             ACI000200D                                                 DSPHLPK1
           DIVIDE ZZRWCL BY 256 GIVING ZHCSRW REMAINDER ZHCSCL          DSPHLPK1
      *                                                                 DSPHLPK1
      *    Save cursor position for redisplay                           DSPHLPK1
      *    Row                                                          DSPHLPK1
           MOVE ZEROS TO ZZZCSRW                                        DSPHLPK1
           ADD ZHCSRW TO ZZZCSRW                                        DSPHLPK1
      *    Column                                                       DSPHLPK1
           MOVE ZEROS TO ZZZCSCL                                        DSPHLPK1
           ADD ZHCSCL TO ZZZCSCL                                        DSPHLPK1
      *                                                                 DSPHLPK1
           MOVE 'ACI000200H' TO W0HPMB                                  DSPHLPK1
           MOVE SPACES TO YYHPFL                                        DSPHLPK1
           MOVE SPACES TO YYHPLB                                        DSPHLPK1
           MOVE '*START' TO YYHLVN                                      DSPHLPK1
           MOVE '*NORMAL' TO YYUSOP                                     DSPHLPK1
           MOVE ZHCSRW TO YYRW                                          DSPHLPK1
           MOVE ZHCSCL TO YYCL                                          DSPHLPK1
           MOVE ZEROS  TO YYLGCT                                        DSPHLPK1
           MOVE SPACES TO YYLGVN                                        DSPHLPK1
           CALL 'YDDSHPR' USING                                         DSPHLPK1
      *    Member name                                                  DSPHLPK1
             W0HPMB                                                     DSPHLPK1
      *    *DFT text file                                               DSPHLPK1
             YYHPFL                                                     DSPHLPK1
      *    Help text library                                            DSPHLPK1
             YYHPLB                                                     DSPHLPK1
      *    Return code                                                  DSPHLPK1
             W0RTN                                                      DSPHLPK1
      *    Help label                                                   DSPHLPK1
             YYHLVN                                                     DSPHLPK1
      *    Options                                                      DSPHLPK1
             YYUSOP                                                     DSPHLPK1
      *    Row                                                          DSPHLPK1
             YYRW                                                       DSPHLPK1
      *    Column                                                       DSPHLPK1
             YYCL                                                       DSPHLPK1
      *    # of grps                                                    DSPHLPK1
             YYLGCT                                                     DSPHLPK1
      *    Label grps                                                   DSPHLPK1
             YYLGVN                                                     DSPHLPK1
           END-CALL                                                     DSPHLPK1
      *                                                                 DSPHLPK1
      *    Clear set cursor DDS indicator                               DSPHLPK1
           IF (C-INDICATOR-OFF(94)) THEN                                DSPHLPK1
               MOVE 'OFF' TO WCSRLC                                     DSPHLPK1
               SET C-INDICATOR-ON(94) TO TRUE                           DSPHLPK1
           END-IF                                                       DSPHLPK1
      *==============================================================   DSPHLPK1
           CONTINUE.                                                    DSPHLPK1
       ZHEXIT.                                                          DSPHLPK1
           EXIT.                                                        DSPHLPK1
      /EJECT                                                            PMTVALK1
       ZXEXPG SECTION.                                                  PMTVALK1
      *==============================================================   PMTVALK1
      *    Cancel & exit program                                        PMTVALK1
      *==============================================================   PMTVALK1
      *    USER: Exit program processing                                MSGACTK2
      *    CASE: DTL.*CMD key is *Fast Exit                             MSGACTK2
      *    *IF                                                          CBLIFXK1
           IF (C-INDICATOR-ON(03)) THEN                                 CBLIFXK1
      *        *Return code                                             CBLEXTK1
               MOVE 'Y2U9999' TO P0RTN                                  CBLEXTK1
               PERFORM ZYEXPG                                           CBLEXTK1
           END-IF                                                       MSGACTK2
           MOVE SPACES TO P0RTN                                         PMTVALK1
           PERFORM ZYEXPG                                               PMTVALK1
      *==============================================================   PMTVALK1
           CONTINUE.                                                    PMTVALK1
       ZXEXIT.                                                          PMTVALK1
           EXIT.                                                        PMTVALK1
      /EJECT                                                            CBLUPDK1
       ZYEXPG SECTION.                                                  CBLUPDK1
      *==============================================================   CBLUPDK1
      *    Exit program: Direct                                         CBLUPDK1
      *==============================================================   CBLUPDK1
           CLOSE ACI000200D                                             CBLUPDK1
      *    Reset entry parameters as appropriate                        CBLUPDK1
           PERFORM ZZEXPM.                                              CBLUPDK1
      *    Exit program                                                 CBLUPDK1
           CONTINUE.                                                    CBLUPDK1
       ZYEXPG-EXIT.                                                     CBLUPDK1
           GOBACK.                                                      CBLUPDK1
      *==============================================================   CBLUPDK1
           CONTINUE.                                                    CBLUPDK1
       ZYEXIT.                                                          CBLUPDK1
           EXIT.                                                        CBLUPDK1
      /EJECT                                                            DCLPARK1
       ZZEXPM SECTION.                                                  DCLPARK1
      *==============================================================   DCLPARK1
      *    Return parameters from work fields                           DCLPARK1
      *==============================================================   DCLPARK1
      *==============================================================   DCLPARK1
           CONTINUE.                                                    DCLPARK1
       ZZPEXT.                                                          DCLPARK1
           EXIT.                                                        DCLPARK1
      /EJECT                                                            CBLHDRK1
       ZZINIT SECTION.                                                  CBLHDRK1
      *==============================================================   CBLHDRK1
      *    Initialisation                                               CBLHDRK1
      *==============================================================   CBLHDRK1
           IF (W0ICL = SPACES) THEN                                     CBLHDRK1
      *        *Initial call                                            CBLHDRK1
               MOVE 'Y' TO W0ICL                                        CBLHDRK1
           ELSE                                                         CBLHDRK1
               MOVE 'N' TO W0ICL                                        CBLHDRK1
           END-IF                                                       CBLHDRK1
           MOVE SPACES TO P0RTN                                         CBLHDRK1
           MOVE SPACES TO W0RTN                                         CBLHDRK1
           MOVE ZEROS  TO W0RTW                                         CBLHDRK1
           MOVE SPACES TO W0RSF                                         CBLHDRK1
           MOVE '400' TO W0ENV                                          CBLHDRK1
           MOVE ALL B'0' TO INDICS                                      CBLHDRK1
           MOVE SPACES TO ZZPGM OF JOB-CONTEXT                          CBLHDRK1
      *    Retrieve job attributes                                      CBLHDRK1
           CALL 'Y2RTJCR' USING                                         CBLHDRK1
             JOB-CONTEXT                                                CBLHDRK1
           END-CALL                                                     CBLHDRK1
      *    Setup job date/time                                          CBLHDRK1
           MOVE ZZSD7 OF JOB-CONTEXT TO ZZJDT                           CBLHDRK1
           ACCEPT ZZTIME FROM TIME                                      CBLHDRK1
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT                           CBLHDRK1
           MOVE 'ACI000200S' TO ZZPGM OF JOB-CONTEXT                    CBLHDRK1
           MOVE ZEROS TO ZZCSRW OF ZRCDDTL1-WS-O                        CBLEXFK1
           MOVE ZEROS TO ZZCSCL OF ZRCDDTL1-WS-O                        CBLEXFK1
      *    Define work field U:Data Area Name                           ACTCTXK4
           MOVE SPACES TO WUDTAARA OF WORK-CONTEXT                      ACTCTXK4
      *    Obtain default message file                                  CBLEXMK1
           MOVE 'JSMGFLA' TO DATA-AREA-NAME                             CBLEXMK1
           MOVE 'Y2RTDAC' TO YRWG00                                     CBLEXMK1
           CALL YRWG00 USING                                            CBLEXMK1
             DATA-AREA-NAME                                             CBLEXMK1
             ZADFMF                                                     CBLEXMK1
           END-CALL                                                     CBLEXMK1
      *    Define work field GX GL code                                 ACTCTXK4
           MOVE SPACES TO WUGXGLCDE OF WORK-CONTEXT                     ACTCTXK4
           OPEN INPUT JSVLLSL9                                          CVTSTSK1
      *                                                                 CBLSETK2
      *    Initialize array variables                                   CBLSETK2
      *    Flag no *SET CURSOR in the program                           CBLSETK2
           MOVE 'N' TO YSETCS                                           CBLSETK2
           MOVE SPACES TO WCSRLC                                        CBLSETK2
      *                                                                 CBLSETK2
      *    Obtain default message file                                  CBLUPDK1
           MOVE 'JSMGFLA' TO DATA-AREA-NAME                             CBLUPDK1
           CALL 'Y2RTDAC' USING                                         CBLUPDK1
             DATA-AREA-NAME                                             CBLUPDK1
             ZADFMF                                                     CBLUPDK1
           END-CALL                                                     CBLUPDK1
      *    Signal first error message outstanding                       CBLUPDK1
           MOVE 'Y' TO ZAFSMS                                           CBLUPDK1
      *    Open files                                                   CBLUPDK1
           OPEN I-O ACI000200D                                          CBLUPDK1
           MOVE 'Y' TO W0OPN                                            CBLUPDK1
           MOVE 'N' TO W0PMT                                            CBLUPDK1
           MOVE 'ACI000200S' TO ZZPGM OF ZRCDDTL1-WS-O                  PMTVALK1
           MOVE ZZUSR OF JOB-CONTEXT TO ZZUSR OF ACI000200D-WS-O        PMTVALK1
           MOVE ZZJOB OF JOB-CONTEXT TO ZZJOB OF ACI000200D-WS-O        PMTVALK1
           MOVE ZZPGM OF JOB-CONTEXT TO ZZPGM OF ZMSGCTL-WS-O           PMTVALK1
      *    USER: Initialize program                                     MSGACTK2
      *    Utl @Copyright - #Standard Functions  *                      MSGACTK2
      *    Program details                                              MSGACTK2
      *    CASE: *OTHERWISE                                             MSGACTK2
      *    -------------------------------------------------------------MSGACTK2
      *    System  . . . . . :   Finance Interfaces - Global Expenses   MSGACTK2
      *    Programmer  . . . :   Maurice Mead                           MSGACTK2
      *    Request/Project . :   RN-CHG-145887                          MSGACTK2
      *    Date written  . . :   16/05/2007                             MSGACTK2
      *    The input interface normally contains two lines with invalid MSGACTK2
      *    account numbers, this screen allows the user to specify      MSGACTK2
      *    the valid account number that is to replace them.            MSGACTK2
      *    -------------------------------------------------------------MSGACTK2
      *    Maintenance:-                                                MSGACTK2
      *    dd/mm/yyyy  request/project       programmer                 MSGACTK2
      *    change description                                           MSGACTK2
      *    -------------------------------------------------------------MSGACTK2
      *    Utl set screen sysid (Pmt - #Standard Functions  *           MSGACTK2
      *.Start.of.User.source........................................... CBLUFNK1
           MOVE 'SYSNAME'              TO RUK-DTAARA-NAME               CBLUFNK1
           CALL 'Y2RTDAC'                                               CBLUFNK1
             USING RUK-DTAARA-NAME                                      CBLUFNK1
                   ZZSNAM  OF ZRCDDTL1-WS-O                             CBLUFNK1
           END-CALL                                                     CBLUFNK1
      *.End.of.user.source............................................. CBLUFNK1
      *    U:Data Area Name                                             CBLMOVK1
           MOVE 'ACI000110A' TO WUDTAARA OF WORK-CONTEXT                CBLMOVK1
      *    Load screen                                                  PMTVALK1
           PERFORM MALDSC                                               PMTVALK1
      *==============================================================   CBLHDRK1
           CONTINUE.                                                    CBLHDRK1
       ZZEXIT.                                                          CBLHDRK1
           EXIT.                                                        CBLHDRK1
