       PROCESS APOST GRAPHIC.
      ***************************************************************
       IDENTIFICATION DIVISION.
     H/TITLE EXT crt Export veh ric    Execute external functio
     Z* CRTBNDCBL
     Z* CVTOPT(*DATETIME) DBGVIEW(*SOURCE) OPTIMIZE(*BASIC)
     Z* BNDDIR(YBNDDIR) ACTGRP(*CALLER)
      *
     H* SYNOPSIS :
     H*  Perform user function
     H*  As defined by action diagram
     H* Generated by CA 2E release 8.7 (1632)
     H* Function type : Execute external function  Version:  8.7
     H* Object type   : *PGM
      *
     H* Company    : Vehicle Finance
     H* System     : Vehicle Finance
     H* User name  : PRAGTSK
     H* Date       : 20/09/19 time: 14:19:46
     H* Copyright  : Vehicle Finance
      *
      *==============================================================
     M* MAINTENANCE   :
      *==============================================================
       PROGRAM-ID.  RIC000120S.
      /EJECT
      ***************************************************************
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.  IBM-AS400.
       OBJECT-COMPUTER.  IBM-AS400.
       SPECIAL-NAMES.  OPEN-FEEDBACK IS OPEN-FEEDBACK-AREA,
           I-O-FEEDBACK IS I-O-FEEDBACK-AREA.
      /EJECT
      ***************************************************************
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      *
           SELECT VAVEHDTALG
             ASSIGN TO DATABASE-VAVEHDTALG
             ORGANIZATION IS INDEXED
             ACCESS MODE IS DYNAMIC
             RECORD KEY IS EXTERNALLY-DESCRIBED-KEY
             FILE STATUS IS FILE-STATUS.
      *    RSQ : Vehicle                   Not Purget
      *
       I-O-CONTROL.
      *
      /EJECT
      ***************************************************************
       DATA DIVISION.
       FILE SECTION.
      *
      *
       FD  VAVEHDTALG
           LABEL RECORDS ARE STANDARD.
       01  VAVEHDTALG-R.
           COPY DDS-ALL-FORMATS OF VAVEHDTALG.
      /EJECT
      ***************************************************************
       WORKING-STORAGE SECTION.
      *
      *    Job context
       01  JOB-CONTEXT.
           COPY DDS-ALL-FORMATS OF Y2PGDSPK.
      *    Job date/time
           03  IJBDTTM.
           05  ZZJDT PIC S9(7).
           05  ZZJDTE REDEFINES ZZJDT.
           07  ZZJCC PIC S9(1).
           07  ZZJYY PIC S9(2).
           07  ZZJMM PIC S9(2).
           07  ZZJDD PIC S9(2).
           05  ZZJTM PIC S9(6).
           05  ZZJTME REDEFINES ZZJTM.
           07  ZZJHH PIC S9(2).
           07  ZZJNN PIC S9(2).
           07  ZZJSS PIC S9(2).
           03  ZZFQL PIC X(21).
           03  ZZFLB PIC X(10).
           03  ZZFFL PIC X(10).
           03  ZZFMB PIC X(10).
           03  ZZCDB PIC X(18).
           03  ZZLDB PIC X(18).
           03  ZZTMS PIC X(26).
       01  ZZTIME.
           03  ZZHNS PIC S9(6).
           03  ZZHH PIC S9(2).
      *
       77  C-IND-OFF PIC 1(1) VALUE B'0'.
       77  C-IND-ON PIC 1(1) VALUE B'1'.
       77  W0STRNG PIC X(32766).
      *
       01  FILE-STATUS PIC X(2).
           88  C-IO-OK VALUE '00'.
           88  C-EOF VALUE '10' '46'.
           88  C-NO-MOD-SFLRCDS VALUE '12'.
           88  C-IO-ERR VALUE '21' '22' '24' '30' '34' '90' '91' '92' '9
      -     '4' '95' '9A' '9H' '9I' '9K' '9M' '9N' '9P'.
           88  C-NO-RECORD VALUE '23'.
           88  C-RECORD-LOCKED VALUE '9D'.
      *
       01  UNTIL-CONDITION PIC 1(1).
           88  C-UNTIL-FALSE VALUE B'0'.
           88  C-UNTIL-TRUE VALUE B'1'.
      *
       01  FOREVER PIC 1(1) VALUE B'1'.
           88  C-FOREVER VALUE B'1'.
      *
       01  WRK-IO-TRASH-AREA PIC X(1).
      *
       01  W0RTN PIC X(7).
       01  W0RSF PIC X(1).
       01  W0ENV PIC X(3).
       01  W0RTW PIC S9(9) COMP-4.
       01  W0ICL PIC X(1).
      *    *Synon (17,7) work field
       01  W0WD01 PIC S9(10)V9(7) COMP-3.
      *    *Synon (17,7) work field
       01  W0WD00 PIC S9(10)V9(7) COMP-3.
      *
      *..............................................................
      *    Define Full Externally Described Keylist
       01  EXTSA1.
      *    Registration Date 58
           03  J6REGDT58 PIC S9(8) COMP-3.
      *..............................................................
      *    Outward parameters
       01  PARC.
      *    RCD : Vehicle                   By Reg 58,SCP Model,Vers
      *    I : MAP Invariant BCV
      *    Invariant BCV
           03  PAINVBCV PIC X(15).
      *    I : MAP VIN
      *    VIN
           03  PAVIN PIC X(17).
      *    I : MAP Order Type code
      *    Order Type code
           03  PAORDTYPCD PIC X(1).
      *    I : MAP Owning Account
      *    Owning Account
           03  PAOWNACC PIC X(6).
      *    I : MAP Delivery Account
      *    Delivery Account
           03  PADLVACC PIC X(6).
      *    I : MAP SCP Model code
      *    SCP Model code
           03  PASCMDLCDE PIC X(3).
      *    I : MAP SCP Model Version Code
      *    SCP Model Version Code
           03  PASCVERCDE PIC X(12).
      *    I : MAP SCR Model Code
      *    SCR Model Code
           03  PASCRMDL PIC X(3).
      *    I : MAP SCR Model Version Code
      *    SCR Model Version Code
           03  PASCRVER PIC X(12).
      *    I : MAP Phase
      *    Phase
           03  PAO2ST PIC X(1).
      *    I : MAP Type VP/VU
      *    Type VP/VU
           03  PAIDGENRE PIC X(2).
      *    I : MAP Registration number
      *    Registration number
           03  PAREGMK PIC X(7).
      *    I : MAP Dealer Order Cancel Date
      *    Dealer Order Cancel Date
           03  PADLORDCND PIC S9(8) COMP-3.
      *    I : MAP C.O.C
      *    C.O.C
           03  PANUMRECPT PIC X(26).
      *    I : MAP Version TVV
      *    Version TVV
           03  PATVV PIC X(18).
      *    I : MAP Build Year
      *    Build Year
           03  PABLDYEAR PIC S9(4) COMP-3.
      *    I : MAP Build Week
      *    Build Week
           03  PABLDWEEK PIC S9(2) COMP-3.
      *    I : MAP Build Day
      *    Build Day
           03  PABLDDAY PIC X(1).
      *    I : MAP TCM Date 07
      *    TCM Date 07
           03  PATCMDT07 PIC S9(8) COMP-3.
      *    I : MAP PEC/MADC Date 10
      *    PEC/MADC Date 10
           03  PAPECDT10 PIC S9(8) COMP-3.
      *    I : MAP Vehicle Shipment Date 20
      *    Vehicle Shipment Date 20
           03  PASHPDT20 PIC S9(8) COMP-3.
      *    I : MAP Arrival at Dock Date 28
      *    Arrival at Dock Date 28
           03  PADOCDT28 PIC S9(8) COMP-3.
      *    I : MAP Enter Import Ctr Date 32
      *    Enter Import Ctr Date 32
           03  PAENTIMP32 PIC S9(8) COMP-3.
      *    I : MAP Block Start Date 33
      *    Block Start Date 33
           03  PABLSTDT33 PIC S9(8) COMP-3.
      *    I : MAP Record Block End Date 34
      *    Record Block End Date 34
           03  PABLENDT34 PIC S9(8) COMP-3.
      *    I : MAP Dealer Invoiced Date 42
      *    Dealer Invoiced Date 42
           03  PADLRINV42 PIC S9(8) COMP-3.
      *    I : MAP Exit Import Centre Dte 45
      *    Exit Import Centre Dte 45
           03  PAEXICDT45 PIC S9(8) COMP-3.
      *    I : MAP Requested AAD Date 53
      *    Requested AAD Date 53
           03  PARAADDT53 PIC S9(8) COMP-3.
      *    I : MAP Registration Date 58
      *    Registration Date 58
           03  PAREGDT58 PIC S9(8) COMP-3.
      *    I : MAP Veh Reg Cancelled Date
      *    Veh Reg Cancelled Date
           03  PAVREGCNL PIC S9(8) COMP-3.
      *    I : MAP Customer Order Number
      *    Customer Order Number
           03  PACUSORDNB PIC X(6).
      *    I : MAP Customer Order Date #
      *    Customer Order Date #
           03  PACUSORDD8 PIC S9(8) COMP-3.
      *    I : MAP Veh ARC Planned Date
      *    Veh ARC Planned Date
           03  PAARCPLN PIC S9(8) COMP-3.
      *    I : MAP Veh DDD Requested Date
      *    Veh DDD Requested Date
           03  PADDDREQ PIC S9(8) COMP-3.
      *    I : MAP Veh DDD Forecast Date
      *    Veh DDD Forecast Date
           03  PADDDFCST PIC S9(8) COMP-3.
      *    I : MAP Veh AAD Promise Date
      *    Veh AAD Promise Date
           03  PAAADPRMDT PIC S9(8) COMP-3.
      *    I : MAP Veh AAD Planned Date
      *    Veh AAD Planned Date
           03  PAAADPLN PIC S9(8) COMP-3.
      *    I : MAP Veh AAD Actual Date
      *    Veh AAD Actual Date
           03  PAAADACTDT PIC S9(8) COMP-3.
      *    I : MAP Veh Financial Block
      *    Veh Financial Block
           03  PAVBLKFIN PIC X(1).
      *    I : MAP Veh Commercial Block
      *    Veh Commercial Block
           03  PAVBLKCOM PIC X(1).
      *    I : MAP Veh Quality/CAT Block
      *    Veh Quality/CAT Block
           03  PAVBLKQLT PIC X(1).
      *    I : MAP SEDRE hdr APL code
      *    SEDRE hdr APL code
           03  PASEDAPLCD PIC X(6).
      *
      *    *Return code
       01  WQ0001 PIC X(7).
      *    U:Date D8#
       01  WQ0002 PIC S9(8) COMP-3.
      *    U:Date D8# b
       01  WQ0003 PIC S9(8) COMP-3.
      *    U:Date D8# c
       01  WQ0004 PIC S9(8) COMP-3.
       01  W0CLPG PIC X(10).
      *    *Return code
       01  WQ0005 PIC X(7).
      *    U:Date D8#
       01  WQ0006 PIC S9(8) COMP-3.
      *    U:Date D8# b
       01  WQ0007 PIC S9(8) COMP-3.
      *    U:Date D8# c
       01  WQ0008 PIC S9(8) COMP-3.
      *
      *..............................................................
      *    Define Full Externally Described Keylist
       01  EXTSA2.
      *    Registration Date 58
           03  J6REGDT58 PIC S9(8) COMP-3.
      *..............................................................
      *    *Return code
       01  WQ0009 PIC X(7).
      *    U:Date D8#
       01  WQ0010 PIC S9(8) COMP-3.
      *    U:Date D8# b
       01  WQ0011 PIC S9(8) COMP-3.
      *    U:Date D8# c
       01  WQ0012 PIC S9(8) COMP-3.
      *    *Return code
       01  WQ0013 PIC X(7).
      *    U:Date D8#
       01  WQ0014 PIC S9(8) COMP-3.
      *    U:Date D8# b
       01  WQ0015 PIC S9(8) COMP-3.
      *    U:Date D8# c
       01  WQ0016 PIC S9(8) COMP-3.
       01  ZAPGMQ PIC X(10).
       01  ZAPGRL PIC X(5).
       01  ZAMSID PIC X(7).
       01  ZAMSGF PIC X(10).
       01  ZAMSDA PIC X(132).
       01  ZAMSTP PIC X(7).
       01  ZAILE PIC X(1).
       01  ZAFSMS PIC X(1).
       01  VAVEHDTALG-OPEN.
           COPY DDS-ALL-FORMATS OF Y2IOPEN.
      *    Open feedback area
      *
       01  W0OPN PIC X(1).
       01  W0PMT PIC X(1).
      *    U:Date D8#
       01  WORK-CONTEXT.
           03  YL0001 PIC S9(8) COMP-3.
      *    U:Date D8# b
           03  YL0002 PIC S9(8) COMP-3.
      *    U:Year
           03  WUA1NB PIC S9(2) COMP-3.
      *    U:Period (MMDD)
           03  WUUPERMD PIC S9(4).
      *    U:Number (4.0)
           03  WUC2NB PIC S9(4) COMP-3.
      *    U:Date D8# c
           03  YL0003 PIC S9(8) COMP-3.
      *
      *    Indicators
       01  INDICS.
           03  IND PIC 1(1) OCCURS 99 INDICATOR 1.
           88  C-INDICATOR-ON VALUE B'1'.
           88  C-INDICATOR-OFF VALUE B'0'.
      *
      /EJECT
      ***************************************************************
       LINKAGE SECTION.
      *    Return code
       01  P0RTN PIC X(7).
      ***************************************************************
       PROCEDURE DIVISION USING
             P0RTN
           .
      ***************************************************************
           CONTINUE.
       MAINLINE SECTION.
      *    Initialize
           PERFORM ZZINIT
      *
      *    EXT crt Export veh ric
      *    desc
           PERFORM UA1SUBR
      *    * Y
      *    Cvt *Job date to DTX
      *    * Job date contains a leading 1 when the year is 2000 or
      *      greater
      *    U:Date DTX
           ADD ZZJDT OF JOB-CONTEXT, 19000000 GIVING YL0001 OF
             WORK-CONTEXT
      *    *Y-1
      *    Rtn Add/Sub Years to Date
      *    Extract MMDD of CYYMMDD
      *    U:Year
      *    U:Period (MMDD)
           DIVIDE 10000 INTO ZZJDT OF JOB-CONTEXT GIVING WUA1NB OF
             WORK-CONTEXT REMAINDER WUUPERMD OF WORK-CONTEXT
      *    Add/Subtract Year & produce New YYYY
      *    CASE: WRK.U:Year is *Less than 40
      *    *IF
           IF (WUA1NB OF WORK-CONTEXT < 40) THEN
      *        New value for Year YYYY
      *        WRK.U:Number (4.0) =
      *        *COMPUTE ( x1 + x2 + x3)
      *        x1    : WRK.U:Year
      *        +     : PGM.*Synon (17,7) work field
      *        x2    : CON.2000
      *        +     : PGM.*Synon (17,7) work field
      *        x3    : PAR.U:Number (2.0)
      *        *Synon (17,7) work field
               ADD WUA1NB OF WORK-CONTEXT, 2000 GIVING W0WD01
      *        *Synon (17,7) work field
               ADD W0WD01, -1 GIVING W0WD00
      *        U:Number (4.0)
               MOVE W0WD00 TO WUC2NB OF WORK-CONTEXT
           ELSE
      *        CASE: *OTHERWISE
      *        New value for Year YYYY
      *        WRK.U:Number (4.0) =
      *        *COMPUTE (x1 + x2 + x3)
      *        x1    : WRK.U:Year
      *        +     : PGM.*Synon (17,7) work field
      *        x2    : CON.1900
      *        +     : PGM.*Synon (17,7) work field
      *        x3    : PAR.U:Number (2.0)
      *        *Synon (17,7) work field
               ADD WUA1NB OF WORK-CONTEXT, 1900 GIVING W0WD01
      *        *Synon (17,7) work field
               ADD W0WD01, -1 GIVING W0WD00
      *        U:Number (4.0)
               MOVE W0WD00 TO WUC2NB OF WORK-CONTEXT
           END-IF
      *    New Date YYYYMMDD
      *    PAR.U:Date YYYYMMDD =
      *    *COMPUTE (x1 * x2 + x3)
      *    x1    : WRK.U:Number (4.0)
      *    *     : PGM.*Synon (17,7) work field *
      *    x2    : CON.10000
      *    +     : PGM.*Synon (17,7) work field
      *    x3    : WRK.U:Period (MMDD)
      *    *Synon (17,7) work field
           MULTIPLY WUC2NB OF WORK-CONTEXT BY 10000 GIVING W0WD01
      *    *Synon (17,7) work field
           ADD W0WD01, WUUPERMD OF WORK-CONTEXT GIVING W0WD00
      *    U:Date YYYYMMDD
           MOVE W0WD00 TO YL0002 OF WORK-CONTEXT
      *    *Y-2
      *    Rtn Add/Sub Years to Date
      *    Extract MMDD of CYYMMDD
      *    U:Year
      *    U:Period (MMDD)
           DIVIDE 10000 INTO ZZJDT OF JOB-CONTEXT GIVING WUA1NB OF
             WORK-CONTEXT REMAINDER WUUPERMD OF WORK-CONTEXT
      *    Add/Subtract Year & produce New YYYY
      *    CASE: WRK.U:Year is *Less than 40
      *    *IF
           IF (WUA1NB OF WORK-CONTEXT < 40) THEN
      *        New value for Year YYYY
      *        WRK.U:Number (4.0) =
      *        *COMPUTE ( x1 + x2 + x3)
      *        x1    : WRK.U:Year
      *        +     : PGM.*Synon (17,7) work field
      *        x2    : CON.2000
      *        +     : PGM.*Synon (17,7) work field
      *        x3    : PAR.U:Number (2.0)
      *        *Synon (17,7) work field
               ADD WUA1NB OF WORK-CONTEXT, 2000 GIVING W0WD01
      *        *Synon (17,7) work field
               ADD W0WD01, -2 GIVING W0WD00
      *        U:Number (4.0)
               MOVE W0WD00 TO WUC2NB OF WORK-CONTEXT
           ELSE
      *        CASE: *OTHERWISE
      *        New value for Year YYYY
      *        WRK.U:Number (4.0) =
      *        *COMPUTE (x1 + x2 + x3)
      *        x1    : WRK.U:Year
      *        +     : PGM.*Synon (17,7) work field
      *        x2    : CON.1900
      *        +     : PGM.*Synon (17,7) work field
      *        x3    : PAR.U:Number (2.0)
      *        *Synon (17,7) work field
               ADD WUA1NB OF WORK-CONTEXT, 1900 GIVING W0WD01
      *        *Synon (17,7) work field
               ADD W0WD01, -2 GIVING W0WD00
      *        U:Number (4.0)
               MOVE W0WD00 TO WUC2NB OF WORK-CONTEXT
           END-IF
      *    New Date YYYYMMDD
      *    PAR.U:Date YYYYMMDD =
      *    *COMPUTE (x1 * x2 + x3)
      *    x1    : WRK.U:Number (4.0)
      *    *     : PGM.*Synon (17,7) work field *
      *    x2    : CON.10000
      *    +     : PGM.*Synon (17,7) work field
      *    x3    : WRK.U:Period (MMDD)
      *    *Synon (17,7) work field
           MULTIPLY WUC2NB OF WORK-CONTEXT BY 10000 GIVING W0WD01
      *    *Synon (17,7) work field
           ADD W0WD01, WUUPERMD OF WORK-CONTEXT GIVING W0WD00
      *    U:Date YYYYMMDD
           MOVE W0WD00 TO YL0003 OF WORK-CONTEXT
      *    rtv crt export veh ric - Vehicle  * registred
           PERFORM SA1RVGN
      *    rtv crt export veh ric - Vehicle  * not registred
           PERFORM SA2RVGN
      *--------------------------------------------------------------
      *    Exit program
           CONTINUE.
       AAEXIT.
           MOVE SPACES TO P0RTN
           PERFORM ZYEXPG
      *==============================================================
      /EJECT
       SA1RVGN SECTION.
      *==============================================================
      *    rtv crt export veh ric - Vehicle  * registred
      *==============================================================
      *    Initialize return code
           MOVE SPACES TO W0RTN
      *    Initialise Full Externally Described Keylist
      *    Registration Date 58
           MOVE -99999999 TO J6REGDT58 OF EXTSA1
           MOVE CORRESPONDING
             EXTSA1 TO
             FVEHDHP OF VAVEHDTALG-R
           START VAVEHDTALG KEY NOT < EXTERNALLY-DESCRIBED-KEY
             FORMAT IS 'FVEHDHP'
           END-START
           IF (C-IO-ERR) THEN
               STOP RUN
           END-IF
           SET C-INDICATOR-OFF(90) TO TRUE
           READ VAVEHDTALG NEXT
             FORMAT IS 'FVEHDHP'
           END-READ
           IF (C-EOF) THEN
               SET C-INDICATOR-ON(90) TO TRUE
           ELSE
               IF (C-IO-ERR) THEN
                   STOP RUN
               END-IF
           END-IF
           IF (C-INDICATOR-ON(90)) THEN
      *        Data record not found
               MOVE 'JSM1386' TO W0RTN
           END-IF
           PERFORM UNTIL NOT (C-INDICATOR-OFF(90))
      *        USER: Process Data record
      *        CASE: DB1.Registration Date 58 is Zero
      *        *IF
               IF (J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R = 0) THEN
      *            Ext Crt RIC Vin Export - #Foreign model access  *
      *            Clear array PARC
                   INITIALIZE PARC
      *            Invariant BCV
                   MOVE J6INVBCV OF FVEHDHP OF VAVEHDTALG-R TO PAINVBCV
      *            VIN
                   MOVE J6VIN OF FVEHDHP OF VAVEHDTALG-R TO PAVIN
      *            Order Type code
                   MOVE J6ORDTYPCD OF FVEHDHP OF VAVEHDTALG-R TO
                     PAORDTYPCD
      *            Owning Account
                   MOVE J6OWNACC OF FVEHDHP OF VAVEHDTALG-R TO PAOWNACC
      *            Delivery Account
                   MOVE J6DLVACC OF FVEHDHP OF VAVEHDTALG-R TO PADLVACC
      *            SCP Model code
                   MOVE J6SCMDLCDE OF FVEHDHP OF VAVEHDTALG-R TO
                     PASCMDLCDE
      *            SCP Model Version Code
                   MOVE J6SCVERCDE OF FVEHDHP OF VAVEHDTALG-R TO
                     PASCVERCDE
      *            SCR Model Code
                   MOVE J6SCRMDL OF FVEHDHP OF VAVEHDTALG-R TO PASCRMDL
      *            SCR Model Version Code
                   MOVE J6SCRVER OF FVEHDHP OF VAVEHDTALG-R TO PASCRVER
      *            Phase
                   MOVE J6O2ST OF FVEHDHP OF VAVEHDTALG-R TO PAO2ST
      *            Type VP/VU
                   MOVE J6IDGENRE OF FVEHDHP OF VAVEHDTALG-R TO
                     PAIDGENRE
      *            Registration number
                   MOVE J6REGMK OF FVEHDHP OF VAVEHDTALG-R TO PAREGMK
      *            Dealer Order Cancel Date
                   ADD J6DLORDCND OF FVEHDHP OF VAVEHDTALG-R TO
                     PADLORDCND
      *            C.O.C
                   MOVE J6NUMRECPT OF FVEHDHP OF VAVEHDTALG-R TO
                     PANUMRECPT
      *            Version TVV
                   MOVE J6TVV OF FVEHDHP OF VAVEHDTALG-R TO PATVV
      *            Build Year
                   ADD J6BLDYEAR OF FVEHDHP OF VAVEHDTALG-R TO PABLDYEAR
      *            Build Week
                   ADD J6BLDWEEK OF FVEHDHP OF VAVEHDTALG-R TO PABLDWEEK
      *            Build Day
                   MOVE J6BLDDAY OF FVEHDHP OF VAVEHDTALG-R TO PABLDDAY
      *            TCM Date 07
                   ADD J6TCMDT07 OF FVEHDHP OF VAVEHDTALG-R TO PATCMDT07
      *            PEC/MADC Date 10
                   ADD J6PECDT10 OF FVEHDHP OF VAVEHDTALG-R TO PAPECDT10
      *            Vehicle Shipment Date 20
                   ADD J6SHPDT20 OF FVEHDHP OF VAVEHDTALG-R TO PASHPDT20
      *            Arrival at Dock Date 28
                   ADD J6DOCDT28 OF FVEHDHP OF VAVEHDTALG-R TO PADOCDT28
      *            Enter Import Ctr Date 32
                   ADD J6ENTIMP32 OF FVEHDHP OF VAVEHDTALG-R TO
                     PAENTIMP32
      *            Block Start Date 33
                   ADD J6BLSTDT33 OF FVEHDHP OF VAVEHDTALG-R TO
                     PABLSTDT33
      *            Record Block End Date 34
                   ADD J6BLENDT34 OF FVEHDHP OF VAVEHDTALG-R TO
                     PABLENDT34
      *            Dealer Invoiced Date 42
                   ADD J6DLRINV42 OF FVEHDHP OF VAVEHDTALG-R TO
                     PADLRINV42
      *            Exit Import Centre Dte 45
                   ADD J6EXICDT45 OF FVEHDHP OF VAVEHDTALG-R TO
                     PAEXICDT45
      *            Requested AAD Date 53
                   ADD J6RAADDT53 OF FVEHDHP OF VAVEHDTALG-R TO
                     PARAADDT53
      *            Registration Date 58
                   ADD J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R TO PAREGDT58
      *            Veh Reg Cancelled Date
                   ADD J6VREGCNL OF FVEHDHP OF VAVEHDTALG-R TO PAVREGCNL
      *            Customer Order Number
                   MOVE J6CUSORDNB OF FVEHDHP OF VAVEHDTALG-R TO
                     PACUSORDNB
      *            Customer Order Date #
                   ADD J6CUSORDD8 OF FVEHDHP OF VAVEHDTALG-R TO
                     PACUSORDD8
      *            Veh ARC Planned Date
                   ADD J6ARCPLN OF FVEHDHP OF VAVEHDTALG-R TO PAARCPLN
      *            Veh DDD Requested Date
                   ADD J6DDDREQ OF FVEHDHP OF VAVEHDTALG-R TO PADDDREQ
      *            Veh DDD Forecast Date
                   ADD J6DDDFCST OF FVEHDHP OF VAVEHDTALG-R TO PADDDFCST
      *            Veh AAD Promise Date
                   ADD J6AADPRMDT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAAADPRMDT
      *            Veh AAD Planned Date
                   ADD J6AADPLN OF FVEHDHP OF VAVEHDTALG-R TO PAAADPLN
      *            Veh AAD Actual Date
                   ADD J6AADACTDT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAAADACTDT
      *            Veh Financial Block
                   MOVE J6VBLKFIN OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKFIN
      *            Veh Commercial Block
                   MOVE J6VBLKCOM OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKCOM
      *            Veh Quality/CAT Block
                   MOVE J6VBLKQLT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKQLT
      *            SEDRE hdr APL code
                   MOVE J6SEDAPLCD OF FVEHDHP OF VAVEHDTALG-R TO
                     PASEDAPLCD
      *
                   SET C-INDICATOR-OFF(90) TO TRUE
                   MOVE SPACES TO WQ0001
                   MOVE YL0001 OF WORK-CONTEXT TO WQ0002
                   MOVE YL0002 OF WORK-CONTEXT TO WQ0003
                   MOVE YL0003 OF WORK-CONTEXT TO WQ0004
      *
                   CALL 'RIC000121S' USING
      *            *Return code
                     WQ0001
      *            RCD : Vehicle
                     PARC
      *            U:Date D8#
                     WQ0002
      *            U:Date D8# b
                     WQ0003
      *            U:Date D8# c
                     WQ0004
                            ON OVERFLOW
                            SET C-INDICATOR-ON(90) TO TRUE
                   END-CALL
      *
                   MOVE WQ0001 TO W0RTN
      *
      *            Error on program call will terminate run unit
                   IF (C-INDICATOR-ON(90)) THEN
                       MOVE 'Y2U0032' TO W0RTN
                       MOVE 'RIC000121S' TO W0CLPG
      *                Send message '*Error occured on CALL...'
      *                Message ID
                       MOVE 'Y2U0032' TO ZAMSID
      *                Message file
                       MOVE 'Y2USRMSG' TO ZAMSGF
      *                Message data
                       MOVE W0CLPG TO ZAMSDA
                       PERFORM ZASNMS
                       SET C-INDICATOR-ON(99) TO TRUE
                   END-IF
               ELSE
      *            CASE:
      *            - c1 AND c2
      *            |- c1    : DB1.Registration Date 58 GE PAR.U:Date
      *              D8# c
      *            |- c2    : DB1.Registration Date 58 LE PAR.U:Date D8#
      *            '-
      *            *IF
                   IF (J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R NOT <
                     YL0003 OF WORK-CONTEXT AND
                       J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R NOT >
                     YL0001 OF WORK-CONTEXT) THEN
      *                Ext Crt RIC Vin Export - #Foreign model access
      *                  *
      *                Clear array PARC
                       INITIALIZE PARC
      *                Invariant BCV
                       MOVE J6INVBCV OF FVEHDHP OF VAVEHDTALG-R TO
                         PAINVBCV
      *                VIN
                       MOVE J6VIN OF FVEHDHP OF VAVEHDTALG-R TO PAVIN
      *                Order Type code
                       MOVE J6ORDTYPCD OF FVEHDHP OF VAVEHDTALG-R TO
                         PAORDTYPCD
      *                Owning Account
                       MOVE J6OWNACC OF FVEHDHP OF VAVEHDTALG-R TO
                         PAOWNACC
      *                Delivery Account
                       MOVE J6DLVACC OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLVACC
      *                SCP Model code
                       MOVE J6SCMDLCDE OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCMDLCDE
      *                SCP Model Version Code
                       MOVE J6SCVERCDE OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCVERCDE
      *                SCR Model Code
                       MOVE J6SCRMDL OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCRMDL
      *                SCR Model Version Code
                       MOVE J6SCRVER OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCRVER
      *                Phase
                       MOVE J6O2ST OF FVEHDHP OF VAVEHDTALG-R TO PAO2ST
      *                Type VP/VU
                       MOVE J6IDGENRE OF FVEHDHP OF VAVEHDTALG-R TO
                         PAIDGENRE
      *                Registration number
                       MOVE J6REGMK OF FVEHDHP OF VAVEHDTALG-R TO
                         PAREGMK
      *                Dealer Order Cancel Date
                       ADD J6DLORDCND OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLORDCND
      *                C.O.C
                       MOVE J6NUMRECPT OF FVEHDHP OF VAVEHDTALG-R TO
                         PANUMRECPT
      *                Version TVV
                       MOVE J6TVV OF FVEHDHP OF VAVEHDTALG-R TO PATVV
      *                Build Year
                       ADD J6BLDYEAR OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDYEAR
      *                Build Week
                       ADD J6BLDWEEK OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDWEEK
      *                Build Day
                       MOVE J6BLDDAY OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDDAY
      *                TCM Date 07
                       ADD J6TCMDT07 OF FVEHDHP OF VAVEHDTALG-R TO
                         PATCMDT07
      *                PEC/MADC Date 10
                       ADD J6PECDT10 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAPECDT10
      *                Vehicle Shipment Date 20
                       ADD J6SHPDT20 OF FVEHDHP OF VAVEHDTALG-R TO
                         PASHPDT20
      *                Arrival at Dock Date 28
                       ADD J6DOCDT28 OF FVEHDHP OF VAVEHDTALG-R TO
                         PADOCDT28
      *                Enter Import Ctr Date 32
                       ADD J6ENTIMP32 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAENTIMP32
      *                Block Start Date 33
                       ADD J6BLSTDT33 OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLSTDT33
      *                Record Block End Date 34
                       ADD J6BLENDT34 OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLENDT34
      *                Dealer Invoiced Date 42
                       ADD J6DLRINV42 OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLRINV42
      *                Exit Import Centre Dte 45
                       ADD J6EXICDT45 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAEXICDT45
      *                Requested AAD Date 53
                       ADD J6RAADDT53 OF FVEHDHP OF VAVEHDTALG-R TO
                         PARAADDT53
      *                Registration Date 58
                       ADD J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAREGDT58
      *                Veh Reg Cancelled Date
                       ADD J6VREGCNL OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVREGCNL
      *                Customer Order Number
                       MOVE J6CUSORDNB OF FVEHDHP OF VAVEHDTALG-R TO
                         PACUSORDNB
      *                Customer Order Date #
                       ADD J6CUSORDD8 OF FVEHDHP OF VAVEHDTALG-R TO
                         PACUSORDD8
      *                Veh ARC Planned Date
                       ADD J6ARCPLN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAARCPLN
      *                Veh DDD Requested Date
                       ADD J6DDDREQ OF FVEHDHP OF VAVEHDTALG-R TO
                         PADDDREQ
      *                Veh DDD Forecast Date
                       ADD J6DDDFCST OF FVEHDHP OF VAVEHDTALG-R TO
                         PADDDFCST
      *                Veh AAD Promise Date
                       ADD J6AADPRMDT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADPRMDT
      *                Veh AAD Planned Date
                       ADD J6AADPLN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADPLN
      *                Veh AAD Actual Date
                       ADD J6AADACTDT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADACTDT
      *                Veh Financial Block
                       MOVE J6VBLKFIN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKFIN
      *                Veh Commercial Block
                       MOVE J6VBLKCOM OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKCOM
      *                Veh Quality/CAT Block
                       MOVE J6VBLKQLT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKQLT
      *                SEDRE hdr APL code
                       MOVE J6SEDAPLCD OF FVEHDHP OF VAVEHDTALG-R TO
                         PASEDAPLCD
      *
                       SET C-INDICATOR-OFF(90) TO TRUE
                       MOVE SPACES TO WQ0005
                       MOVE YL0001 OF WORK-CONTEXT TO WQ0006
                       MOVE YL0002 OF WORK-CONTEXT TO WQ0007
                       MOVE YL0003 OF WORK-CONTEXT TO WQ0008
      *
                       CALL 'RIC000121S' USING
      *                *Return code
                         WQ0005
      *                RCD : Vehicle
                         PARC
      *                U:Date D8#
                         WQ0006
      *                U:Date D8# b
                         WQ0007
      *                U:Date D8# c
                         WQ0008
                                ON OVERFLOW
                                SET C-INDICATOR-ON(90) TO TRUE
                       END-CALL
      *
                       MOVE WQ0005 TO W0RTN
      *
      *                Error on program call will terminate run unit
                       IF (C-INDICATOR-ON(90)) THEN
                           MOVE 'Y2U0032' TO W0RTN
                           MOVE 'RIC000121S' TO W0CLPG
      *                    Send message '*Error occured on CALL...'
      *                    Message ID
                           MOVE 'Y2U0032' TO ZAMSID
      *                    Message file
                           MOVE 'Y2USRMSG' TO ZAMSGF
      *                    Message data
                           MOVE W0CLPG TO ZAMSDA
                           PERFORM ZASNMS
                           SET C-INDICATOR-ON(99) TO TRUE
                       END-IF
                   END-IF
               END-IF
               SET C-INDICATOR-OFF(90) TO TRUE
               READ VAVEHDTALG NEXT
                 FORMAT IS 'FVEHDHP'
               END-READ
               IF (C-EOF) THEN
                   SET C-INDICATOR-ON(90) TO TRUE
               ELSE
                   IF (C-IO-ERR) THEN
                       STOP RUN
                   END-IF
               END-IF
           END-PERFORM
      *==============================================================
           CONTINUE.
       SA1EXIT.
           EXIT.
      /EJECT
       SA2RVGN SECTION.
      *==============================================================
      *    rtv crt export veh ric - Vehicle  * not registred
      *==============================================================
      *    Initialize return code
           MOVE SPACES TO W0RTN
      *    Initialise Full Externally Described Keylist
      *    Registration Date 58
           MOVE -99999999 TO J6REGDT58 OF EXTSA2
           MOVE CORRESPONDING
             EXTSA2 TO
             FVEHDHP OF VAVEHDTALG-R
           START VAVEHDTALG KEY NOT < EXTERNALLY-DESCRIBED-KEY
             FORMAT IS 'FVEHDHP'
           END-START
           IF (C-IO-ERR) THEN
               STOP RUN
           END-IF
           SET C-INDICATOR-OFF(90) TO TRUE
           READ VAVEHDTALG NEXT
             FORMAT IS 'FVEHDHP'
           END-READ
           IF (C-EOF) THEN
               SET C-INDICATOR-ON(90) TO TRUE
           ELSE
               IF (C-IO-ERR) THEN
                   STOP RUN
               END-IF
           END-IF
           IF (C-INDICATOR-ON(90)) THEN
      *        Data record not found
               MOVE 'JSM1386' TO W0RTN
           END-IF
           PERFORM UNTIL NOT (C-INDICATOR-OFF(90))
      *        USER: Process Data record
      *        CASE: DB1.Registration Date 58 is Zero
      *        *IF
               IF (J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R = 0) THEN
      *            Ext Crt RIC Vin Export - #Foreign model access  *
      *            Clear array PARC
                   INITIALIZE PARC
      *            Invariant BCV
                   MOVE J6INVBCV OF FVEHDHP OF VAVEHDTALG-R TO PAINVBCV
      *            VIN
                   MOVE J6VIN OF FVEHDHP OF VAVEHDTALG-R TO PAVIN
      *            Order Type code
                   MOVE J6ORDTYPCD OF FVEHDHP OF VAVEHDTALG-R TO
                     PAORDTYPCD
      *            Owning Account
                   MOVE J6OWNACC OF FVEHDHP OF VAVEHDTALG-R TO PAOWNACC
      *            Delivery Account
                   MOVE J6DLVACC OF FVEHDHP OF VAVEHDTALG-R TO PADLVACC
      *            SCP Model code
                   MOVE J6SCMDLCDE OF FVEHDHP OF VAVEHDTALG-R TO
                     PASCMDLCDE
      *            SCP Model Version Code
                   MOVE J6SCVERCDE OF FVEHDHP OF VAVEHDTALG-R TO
                     PASCVERCDE
      *            SCR Model Code
                   MOVE J6SCRMDL OF FVEHDHP OF VAVEHDTALG-R TO PASCRMDL
      *            SCR Model Version Code
                   MOVE J6SCRVER OF FVEHDHP OF VAVEHDTALG-R TO PASCRVER
      *            Phase
                   MOVE J6O2ST OF FVEHDHP OF VAVEHDTALG-R TO PAO2ST
      *            Type VP/VU
                   MOVE J6IDGENRE OF FVEHDHP OF VAVEHDTALG-R TO
                     PAIDGENRE
      *            Registration number
                   MOVE J6REGMK OF FVEHDHP OF VAVEHDTALG-R TO PAREGMK
      *            Dealer Order Cancel Date
                   ADD J6DLORDCND OF FVEHDHP OF VAVEHDTALG-R TO
                     PADLORDCND
      *            C.O.C
                   MOVE J6NUMRECPT OF FVEHDHP OF VAVEHDTALG-R TO
                     PANUMRECPT
      *            Version TVV
                   MOVE J6TVV OF FVEHDHP OF VAVEHDTALG-R TO PATVV
      *            Build Year
                   ADD J6BLDYEAR OF FVEHDHP OF VAVEHDTALG-R TO PABLDYEAR
      *            Build Week
                   ADD J6BLDWEEK OF FVEHDHP OF VAVEHDTALG-R TO PABLDWEEK
      *            Build Day
                   MOVE J6BLDDAY OF FVEHDHP OF VAVEHDTALG-R TO PABLDDAY
      *            TCM Date 07
                   ADD J6TCMDT07 OF FVEHDHP OF VAVEHDTALG-R TO PATCMDT07
      *            PEC/MADC Date 10
                   ADD J6PECDT10 OF FVEHDHP OF VAVEHDTALG-R TO PAPECDT10
      *            Vehicle Shipment Date 20
                   ADD J6SHPDT20 OF FVEHDHP OF VAVEHDTALG-R TO PASHPDT20
      *            Arrival at Dock Date 28
                   ADD J6DOCDT28 OF FVEHDHP OF VAVEHDTALG-R TO PADOCDT28
      *            Enter Import Ctr Date 32
                   ADD J6ENTIMP32 OF FVEHDHP OF VAVEHDTALG-R TO
                     PAENTIMP32
      *            Block Start Date 33
                   ADD J6BLSTDT33 OF FVEHDHP OF VAVEHDTALG-R TO
                     PABLSTDT33
      *            Record Block End Date 34
                   ADD J6BLENDT34 OF FVEHDHP OF VAVEHDTALG-R TO
                     PABLENDT34
      *            Dealer Invoiced Date 42
                   ADD J6DLRINV42 OF FVEHDHP OF VAVEHDTALG-R TO
                     PADLRINV42
      *            Exit Import Centre Dte 45
                   ADD J6EXICDT45 OF FVEHDHP OF VAVEHDTALG-R TO
                     PAEXICDT45
      *            Requested AAD Date 53
                   ADD J6RAADDT53 OF FVEHDHP OF VAVEHDTALG-R TO
                     PARAADDT53
      *            Registration Date 58
                   ADD J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R TO PAREGDT58
      *            Veh Reg Cancelled Date
                   ADD J6VREGCNL OF FVEHDHP OF VAVEHDTALG-R TO PAVREGCNL
      *            Customer Order Number
                   MOVE J6CUSORDNB OF FVEHDHP OF VAVEHDTALG-R TO
                     PACUSORDNB
      *            Customer Order Date #
                   ADD J6CUSORDD8 OF FVEHDHP OF VAVEHDTALG-R TO
                     PACUSORDD8
      *            Veh ARC Planned Date
                   ADD J6ARCPLN OF FVEHDHP OF VAVEHDTALG-R TO PAARCPLN
      *            Veh DDD Requested Date
                   ADD J6DDDREQ OF FVEHDHP OF VAVEHDTALG-R TO PADDDREQ
      *            Veh DDD Forecast Date
                   ADD J6DDDFCST OF FVEHDHP OF VAVEHDTALG-R TO PADDDFCST
      *            Veh AAD Promise Date
                   ADD J6AADPRMDT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAAADPRMDT
      *            Veh AAD Planned Date
                   ADD J6AADPLN OF FVEHDHP OF VAVEHDTALG-R TO PAAADPLN
      *            Veh AAD Actual Date
                   ADD J6AADACTDT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAAADACTDT
      *            Veh Financial Block
                   MOVE J6VBLKFIN OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKFIN
      *            Veh Commercial Block
                   MOVE J6VBLKCOM OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKCOM
      *            Veh Quality/CAT Block
                   MOVE J6VBLKQLT OF FVEHDHP OF VAVEHDTALG-R TO
                     PAVBLKQLT
      *            SEDRE hdr APL code
                   MOVE J6SEDAPLCD OF FVEHDHP OF VAVEHDTALG-R TO
                     PASEDAPLCD
      *
                   SET C-INDICATOR-OFF(90) TO TRUE
                   MOVE SPACES TO WQ0009
                   MOVE YL0001 OF WORK-CONTEXT TO WQ0010
                   MOVE YL0002 OF WORK-CONTEXT TO WQ0011
                   MOVE YL0003 OF WORK-CONTEXT TO WQ0012
      *
                   CALL 'RIC000121S' USING
      *            *Return code
                     WQ0009
      *            RCD : Vehicle
                     PARC
      *            U:Date D8#
                     WQ0010
      *            U:Date D8# b
                     WQ0011
      *            U:Date D8# c
                     WQ0012
                            ON OVERFLOW
                            SET C-INDICATOR-ON(90) TO TRUE
                   END-CALL
      *
                   MOVE WQ0009 TO W0RTN
      *
      *            Error on program call will terminate run unit
                   IF (C-INDICATOR-ON(90)) THEN
                       MOVE 'Y2U0032' TO W0RTN
                       MOVE 'RIC000121S' TO W0CLPG
      *                Send message '*Error occured on CALL...'
      *                Message ID
                       MOVE 'Y2U0032' TO ZAMSID
      *                Message file
                       MOVE 'Y2USRMSG' TO ZAMSGF
      *                Message data
                       MOVE W0CLPG TO ZAMSDA
                       PERFORM ZASNMS
                       SET C-INDICATOR-ON(99) TO TRUE
                   END-IF
               ELSE
      *            CASE:
      *            - c1 AND c2
      *            |- c1    : DB1.Registration Date 58 GE PAR.U:Date
      *              D8# c
      *            |- c2    : DB1.Registration Date 58 LE PAR.U:Date D8#
      *            '-
      *            *IF
                   IF (J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R NOT <
                     YL0003 OF WORK-CONTEXT AND
                       J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R NOT >
                     YL0001 OF WORK-CONTEXT) THEN
      *                Ext Crt RIC Vin Export - #Foreign model access
      *                  *
      *                Clear array PARC
                       INITIALIZE PARC
      *                Invariant BCV
                       MOVE J6INVBCV OF FVEHDHP OF VAVEHDTALG-R TO
                         PAINVBCV
      *                VIN
                       MOVE J6VIN OF FVEHDHP OF VAVEHDTALG-R TO PAVIN
      *                Order Type code
                       MOVE J6ORDTYPCD OF FVEHDHP OF VAVEHDTALG-R TO
                         PAORDTYPCD
      *                Owning Account
                       MOVE J6OWNACC OF FVEHDHP OF VAVEHDTALG-R TO
                         PAOWNACC
      *                Delivery Account
                       MOVE J6DLVACC OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLVACC
      *                SCP Model code
                       MOVE J6SCMDLCDE OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCMDLCDE
      *                SCP Model Version Code
                       MOVE J6SCVERCDE OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCVERCDE
      *                SCR Model Code
                       MOVE J6SCRMDL OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCRMDL
      *                SCR Model Version Code
                       MOVE J6SCRVER OF FVEHDHP OF VAVEHDTALG-R TO
                         PASCRVER
      *                Phase
                       MOVE J6O2ST OF FVEHDHP OF VAVEHDTALG-R TO PAO2ST
      *                Type VP/VU
                       MOVE J6IDGENRE OF FVEHDHP OF VAVEHDTALG-R TO
                         PAIDGENRE
      *                Registration number
                       MOVE J6REGMK OF FVEHDHP OF VAVEHDTALG-R TO
                         PAREGMK
      *                Dealer Order Cancel Date
                       ADD J6DLORDCND OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLORDCND
      *                C.O.C
                       MOVE J6NUMRECPT OF FVEHDHP OF VAVEHDTALG-R TO
                         PANUMRECPT
      *                Version TVV
                       MOVE J6TVV OF FVEHDHP OF VAVEHDTALG-R TO PATVV
      *                Build Year
                       ADD J6BLDYEAR OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDYEAR
      *                Build Week
                       ADD J6BLDWEEK OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDWEEK
      *                Build Day
                       MOVE J6BLDDAY OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLDDAY
      *                TCM Date 07
                       ADD J6TCMDT07 OF FVEHDHP OF VAVEHDTALG-R TO
                         PATCMDT07
      *                PEC/MADC Date 10
                       ADD J6PECDT10 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAPECDT10
      *                Vehicle Shipment Date 20
                       ADD J6SHPDT20 OF FVEHDHP OF VAVEHDTALG-R TO
                         PASHPDT20
      *                Arrival at Dock Date 28
                       ADD J6DOCDT28 OF FVEHDHP OF VAVEHDTALG-R TO
                         PADOCDT28
      *                Enter Import Ctr Date 32
                       ADD J6ENTIMP32 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAENTIMP32
      *                Block Start Date 33
                       ADD J6BLSTDT33 OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLSTDT33
      *                Record Block End Date 34
                       ADD J6BLENDT34 OF FVEHDHP OF VAVEHDTALG-R TO
                         PABLENDT34
      *                Dealer Invoiced Date 42
                       ADD J6DLRINV42 OF FVEHDHP OF VAVEHDTALG-R TO
                         PADLRINV42
      *                Exit Import Centre Dte 45
                       ADD J6EXICDT45 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAEXICDT45
      *                Requested AAD Date 53
                       ADD J6RAADDT53 OF FVEHDHP OF VAVEHDTALG-R TO
                         PARAADDT53
      *                Registration Date 58
                       ADD J6REGDT58 OF FVEHDHP OF VAVEHDTALG-R TO
                         PAREGDT58
      *                Veh Reg Cancelled Date
                       ADD J6VREGCNL OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVREGCNL
      *                Customer Order Number
                       MOVE J6CUSORDNB OF FVEHDHP OF VAVEHDTALG-R TO
                         PACUSORDNB
      *                Customer Order Date #
                       ADD J6CUSORDD8 OF FVEHDHP OF VAVEHDTALG-R TO
                         PACUSORDD8
      *                Veh ARC Planned Date
                       ADD J6ARCPLN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAARCPLN
      *                Veh DDD Requested Date
                       ADD J6DDDREQ OF FVEHDHP OF VAVEHDTALG-R TO
                         PADDDREQ
      *                Veh DDD Forecast Date
                       ADD J6DDDFCST OF FVEHDHP OF VAVEHDTALG-R TO
                         PADDDFCST
      *                Veh AAD Promise Date
                       ADD J6AADPRMDT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADPRMDT
      *                Veh AAD Planned Date
                       ADD J6AADPLN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADPLN
      *                Veh AAD Actual Date
                       ADD J6AADACTDT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAAADACTDT
      *                Veh Financial Block
                       MOVE J6VBLKFIN OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKFIN
      *                Veh Commercial Block
                       MOVE J6VBLKCOM OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKCOM
      *                Veh Quality/CAT Block
                       MOVE J6VBLKQLT OF FVEHDHP OF VAVEHDTALG-R TO
                         PAVBLKQLT
      *                SEDRE hdr APL code
                       MOVE J6SEDAPLCD OF FVEHDHP OF VAVEHDTALG-R TO
                         PASEDAPLCD
      *
                       SET C-INDICATOR-OFF(90) TO TRUE
                       MOVE SPACES TO WQ0013
                       MOVE YL0001 OF WORK-CONTEXT TO WQ0014
                       MOVE YL0002 OF WORK-CONTEXT TO WQ0015
                       MOVE YL0003 OF WORK-CONTEXT TO WQ0016
      *
                       CALL 'RIC000121S' USING
      *                *Return code
                         WQ0013
      *                RCD : Vehicle
                         PARC
      *                U:Date D8#
                         WQ0014
      *                U:Date D8# b
                         WQ0015
      *                U:Date D8# c
                         WQ0016
                                ON OVERFLOW
                                SET C-INDICATOR-ON(90) TO TRUE
                       END-CALL
      *
                       MOVE WQ0013 TO W0RTN
      *
      *                Error on program call will terminate run unit
                       IF (C-INDICATOR-ON(90)) THEN
                           MOVE 'Y2U0032' TO W0RTN
                           MOVE 'RIC000121S' TO W0CLPG
      *                    Send message '*Error occured on CALL...'
      *                    Message ID
                           MOVE 'Y2U0032' TO ZAMSID
      *                    Message file
                           MOVE 'Y2USRMSG' TO ZAMSGF
      *                    Message data
                           MOVE W0CLPG TO ZAMSDA
                           PERFORM ZASNMS
                           SET C-INDICATOR-ON(99) TO TRUE
                       END-IF
                   END-IF
               END-IF
               SET C-INDICATOR-OFF(90) TO TRUE
               READ VAVEHDTALG NEXT
                 FORMAT IS 'FVEHDHP'
               END-READ
               IF (C-EOF) THEN
                   SET C-INDICATOR-ON(90) TO TRUE
               ELSE
                   IF (C-IO-ERR) THEN
                       STOP RUN
                   END-IF
               END-IF
           END-PERFORM
      *==============================================================
           CONTINUE.
       SA2EXIT.
           EXIT.
      /EJECT
       UA1SUBR SECTION.
      *==============================================================
      *    desc
      *==============================================================
      *    ------------------------------------------------------------
      *      --------------
      *    Application:  RIC (UK) IRN-11945
      *    Created: 12.09.2019  JLT     bug:90713
      *    Desc: Create export Vehicle vin
      *    To extract VIN information in Y, Y-1, Y-2 information
      *    ------------------------------------------------------------
      *      --------------
      *    Utl @Copyright - #Standard Functions  *
     E* Y2V3114 - Source member UTLCPYRGTS not found.
      *    Changes:
      *==============================================================
           CONTINUE.
       UA1EXIT.
           EXIT.
      /EJECT
       ZASNMS SECTION.
      *==============================================================
      *    Send message to program's message queue
      *==============================================================
      *    Send if first error message or not an error message
           IF (ZAMSTP NOT = SPACES OR
               ZAFSMS NOT = 'N') THEN
               IF (ZAMSTP = SPACES) THEN
      *            Signal first error message sent
                   MOVE 'N' TO ZAFSMS
               END-IF
               IF (ZAPGMQ = SPACES) THEN
                   MOVE ZZPGM OF JOB-CONTEXT TO ZAPGMQ
               END-IF
               MOVE 'Y' TO ZAILE
               CALL 'Y2SNMGC' USING
      *        Program queue
                 ZAPGMQ
      *        Relative queue
                 ZAPGRL
      *        Message ID
                 ZAMSID
      *        Message file
                 ZAMSGF
      *        Message data
                 ZAMSDA
      *        Message type
                 ZAMSTP
                 ZAILE
               END-CALL
           END-IF
      *    Clear all fields for default mechanism next time
      *    Program queue
           MOVE SPACES TO ZAPGMQ
      *    Relative queue
           MOVE SPACES TO ZAPGRL
      *    Message ID
           MOVE SPACES TO ZAMSID
      *    Message file
           MOVE SPACES TO ZAMSGF
      *    Message data
           MOVE SPACES TO ZAMSDA
      *    Message type
           MOVE SPACES TO ZAMSTP
      *==============================================================
           CONTINUE.
       ZAEXIT.
           EXIT.
      /EJECT
       ZXEXPG SECTION.
      *==============================================================
      *    Exit program: Normal
      *==============================================================
           PERFORM ZYEXPG
      *==============================================================
           CONTINUE.
       ZXEXIT.
           EXIT.
      /EJECT
       ZYEXPG SECTION.
      *==============================================================
      *    Exit program: Direct
      *==============================================================
           CLOSE VAVEHDTALG
      *    Reset entry parameters as appropriate
           PERFORM ZZEXPM.
      *    Exit program
           CONTINUE.
       ZYEXPG-EXIT.
           GOBACK.
      *==============================================================
           CONTINUE.
       ZYEXIT.
           EXIT.
      /EJECT
       ZZEXPM SECTION.
      *==============================================================
      *    Return parameters from work fields
      *==============================================================
      *==============================================================
           CONTINUE.
       ZZPEXT.
           EXIT.
      /EJECT
       ZZINIT SECTION.
      *==============================================================
      *    Initialisation
      *==============================================================
           IF (W0ICL = SPACES) THEN
      *        *Initial call
               MOVE 'Y' TO W0ICL
           ELSE
               MOVE 'N' TO W0ICL
           END-IF
           MOVE SPACES TO P0RTN
           MOVE SPACES TO W0RTN
           MOVE ZEROS  TO W0RTW
           MOVE SPACES TO W0RSF
           MOVE '400' TO W0ENV
           MOVE ALL B'0' TO INDICS
           MOVE SPACES TO ZZPGM OF JOB-CONTEXT
      *    Retrieve job attributes
           CALL 'Y2RTJCR' USING
             JOB-CONTEXT
           END-CALL
      *    Setup job date/time
           MOVE ZZSD7 OF JOB-CONTEXT TO ZZJDT
           ACCEPT ZZTIME FROM TIME
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT
           MOVE 'RIC000120S' TO ZZPGM OF JOB-CONTEXT
      *    Define work field U:Year
           MOVE ZERO TO WUA1NB OF WORK-CONTEXT
      *    Define work field U:Period (MMDD)
           MOVE ZERO TO WUUPERMD OF WORK-CONTEXT
      *    Define work field U:Number (4.0)
           MOVE ZERO TO WUC2NB OF WORK-CONTEXT
      *    Signal first error message outstanding
           MOVE 'Y' TO ZAFSMS
      *    Open files
           OPEN INPUT VAVEHDTALG
           ACCEPT VAVEHDTALG-OPEN FROM OPEN-FEEDBACK-AREA FOR VAVEHDTALG
      *    Move main file information to JOB context
           MOVE CORRESPONDING OPENFA OF VAVEHDTALG-OPEN TO JOB-CONTEXT
           CALL 'Y2QLVNR' USING
             ZZFFL OF JOB-CONTEXT
             ZZFLB OF JOB-CONTEXT
             ZZFQL OF JOB-CONTEXT
           END-CALL
           MOVE 'Y' TO W0OPN
           MOVE 'N' TO W0PMT
      *    Define local work field U:Date D8#
           MOVE ZERO TO YL0001 OF WORK-CONTEXT
      *    Define local work field U:Date D8# b
           MOVE ZERO TO YL0002 OF WORK-CONTEXT
      *    Define local work field U:Date D8# c
           MOVE ZERO TO YL0003 OF WORK-CONTEXT
      *==============================================================
           CONTINUE.
       ZZEXIT.
           EXIT.
