       PROCESS APOST GRAPHIC.
      ***************************************************************
       IDENTIFICATION DIVISION.
     H/TITLE EXC Prc bonus Suggest 2   Execute external functio
     Z* CRTBNDCBL
     Z* CVTOPT(*DATETIME) DBGVIEW(*SOURCE) OPTIMIZE(*BASIC)
     Z* BNDDIR(YBNDDIR) ACTGRP(*CALLER)
      *
     H* SYNOPSIS :
     H*  Perform user function
     H*  As defined by action diagram
     H* Generated by CA 2E release 8.7 (1632)
     H* Function type : Execute external function  Version:  8.7
     H* Object type   : *PGM
      *
     H* Company    : Renault (UK) Applications
     H* System     : Renault (UK) Applications
     H* User name  : PRAGTSK
     H* Date       : 18/01/18 time: 10:51:06
     H* Copyright  : Renault (UK) Applications
      *
      *==============================================================
     M* MAINTENANCE   :
      *==============================================================
       PROGRAM-ID.  SBA011000S.
      /EJECT
      ***************************************************************
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.  IBM-AS400.
       OBJECT-COMPUTER.  IBM-AS400.
       SPECIAL-NAMES.  OPEN-FEEDBACK IS OPEN-FEEDBACK-AREA,
           I-O-FEEDBACK IS I-O-FEEDBACK-AREA.
      /EJECT
      ***************************************************************
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      *
           SELECT SBBNSDA2L0
             ASSIGN TO DATABASE-SBBNSDA2L0
             ORGANIZATION IS INDEXED
             ACCESS MODE IS DYNAMIC
             RECORD KEY IS EXTERNALLY-DESCRIBED-KEY
             FILE STATUS IS FILE-STATUS.
      *    UPD : Bonus Sls-Suggest DlrAch2 Update index
      *
       I-O-CONTROL.
      *
      /EJECT
      ***************************************************************
       DATA DIVISION.
       FILE SECTION.
      *
      *
       FD  SBBNSDA2L0
           LABEL RECORDS ARE STANDARD.
       01  SBBNSDA2L0-R.
           COPY DDS-ALL-FORMATS OF SBBNSDA2L0.
      /EJECT
      ***************************************************************
       WORKING-STORAGE SECTION.
      *
      *    Job context
       01  JOB-CONTEXT.
           COPY DDS-ALL-FORMATS OF Y2PGDSPK.
      *    Job date/time
           03  IJBDTTM.
           05  ZZJDT PIC S9(7).
           05  ZZJDTE REDEFINES ZZJDT.
           07  ZZJCC PIC S9(1).
           07  ZZJYY PIC S9(2).
           07  ZZJMM PIC S9(2).
           07  ZZJDD PIC S9(2).
           05  ZZJTM PIC S9(6).
           05  ZZJTME REDEFINES ZZJTM.
           07  ZZJHH PIC S9(2).
           07  ZZJNN PIC S9(2).
           07  ZZJSS PIC S9(2).
           03  ZZFQL PIC X(21).
           03  ZZFLB PIC X(10).
           03  ZZFFL PIC X(10).
           03  ZZFMB PIC X(10).
           03  ZZCDB PIC X(18).
           03  ZZLDB PIC X(18).
           03  ZZTMS PIC X(26).
       01  ZZTIME.
           03  ZZHNS PIC S9(6).
           03  ZZHH PIC S9(2).
      *
       77  C-IND-OFF PIC 1(1) VALUE B'0'.
       77  C-IND-ON PIC 1(1) VALUE B'1'.
       77  W0STRNG PIC X(32766).
      *
       01  FILE-STATUS PIC X(2).
           88  C-IO-OK VALUE '00'.
           88  C-EOF VALUE '10' '46'.
           88  C-NO-MOD-SFLRCDS VALUE '12'.
           88  C-IO-ERR VALUE '21' '22' '24' '30' '34' '90' '91' '92' '9
      -     '4' '95' '9A' '9H' '9I' '9K' '9M' '9N' '9P'.
           88  C-NO-RECORD VALUE '23'.
           88  C-RECORD-LOCKED VALUE '9D'.
      *
       01  UNTIL-CONDITION PIC 1(1).
           88  C-UNTIL-FALSE VALUE B'0'.
           88  C-UNTIL-TRUE VALUE B'1'.
      *
       01  FOREVER PIC 1(1) VALUE B'1'.
           88  C-FOREVER VALUE B'1'.
      *
       01  WRK-IO-TRASH-AREA PIC X(1).
      *
       01  W0RTN PIC X(7).
       01  W0RSF PIC X(1).
       01  W0ENV PIC X(3).
       01  W0RTW PIC S9(9) COMP-4.
       01  W0ICL PIC X(1).
      *    Message data for message Y2U0009.
       01  MD0009.
           03  MDPGM PIC X(10).
           03  MDACP PIC X(10).
           03  MDFMT PIC X(10).
           03  MDACT PIC X(4).
           03  MDLBL PIC X(6).
       01  ZADFMF PIC X(10).
       01  DATA-AREA-NAME PIC X(10).
       01  ZAPGMQ PIC X(10).
       01  ZAPGRL PIC X(5).
       01  ZAMSID PIC X(7).
       01  ZAMSGF PIC X(10).
       01  ZAMSDA PIC X(132).
       01  ZAMSTP PIC X(7).
       01  ZAILE PIC X(1).
       01  ZAFSMS PIC X(1).
       01  SBBNSDA2L0-OPEN.
           COPY DDS-ALL-FORMATS OF Y2IOPEN.
      *    Open feedback area
      *
       01  W0OPN PIC X(1).
       01  W0PMT PIC X(1).
      *    PreQual Net Reg/Ord 1
       01  WORK-CONTEXT.
           03  WUGENU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 2
           03  WUGXNU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 3
           03  WUGZNU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 4
           03  WUG0NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 5
           03  WUG1NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 6
           03  WUG2NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 7
           03  WUG3NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 8
           03  WUG4NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 9
           03  WUG8NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 10
           03  WUG9NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 11
           03  WUHANU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 12
           03  WUHHNU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 13
           03  WUJ6NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 14
           03  WUJ7NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 15
           03  WUJ8NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 16
           03  WUJ9NU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 17
           03  WUKANU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 18
           03  WUKBNU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 19
           03  WUKCNU PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 20
           03  WUKDNU PIC S9(7) COMP-3.
      *
      *    Indicators
       01  INDICS.
           03  IND PIC 1(1) OCCURS 99 INDICATOR 1.
           88  C-INDICATOR-ON VALUE B'1'.
           88  C-INDICATOR-OFF VALUE B'0'.
      *
      /EJECT
      *    Parameter declarations
      /EJECT
      ***************************************************************
       LINKAGE SECTION.
      *    Return code
       01  P0RTN PIC X(7).
       01  P1PARM.
      *    Bonus Scheme (8)
           03  P1BNSSCM PIC X(8).
      *    Dealer number (Num key)
           03  P1DLRNOKEY PIC S9(5) COMP-3.
      *    Run Number
           03  P1RUNNO PIC S9(3) COMP-3.
      *    Scheme Sequence
           03  P1SCMSTS PIC X(1).
      *    Achievement Band
           03  P1ACHBND PIC X(10).
      *    No of Registrations
           03  P1NOREG PIC S9(7) COMP-3.
      *    No of Order
           03  P1KENU PIC S9(7) COMP-3.
      *    No of Registrations cancl
           03  P1EONU PIC S9(7) COMP-3.
      *    No of Order Canceled
           03  P1KFNU PIC S9(7) COMP-3.
      *    Target Value Registration
           03  P1OEVB PIC S9(5) COMP-3.
      *    Target Value Order
           03  P1OFVB PIC S9(5) COMP-3.
      *    Total Count Registration
           03  P1KGNU PIC S9(5) COMP-3.
      *    Total Count Order
           03  P1KHNU PIC S9(5) COMP-3.
      *    Achieved Pre-Qualifier
           03  P1ACPRQ PIC X(1).
      *    Achieved Pre-Qualifier 2
           03  P1ACPRQ2 PIC X(1).
      *    PreQual Reg/Ord 1
           03  P1FNNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 2
           03  P1FONU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 3
           03  P1FPNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 4
           03  P1FQNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 5
           03  P1FRNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 6
           03  P1E9NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 7
           03  P1FANU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 8
           03  P1E0NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 9
           03  P1E1NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 10
           03  P1E2NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 11
           03  P1E3NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 12
           03  P1E6NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 13
           03  P1JQNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 14
           03  P1JRNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 15
           03  P1JSNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 16
           03  P1JTNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 17
           03  P1JUNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 18
           03  P1JVNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 19
           03  P1JWNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 20
           03  P1JXNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 1
           03  P1H6NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 2
           03  P1H7NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 3
           03  P1H8NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 4
           03  P1H9NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 5
           03  P1IANU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 6
           03  P1IBNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 7
           03  P1ICNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 8
           03  P1IDNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 9
           03  P1IENU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 10
           03  P1FFNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 11
           03  P1FJNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 12
           03  P1FKNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 13
           03  P1JYNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 14
           03  P1JZNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 15
           03  P1J0NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 16
           03  P1J1NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 17
           03  P1J2NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 18
           03  P1J3NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 19
           03  P1J4NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 20
           03  P1J5NU PIC S9(7) COMP-3.
      *    PreQual Target Reg/Ord 1
           03  P1NWVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 2
           03  P1NXVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 3
           03  P1NYVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 4
           03  P1NZVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 5
           03  P1N0VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 6
           03  P1N1VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 7
           03  P1N2VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 8
           03  P1N3VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 9
           03  P1N4VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 10
           03  P1FLNU PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 11
           03  P1FMNU PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 12
           03  P1NVVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 13
           03  P1N6VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 14
           03  P1N7VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 15
           03  P1N8VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 16
           03  P1N9VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 17
           03  P1OAVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 18
           03  P1OBVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 19
           03  P1OCVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 20
           03  P1ODVB PIC S9(5) COMP-3.
      *    Dealer total bonus amount
           03  P1DLBNAMTT PIC S9(9)V9(2) COMP-3.
      *    Run Mode
           03  P1ZKCF PIC X(1).
      *    Order Band Achieved
           03  P1ZLCF PIC S9(3) COMP-3.
      *    Registration Band Ach
           03  P1ZMCF PIC S9(3) COMP-3.
      *    Manual Override Band
           03  P1ZRCF PIC S9(3) COMP-3.
      *    Overall Combined Ach Band
           03  P1ZNCF PIC S9(3) COMP-3.
      *    Manual Override Penalty
           03  P1HSNU PIC S9(3).
      *    Overall Penalty
           03  P1I0NU PIC S9(3).
      *    *USER
           03  P1USR PIC X(10).
      *    *PROGRAM
           03  P1PGM PIC X(10).
      *    *JOB
           03  P1JOB PIC X(10).
      *    Job Date (8)
           03  P1JOBDTE8 PIC S9(8) COMP-3.
      *    *Job time
           03  P1JTM PIC S9(6) COMP-3.
      ***************************************************************
       PROCEDURE DIVISION USING
             P0RTN
      *    RCD: Bonus Sls-Suggest DlrAch2 Update index
      *    I : RST Bonus Scheme (8)
      *    I : RST Dealer number (Num key)
      *    I : RST Run Number
      *    I : MAP Scheme Sequence
      *    I : MAP Achievement Band
      *    I : MAP No of Registrations
      *    I : MAP No of Order
      *    I : MAP No of Registrations cancl
      *    I : MAP No of Order Canceled
      *    I : MAP Target Value Registration
      *    I : MAP Target Value Order
      *    I : MAP Total Count Registration
      *    I : MAP Total Count Order
      *    I : MAP Achieved Pre-Qualifier
      *    I : MAP Achieved Pre-Qualifier 2
      *    I : MAP PreQual Reg/Ord 1
      *    I : MAP PreQual Reg/Ord 2
      *    I : MAP PreQual Reg/Ord 3
      *    I : MAP PreQual Reg/Ord 4
      *    I : MAP PreQual Reg/Ord 5
      *    I : MAP PreQual Reg/Ord 6
      *    I : MAP PreQual Reg/Ord 7
      *    I : MAP PreQual Reg/Ord 8
      *    I : MAP PreQual Reg/Ord 9
      *    I : MAP PreQual Reg/Ord 10
      *    I : MAP PreQual Reg/Ord 11
      *    I : MAP PreQual Reg/Ord 12
      *    I : MAP PreQual Reg/Ord 13
      *    I : MAP PreQual Reg/Ord 14
      *    I : MAP PreQual Reg/Ord 15
      *    I : MAP PreQual Reg/Ord 16
      *    I : MAP PreQual Reg/Ord 17
      *    I : MAP PreQual Reg/Ord 18
      *    I : MAP PreQual Reg/Ord 19
      *    I : MAP PreQual Reg/Ord 20
      *    I : MAP PreQual De-Reg/Ord 1
      *    I : MAP PreQual De-Reg/Ord 2
      *    I : MAP PreQual De-Reg/Ord 3
      *    I : MAP PreQual De-Reg/Ord 4
      *    I : MAP PreQual De-Reg/Ord 5
      *    I : MAP PreQual De-Reg/Ord 6
      *    I : MAP PreQual De-Reg/Ord 7
      *    I : MAP PreQual De-Reg/Ord 8
      *    I : MAP PreQual De-Reg/Ord 9
      *    I : MAP PreQual De-Reg/Ord 10
      *    I : MAP PreQual De-Reg/Ord 11
      *    I : MAP PreQual De-Reg/Ord 12
      *    I : MAP PreQual De-Reg/Ord 13
      *    I : MAP PreQual De-Reg/Ord 14
      *    I : MAP PreQual De-Reg/Ord 15
      *    I : MAP PreQual De-Reg/Ord 16
      *    I : MAP PreQual De-Reg/Ord 17
      *    I : MAP PreQual De-Reg/Ord 18
      *    I : MAP PreQual De-Reg/Ord 19
      *    I : MAP PreQual De-Reg/Ord 20
      *    I : MAP PreQual Target Reg/Ord 1
      *    I : MAP PreQual Target Reg/Ord 2
      *    I : MAP PreQual Target Reg/Ord 3
      *    I : MAP PreQual Target Reg/Ord 4
      *    I : MAP PreQual Target Reg/Ord 5
      *    I : MAP PreQual Target Reg/Ord 6
      *    I : MAP PreQual Target Reg/Ord 7
      *    I : MAP PreQual Target Reg/Ord 8
      *    I : MAP PreQual Target Reg/Ord 9
      *    I : MAP PreQual Target Reg/Ord 10
      *    I : MAP PreQual Target Reg/Ord 11
      *    I : MAP PreQual Target Reg/Ord 12
      *    I : MAP PreQual Target Reg/Ord 13
      *    I : MAP PreQual Target Reg/Ord 14
      *    I : MAP PreQual Target Reg/Ord 15
      *    I : MAP PreQual Target Reg/Ord 16
      *    I : MAP PreQual Target Reg/Ord 17
      *    I : MAP PreQual Target Reg/Ord 18
      *    I : MAP PreQual Target Reg/Ord 19
      *    I : MAP PreQual Target Reg/Ord 20
      *    I : MAP Dealer total bonus amount
      *    I : MAP Run Mode
      *    I : MAP Order Band Achieved
      *    I : MAP Registration Band Ach
      *    I : MAP Manual Override Band
      *    I : MAP Overall Combined Ach Band
      *    I : MAP Manual Override Penalty
      *    I : MAP Overall Penalty
      *    I : MAP *USER
      *    I : MAP *PROGRAM
      *    I : MAP *JOB
      *    I : MAP Job Date (8)
      *    I : MAP *Job time
      *    RCD : Bonus Sls-Suggest DlrAch2
             P1PARM
           .
      ***************************************************************
           CONTINUE.
       MAINLINE SECTION.
      *    Initialize
           PERFORM ZZINIT
      *
      *    EXC Chg bonus Suggest 2
      *    Information
           PERFORM UA1SUBR
      *    Utl @Copyright
      *    ------------------------------------------------------------
      *    COPYRIGHT
      *    (C) COPYRIGHT Renault UK Ltd. 2018
      *    Reproduction not allowed without prior permission
      *    ------------------------------------------------------------
      *    * Input parameter is maximum for CBL
      *    *PGM what called this program must by COBOL ILE
      *    Prc Ch Bonus Sls-Suggest2
      *    PreQual Net Reg/Ord 1
           SUBTRACT P1H6NU FROM P1FNNU GIVING WUGENU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 2
           SUBTRACT P1H7NU FROM P1FONU GIVING WUGXNU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 3
           SUBTRACT P1H8NU FROM P1FPNU GIVING WUGZNU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 4
           SUBTRACT P1H9NU FROM P1FQNU GIVING WUG0NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 5
           SUBTRACT P1IANU FROM P1FRNU GIVING WUG1NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 6
           SUBTRACT P1IBNU FROM P1E9NU GIVING WUG2NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 7
           SUBTRACT P1ICNU FROM P1FANU GIVING WUG3NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 8
           SUBTRACT P1IDNU FROM P1E0NU GIVING WUG4NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 9
           SUBTRACT P1IENU FROM P1E1NU GIVING WUG8NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 10
           SUBTRACT P1FFNU FROM P1E2NU GIVING WUG9NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 11
           SUBTRACT P1FJNU FROM P1E3NU GIVING WUHANU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 12
           SUBTRACT P1FKNU FROM P1E6NU GIVING WUHHNU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 13
           SUBTRACT P1JYNU FROM P1JQNU GIVING WUJ6NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 14
           SUBTRACT P1JZNU FROM P1JRNU GIVING WUJ7NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 15
           SUBTRACT P1J0NU FROM P1JSNU GIVING WUJ8NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 16
           SUBTRACT P1J1NU FROM P1JTNU GIVING WUJ9NU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 17
           SUBTRACT P1J2NU FROM P1JUNU GIVING WUKANU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 18
           SUBTRACT P1J3NU FROM P1JVNU GIVING WUKBNU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 19
           SUBTRACT P1J4NU FROM P1JWNU GIVING WUKCNU OF WORK-CONTEXT
      *    PreQual Net Reg/Ord 20
           SUBTRACT P1J5NU FROM P1JXNU GIVING WUKDNU OF WORK-CONTEXT
      *    Change Bonus Sls-Suggest - Bonus Sls-Suggest DlrAch2  *
           PERFORM SA1CHRC
      *    *Return code
           MOVE W0RTN TO P0RTN
           PERFORM ZYEXPG
      *--------------------------------------------------------------
      *    Exit program
           CONTINUE.
       AAEXIT.
           MOVE SPACES TO P0RTN
           PERFORM ZYEXPG
      *==============================================================
      /EJECT
       SA1CHRC SECTION.
      *==============================================================
      *    Change Bonus Sls-Suggest - Bonus Sls-Suggest DlrAch2  *
      *==============================================================
      *    Initialize return code
           MOVE SPACES TO W0RTN
      *    Move key fields to FBNSDLX
      *    Bonus Scheme (8)
           MOVE P1BNSSCM TO BCBNSSCM OF SBBNSDA2L0-R
      *    Dealer number (Num key)
           MOVE P1DLRNOKEY TO BCDLRNOKEY OF SBBNSDA2L0-R
      *    Run Number
           MOVE P1RUNNO TO BCRUNNO OF SBBNSDA2L0-R
      *
           READ SBBNSDA2L0 END-READ
           IF (C-NO-RECORD) THEN
               SET C-INDICATOR-ON(90) TO TRUE
           ELSE
               SET C-INDICATOR-OFF(90) TO TRUE
           END-IF
           IF (C-IO-ERR OR
               C-RECORD-LOCKED) THEN
               SET C-INDICATOR-ON(91) TO TRUE
           ELSE
               SET C-INDICATOR-OFF(91) TO TRUE
           END-IF
      *
           IF (C-INDICATOR-ON(90)) THEN
      *        Data record not found
               MOVE 'Y2U0009' TO W0RTN
      *        USER: Processing if Data record not found
      *        Create Bonus Sls-Suggest - Bonus Sls-Suggest DlrAch2  *
               PERFORM SA2CRRC
               IF (W0RTN NOT = SPACES) THEN
                   MOVE ZZPGM  OF JOB-CONTEXT TO MDPGM OF MD0009
                   MOVE 'SBBNSDA2L0' TO MDACP OF MD0009
                   MOVE 'FBNSDLX' TO MDFMT OF MD0009
                   MOVE '*CHG' TO MDACT OF MD0009
      *            Record not found label: LBL001.
                   MOVE 'LBL001' TO MDLBL OF MD0009
      *            Send message '*Record no longer on file'
      *            Message ID
                   MOVE 'Y2U0009' TO ZAMSID
      *            Message file
                   MOVE 'Y2USRMSG' TO ZAMSGF
      *            Message data
                   MOVE MD0009 TO ZAMSDA
                   PERFORM ZASNMS
                   MOVE SPACES TO MD0009
               END-IF
               GO SA1EXIT
           END-IF
      *
           IF (C-INDICATOR-ON(91)) THEN
      *        Record locked
               MOVE 'Y2U0004' TO W0RTN
      *        Send message '*Database operation error'
      *        Message ID
               MOVE 'Y2U0004' TO ZAMSID
      *        Message file
               MOVE 'Y2USRMSG' TO ZAMSGF
               PERFORM ZASNMS
               GO SA1EXIT
           END-IF
      *
      *    Move all fields to FBNSDLX
      *    Scheme Sequence
           MOVE P1SCMSTS TO BCSCMSTS OF SBBNSDA2L0-R
      *    Achievement Band
           MOVE P1ACHBND TO BCACHBND OF SBBNSDA2L0-R
      *    No of Registrations
           MOVE P1NOREG TO BCNOREG OF SBBNSDA2L0-R
      *    No of Order
           MOVE P1KENU TO BCKENU OF SBBNSDA2L0-R
      *    No of Registrations cancl
           MOVE P1EONU TO BCEONU OF SBBNSDA2L0-R
      *    No of Order Canceled
           MOVE P1KFNU TO BCKFNU OF SBBNSDA2L0-R
      *    Target Value Registration
           MOVE P1OEVB TO BCOEVB OF SBBNSDA2L0-R
      *    Target Value Order
           MOVE P1OFVB TO BCOFVB OF SBBNSDA2L0-R
      *    Total Count Registration
           MOVE P1KGNU TO BCKGNU OF SBBNSDA2L0-R
      *    Total Count Order
           MOVE P1KHNU TO BCKHNU OF SBBNSDA2L0-R
      *    Achieved Pre-Qualifier
           MOVE P1ACPRQ TO BCACPRQ OF SBBNSDA2L0-R
      *    Achieved Pre-Qualifier 2
           MOVE P1ACPRQ2 TO BCACPRQ2 OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 1
           MOVE P1FNNU TO BCFNNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 2
           MOVE P1FONU TO BCFONU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 3
           MOVE P1FPNU TO BCFPNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 4
           MOVE P1FQNU TO BCFQNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 5
           MOVE P1FRNU TO BCFRNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 6
           MOVE P1E9NU TO BCE9NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 7
           MOVE P1FANU TO BCFANU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 8
           MOVE P1E0NU TO BCE0NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 9
           MOVE P1E1NU TO BCE1NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 10
           MOVE P1E2NU TO BCE2NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 11
           MOVE P1E3NU TO BCE3NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 12
           MOVE P1E6NU TO BCE6NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 13
           MOVE P1JQNU TO BCJQNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 14
           MOVE P1JRNU TO BCJRNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 15
           MOVE P1JSNU TO BCJSNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 16
           MOVE P1JTNU TO BCJTNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 17
           MOVE P1JUNU TO BCJUNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 18
           MOVE P1JVNU TO BCJVNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 19
           MOVE P1JWNU TO BCJWNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 20
           MOVE P1JXNU TO BCJXNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 1
           MOVE P1H6NU TO BCH6NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 2
           MOVE P1H7NU TO BCH7NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 3
           MOVE P1H8NU TO BCH8NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 4
           MOVE P1H9NU TO BCH9NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 5
           MOVE P1IANU TO BCIANU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 6
           MOVE P1IBNU TO BCIBNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 7
           MOVE P1ICNU TO BCICNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 8
           MOVE P1IDNU TO BCIDNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 9
           MOVE P1IENU TO BCIENU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 10
           MOVE P1FFNU TO BCFFNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 11
           MOVE P1FJNU TO BCFJNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 12
           MOVE P1FKNU TO BCFKNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 13
           MOVE P1JYNU TO BCJYNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 14
           MOVE P1JZNU TO BCJZNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 15
           MOVE P1J0NU TO BCJ0NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 16
           MOVE P1J1NU TO BCJ1NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 17
           MOVE P1J2NU TO BCJ2NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 18
           MOVE P1J3NU TO BCJ3NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 19
           MOVE P1J4NU TO BCJ4NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 20
           MOVE P1J5NU TO BCJ5NU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 1
           MOVE P1NWVB TO BCNWVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 2
           MOVE P1NXVB TO BCNXVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 3
           MOVE P1NYVB TO BCNYVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 4
           MOVE P1NZVB TO BCNZVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 5
           MOVE P1N0VB TO BCN0VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 6
           MOVE P1N1VB TO BCN1VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 7
           MOVE P1N2VB TO BCN2VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 8
           MOVE P1N3VB TO BCN3VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 9
           MOVE P1N4VB TO BCN4VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 10
           MOVE P1FLNU TO BCFLNU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 11
           MOVE P1FMNU TO BCFMNU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 12
           MOVE P1NVVB TO BCNVVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 13
           MOVE P1N6VB TO BCN6VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 14
           MOVE P1N7VB TO BCN7VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 15
           MOVE P1N8VB TO BCN8VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 16
           MOVE P1N9VB TO BCN9VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 17
           MOVE P1OAVB TO BCOAVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 18
           MOVE P1OBVB TO BCOBVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 19
           MOVE P1OCVB TO BCOCVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 20
           MOVE P1ODVB TO BCODVB OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 1
           MOVE WUGENU OF WORK-CONTEXT TO BCGENU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 2
           MOVE WUGXNU OF WORK-CONTEXT TO BCGXNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 3
           MOVE WUGZNU OF WORK-CONTEXT TO BCGZNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 4
           MOVE WUG0NU OF WORK-CONTEXT TO BCG0NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 5
           MOVE WUG1NU OF WORK-CONTEXT TO BCG1NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 6
           MOVE WUG2NU OF WORK-CONTEXT TO BCG2NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 7
           MOVE WUG3NU OF WORK-CONTEXT TO BCG3NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 8
           MOVE WUG4NU OF WORK-CONTEXT TO BCG4NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 9
           MOVE WUG8NU OF WORK-CONTEXT TO BCG8NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 10
           MOVE WUG9NU OF WORK-CONTEXT TO BCG9NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 11
           MOVE WUHANU OF WORK-CONTEXT TO BCHANU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 12
           MOVE WUHHNU OF WORK-CONTEXT TO BCHHNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 13
           MOVE WUJ6NU OF WORK-CONTEXT TO BCJ6NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 14
           MOVE WUJ7NU OF WORK-CONTEXT TO BCJ7NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 15
           MOVE WUJ8NU OF WORK-CONTEXT TO BCJ8NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 16
           MOVE WUJ9NU OF WORK-CONTEXT TO BCJ9NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 17
           MOVE WUKANU OF WORK-CONTEXT TO BCKANU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 18
           MOVE WUKBNU OF WORK-CONTEXT TO BCKBNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 19
           MOVE WUKCNU OF WORK-CONTEXT TO BCKCNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 20
           MOVE WUKDNU OF WORK-CONTEXT TO BCKDNU OF SBBNSDA2L0-R
      *    Dealer total bonus amount
           MOVE P1DLBNAMTT TO BCDLBNAMTT OF SBBNSDA2L0-R
      *    Run Mode
           MOVE P1ZKCF TO BCZKCF OF SBBNSDA2L0-R
      *    Order Band Achieved
           MOVE P1ZLCF TO BCZLCF OF SBBNSDA2L0-R
      *    Registration Band Ach
           MOVE P1ZMCF TO BCZMCF OF SBBNSDA2L0-R
      *    Manual Override Band
           MOVE P1ZRCF TO BCZRCF OF SBBNSDA2L0-R
      *    Overall Combined Ach Band
           MOVE P1ZNCF TO BCZNCF OF SBBNSDA2L0-R
      *    Manual Override Penalty
           MOVE P1HSNU TO BCHSNU OF SBBNSDA2L0-R
      *    Overall Penalty
           MOVE P1I0NU TO BCI0NU OF SBBNSDA2L0-R
      *    *USER
           MOVE P1USR TO BCUSR OF SBBNSDA2L0-R
      *    *PROGRAM
           MOVE P1PGM TO BCPGM OF SBBNSDA2L0-R
      *    *JOB
           MOVE P1JOB TO BCJOB OF SBBNSDA2L0-R
      *    Job Date (8)
           MOVE P1JOBDTE8 TO BCJOBDTE8 OF SBBNSDA2L0-R
      *    *Job time
           MOVE P1JTM TO BCJTM OF SBBNSDA2L0-R
      *
           REWRITE SBBNSDA2L0-R END-REWRITE
           IF (NOT C-IO-OK) THEN
               SET C-INDICATOR-ON(91) TO TRUE
           ELSE
               SET C-INDICATOR-OFF(91) TO TRUE
           END-IF
           IF (C-INDICATOR-ON(91)) THEN
      *        Change error detected
               MOVE 'Y2U0004' TO W0RTN
           ELSE
      *        DBF change successful
               CONTINUE
           END-IF
      *==============================================================
           CONTINUE.
       SA1EXIT.
           EXIT.
      /EJECT
       SA2CRRC SECTION.
      *==============================================================
      *    Create Bonus Sls-Suggest - Bonus Sls-Suggest DlrAch2  *
      *==============================================================
      *    Initialize return code
           MOVE SPACES TO W0RTN
      *
      *    Move all fields to FBNSDLX
      *    Bonus Scheme (8)
           MOVE P1BNSSCM TO BCBNSSCM OF SBBNSDA2L0-R
      *    Dealer number (Num key)
           MOVE P1DLRNOKEY TO BCDLRNOKEY OF SBBNSDA2L0-R
      *    Run Number
           MOVE P1RUNNO TO BCRUNNO OF SBBNSDA2L0-R
      *    Scheme Sequence
           MOVE P1SCMSTS TO BCSCMSTS OF SBBNSDA2L0-R
      *    Achievement Band
           MOVE P1ACHBND TO BCACHBND OF SBBNSDA2L0-R
      *    No of Registrations
           MOVE P1NOREG TO BCNOREG OF SBBNSDA2L0-R
      *    No of Order
           MOVE P1KENU TO BCKENU OF SBBNSDA2L0-R
      *    No of Registrations cancl
           MOVE P1EONU TO BCEONU OF SBBNSDA2L0-R
      *    No of Order Canceled
           MOVE P1KFNU TO BCKFNU OF SBBNSDA2L0-R
      *    Target Value Registration
           MOVE P1OEVB TO BCOEVB OF SBBNSDA2L0-R
      *    Target Value Order
           MOVE P1OFVB TO BCOFVB OF SBBNSDA2L0-R
      *    Total Count Registration
           MOVE P1KGNU TO BCKGNU OF SBBNSDA2L0-R
      *    Total Count Order
           MOVE P1KHNU TO BCKHNU OF SBBNSDA2L0-R
      *    Achieved Pre-Qualifier
           MOVE P1ACPRQ TO BCACPRQ OF SBBNSDA2L0-R
      *    Achieved Pre-Qualifier 2
           MOVE P1ACPRQ2 TO BCACPRQ2 OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 1
           MOVE P1FNNU TO BCFNNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 2
           MOVE P1FONU TO BCFONU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 3
           MOVE P1FPNU TO BCFPNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 4
           MOVE P1FQNU TO BCFQNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 5
           MOVE P1FRNU TO BCFRNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 6
           MOVE P1E9NU TO BCE9NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 7
           MOVE P1FANU TO BCFANU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 8
           MOVE P1E0NU TO BCE0NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 9
           MOVE P1E1NU TO BCE1NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 10
           MOVE P1E2NU TO BCE2NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 11
           MOVE P1E3NU TO BCE3NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 12
           MOVE P1E6NU TO BCE6NU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 13
           MOVE P1JQNU TO BCJQNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 14
           MOVE P1JRNU TO BCJRNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 15
           MOVE P1JSNU TO BCJSNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 16
           MOVE P1JTNU TO BCJTNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 17
           MOVE P1JUNU TO BCJUNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 18
           MOVE P1JVNU TO BCJVNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 19
           MOVE P1JWNU TO BCJWNU OF SBBNSDA2L0-R
      *    PreQual Reg/Ord 20
           MOVE P1JXNU TO BCJXNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 1
           MOVE P1H6NU TO BCH6NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 2
           MOVE P1H7NU TO BCH7NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 3
           MOVE P1H8NU TO BCH8NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 4
           MOVE P1H9NU TO BCH9NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 5
           MOVE P1IANU TO BCIANU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 6
           MOVE P1IBNU TO BCIBNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 7
           MOVE P1ICNU TO BCICNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 8
           MOVE P1IDNU TO BCIDNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 9
           MOVE P1IENU TO BCIENU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 10
           MOVE P1FFNU TO BCFFNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 11
           MOVE P1FJNU TO BCFJNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 12
           MOVE P1FKNU TO BCFKNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 13
           MOVE P1JYNU TO BCJYNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 14
           MOVE P1JZNU TO BCJZNU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 15
           MOVE P1J0NU TO BCJ0NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 16
           MOVE P1J1NU TO BCJ1NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 17
           MOVE P1J2NU TO BCJ2NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 18
           MOVE P1J3NU TO BCJ3NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 19
           MOVE P1J4NU TO BCJ4NU OF SBBNSDA2L0-R
      *    PreQual De-Reg/Ord 20
           MOVE P1J5NU TO BCJ5NU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 1
           MOVE P1NWVB TO BCNWVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 2
           MOVE P1NXVB TO BCNXVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 3
           MOVE P1NYVB TO BCNYVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 4
           MOVE P1NZVB TO BCNZVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 5
           MOVE P1N0VB TO BCN0VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 6
           MOVE P1N1VB TO BCN1VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 7
           MOVE P1N2VB TO BCN2VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 8
           MOVE P1N3VB TO BCN3VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 9
           MOVE P1N4VB TO BCN4VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 10
           MOVE P1FLNU TO BCFLNU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 11
           MOVE P1FMNU TO BCFMNU OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 12
           MOVE P1NVVB TO BCNVVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 13
           MOVE P1N6VB TO BCN6VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 14
           MOVE P1N7VB TO BCN7VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 15
           MOVE P1N8VB TO BCN8VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 16
           MOVE P1N9VB TO BCN9VB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 17
           MOVE P1OAVB TO BCOAVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 18
           MOVE P1OBVB TO BCOBVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 19
           MOVE P1OCVB TO BCOCVB OF SBBNSDA2L0-R
      *    PreQual Target Reg/Ord 20
           MOVE P1ODVB TO BCODVB OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 1
           MOVE WUGENU OF WORK-CONTEXT TO BCGENU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 2
           MOVE WUGXNU OF WORK-CONTEXT TO BCGXNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 3
           MOVE WUGZNU OF WORK-CONTEXT TO BCGZNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 4
           MOVE WUG0NU OF WORK-CONTEXT TO BCG0NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 5
           MOVE WUG1NU OF WORK-CONTEXT TO BCG1NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 6
           MOVE WUG2NU OF WORK-CONTEXT TO BCG2NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 7
           MOVE WUG3NU OF WORK-CONTEXT TO BCG3NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 8
           MOVE WUG4NU OF WORK-CONTEXT TO BCG4NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 9
           MOVE WUG8NU OF WORK-CONTEXT TO BCG8NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 10
           MOVE WUG9NU OF WORK-CONTEXT TO BCG9NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 11
           MOVE WUHANU OF WORK-CONTEXT TO BCHANU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 12
           MOVE WUHHNU OF WORK-CONTEXT TO BCHHNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 13
           MOVE WUJ6NU OF WORK-CONTEXT TO BCJ6NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 14
           MOVE WUJ7NU OF WORK-CONTEXT TO BCJ7NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 15
           MOVE WUJ8NU OF WORK-CONTEXT TO BCJ8NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 16
           MOVE WUJ9NU OF WORK-CONTEXT TO BCJ9NU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 17
           MOVE WUKANU OF WORK-CONTEXT TO BCKANU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 18
           MOVE WUKBNU OF WORK-CONTEXT TO BCKBNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 19
           MOVE WUKCNU OF WORK-CONTEXT TO BCKCNU OF SBBNSDA2L0-R
      *    PreQual Net Reg/Ord 20
           MOVE WUKDNU OF WORK-CONTEXT TO BCKDNU OF SBBNSDA2L0-R
      *    Dealer total bonus amount
           MOVE P1DLBNAMTT TO BCDLBNAMTT OF SBBNSDA2L0-R
      *    Run Mode
           MOVE P1ZKCF TO BCZKCF OF SBBNSDA2L0-R
      *    Order Band Achieved
           MOVE P1ZLCF TO BCZLCF OF SBBNSDA2L0-R
      *    Registration Band Ach
           MOVE P1ZMCF TO BCZMCF OF SBBNSDA2L0-R
      *    Manual Override Band
           MOVE P1ZRCF TO BCZRCF OF SBBNSDA2L0-R
      *    Overall Combined Ach Band
           MOVE P1ZNCF TO BCZNCF OF SBBNSDA2L0-R
      *    Manual Override Penalty
           MOVE P1HSNU TO BCHSNU OF SBBNSDA2L0-R
      *    Overall Penalty
           MOVE P1I0NU TO BCI0NU OF SBBNSDA2L0-R
      *    *USER
           MOVE P1USR TO BCUSR OF SBBNSDA2L0-R
      *    *PROGRAM
           MOVE P1PGM TO BCPGM OF SBBNSDA2L0-R
      *    *JOB
           MOVE P1JOB TO BCJOB OF SBBNSDA2L0-R
      *    Job Date (8)
           MOVE P1JOBDTE8 TO BCJOBDTE8 OF SBBNSDA2L0-R
      *    *Job time
           MOVE P1JTM TO BCJTM OF SBBNSDA2L0-R
      *    Check for duplicate primary key
           START SBBNSDA2L0 KEY = EXTERNALLY-DESCRIBED-KEY
             FORMAT IS 'FBNSDLX'
           END-START
           IF (NOT C-NO-RECORD) THEN
               SET C-INDICATOR-ON(90) TO TRUE
           ELSE
               SET C-INDICATOR-OFF(90) TO TRUE
           END-IF
           IF (C-INDICATOR-ON(90)) THEN
               MOVE 'USR7850' TO W0RTN
      *        Send message 'Bonus Sls-Suggest DlrA EX'
      *        Message ID
               MOVE 'USR7850' TO ZAMSID
               PERFORM ZASNMS
               GO SA2EXIT
           END-IF
      *
           WRITE SBBNSDA2L0-R END-WRITE
           IF (C-IO-ERR) THEN
               SET C-INDICATOR-ON(91) TO TRUE
           ELSE
               SET C-INDICATOR-OFF(91) TO TRUE
           END-IF
      *
           IF (C-INDICATOR-ON(91)) THEN
      *        Write error detected
               MOVE 'Y2U0004' TO W0RTN
           ELSE
      *        DBF write successful
               CONTINUE
           END-IF
      *==============================================================
           CONTINUE.
       SA2EXIT.
           EXIT.
      /EJECT
       UA1SUBR SECTION.
      *==============================================================
      *    Information
      *==============================================================
      *    ------------------------------------------------------------
      *      -----
      *    Application: UKS IRN-11947
      *    Author     : Jiri Loskot, TaskForce
      *    Date       : 2018-01-17
      *    Description: Create new recor in file  -(api) RZ 2729
      *    Because exist more bonus scheme use program api not direct
      *      read file
      *    ------------------------------------------------------------
      *      -----
      *==============================================================
           CONTINUE.
       UA1EXIT.
           EXIT.
      /EJECT
       ZASNMS SECTION.
      *==============================================================
      *    Send message to program's message queue
      *==============================================================
      *    Send if first error message or not an error message
           IF (ZAMSTP NOT = SPACES OR
               ZAFSMS NOT = 'N') THEN
               IF (ZAMSTP = SPACES) THEN
      *            Signal first error message sent
                   MOVE 'N' TO ZAFSMS
               END-IF
               IF (ZAPGMQ = SPACES) THEN
                   MOVE ZZPGM OF JOB-CONTEXT TO ZAPGMQ
               END-IF
      *        If no message file specified, use default
               IF (ZAMSGF = SPACES) THEN
                   MOVE ZADFMF TO ZAMSGF
               END-IF
               MOVE 'Y' TO ZAILE
               CALL 'Y2SNMGC' USING
      *        Program queue
                 ZAPGMQ
      *        Relative queue
                 ZAPGRL
      *        Message ID
                 ZAMSID
      *        Message file
                 ZAMSGF
      *        Message data
                 ZAMSDA
      *        Message type
                 ZAMSTP
                 ZAILE
               END-CALL
           END-IF
      *    Clear all fields for default mechanism next time
      *    Program queue
           MOVE SPACES TO ZAPGMQ
      *    Relative queue
           MOVE SPACES TO ZAPGRL
      *    Message ID
           MOVE SPACES TO ZAMSID
      *    Message file
           MOVE SPACES TO ZAMSGF
      *    Message data
           MOVE SPACES TO ZAMSDA
      *    Message type
           MOVE SPACES TO ZAMSTP
      *==============================================================
           CONTINUE.
       ZAEXIT.
           EXIT.
      /EJECT
       ZXEXPG SECTION.
      *==============================================================
      *    Exit program: Normal
      *==============================================================
           PERFORM ZYEXPG
      *==============================================================
           CONTINUE.
       ZXEXIT.
           EXIT.
      /EJECT
       ZYEXPG SECTION.
      *==============================================================
      *    Exit program: Direct
      *==============================================================
           CLOSE SBBNSDA2L0
      *    Reset entry parameters as appropriate
           PERFORM ZZEXPM.
      *    Exit program
           CONTINUE.
       ZYEXPG-EXIT.
           GOBACK.
      *==============================================================
           CONTINUE.
       ZYEXIT.
           EXIT.
      /EJECT
       ZZEXPM SECTION.
      *==============================================================
      *    Return parameters from work fields
      *==============================================================
      *==============================================================
           CONTINUE.
       ZZPEXT.
           EXIT.
      /EJECT
       ZZINIT SECTION.
      *==============================================================
      *    Initialisation
      *==============================================================
           IF (W0ICL = SPACES) THEN
      *        *Initial call
               MOVE 'Y' TO W0ICL
           ELSE
               MOVE 'N' TO W0ICL
           END-IF
           MOVE SPACES TO P0RTN
           MOVE SPACES TO W0RTN
           MOVE ZEROS  TO W0RTW
           MOVE SPACES TO W0RSF
           MOVE '400' TO W0ENV
           MOVE ALL B'0' TO INDICS
           MOVE SPACES TO ZZPGM OF JOB-CONTEXT
      *    Retrieve job attributes
           CALL 'Y2RTJCR' USING
             JOB-CONTEXT
           END-CALL
      *    Setup job date/time
           MOVE ZZSD7 OF JOB-CONTEXT TO ZZJDT
           ACCEPT ZZTIME FROM TIME
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT
           MOVE 'SBA011000S' TO ZZPGM OF JOB-CONTEXT
      *    Define work field PreQual Net Reg/Ord 1
           MOVE ZERO TO WUGENU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 2
           MOVE ZERO TO WUGXNU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 3
           MOVE ZERO TO WUGZNU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 4
           MOVE ZERO TO WUG0NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 5
           MOVE ZERO TO WUG1NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 6
           MOVE ZERO TO WUG2NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 7
           MOVE ZERO TO WUG3NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 8
           MOVE ZERO TO WUG4NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 9
           MOVE ZERO TO WUG8NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 10
           MOVE ZERO TO WUG9NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 11
           MOVE ZERO TO WUHANU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 12
           MOVE ZERO TO WUHHNU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 13
           MOVE ZERO TO WUJ6NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 14
           MOVE ZERO TO WUJ7NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 15
           MOVE ZERO TO WUJ8NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 16
           MOVE ZERO TO WUJ9NU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 17
           MOVE ZERO TO WUKANU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 18
           MOVE ZERO TO WUKBNU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 19
           MOVE ZERO TO WUKCNU OF WORK-CONTEXT
      *    Define work field PreQual Net Reg/Ord 20
           MOVE ZERO TO WUKDNU OF WORK-CONTEXT
      *    Obtain default message file
           MOVE 'RAMGFLA' TO DATA-AREA-NAME
           CALL 'Y2RTDAC' USING
             DATA-AREA-NAME
             ZADFMF
           END-CALL
      *    Signal first error message outstanding
           MOVE 'Y' TO ZAFSMS
      *    Open files
           OPEN I-O SBBNSDA2L0
           ACCEPT SBBNSDA2L0-OPEN FROM OPEN-FEEDBACK-AREA FOR SBBNSDA2L0
      *    Move main file information to JOB context
           MOVE CORRESPONDING OPENFA OF SBBNSDA2L0-OPEN TO JOB-CONTEXT
           CALL 'Y2QLVNR' USING
             ZZFFL OF JOB-CONTEXT
             ZZFLB OF JOB-CONTEXT
             ZZFQL OF JOB-CONTEXT
           END-CALL
           MOVE 'Y' TO W0OPN
           MOVE 'N' TO W0PMT
      *==============================================================
           CONTINUE.
       ZZEXIT.
           EXIT.
