       PROCESS APOST GRAPHIC.
      ***************************************************************
       IDENTIFICATION DIVISION.
     H/TITLE EXC Rtv Previous Run      Execute external functio
     Z* CRTBNDCBL
     Z* CVTOPT(*DATETIME) DBGVIEW(*SOURCE) OPTIMIZE(*BASIC)
     Z* BNDDIR(YBNDDIR) ACTGRP(*CALLER)
      *
     H* SYNOPSIS :
     H*  Perform user function
     H*  As defined by action diagram
     H* Generated by CA 2E release 8.7 (1632)
     H* Function type : Execute external function  Version:  8.7
     H* Object type   : *PGM
      *
     H* Company    : Renault (UK) Applications
     H* System     : Renault (UK) Applications
     H* User name  : PRAGTSK
     H* Date       : 18/01/18 time: 10:51:09
     H* Copyright  : Renault (UK) Applications
      *
      *==============================================================
     M* MAINTENANCE   :
      *==============================================================
       PROGRAM-ID.  SBA011010S.
      /EJECT
      ***************************************************************
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER.  IBM-AS400.
       OBJECT-COMPUTER.  IBM-AS400.
       SPECIAL-NAMES.  OPEN-FEEDBACK IS OPEN-FEEDBACK-AREA,
           I-O-FEEDBACK IS I-O-FEEDBACK-AREA.
      /EJECT
      ***************************************************************
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
      *
           SELECT SBBNSDA2L3
             ASSIGN TO DATABASE-SBBNSDA2L3
             ORGANIZATION IS INDEXED
             ACCESS MODE IS DYNAMIC
             RECORD KEY IS EXTERNALLY-DESCRIBED-KEY
             FILE STATUS IS FILE-STATUS.
      *    RSQ : Bonus Sls-Suggest DlrAch2 Rtv seq des
      *
       I-O-CONTROL.
      *
      /EJECT
      ***************************************************************
       DATA DIVISION.
       FILE SECTION.
      *
      *
       FD  SBBNSDA2L3
           LABEL RECORDS ARE STANDARD.
       01  SBBNSDA2L3-R.
           COPY DDS-ALL-FORMATS OF SBBNSDA2L3.
      /EJECT
      ***************************************************************
       WORKING-STORAGE SECTION.
      *
      *    Job context
       01  JOB-CONTEXT.
           COPY DDS-ALL-FORMATS OF Y2PGDSPK.
      *    Job date/time
           03  IJBDTTM.
           05  ZZJDT PIC S9(7).
           05  ZZJDTE REDEFINES ZZJDT.
           07  ZZJCC PIC S9(1).
           07  ZZJYY PIC S9(2).
           07  ZZJMM PIC S9(2).
           07  ZZJDD PIC S9(2).
           05  ZZJTM PIC S9(6).
           05  ZZJTME REDEFINES ZZJTM.
           07  ZZJHH PIC S9(2).
           07  ZZJNN PIC S9(2).
           07  ZZJSS PIC S9(2).
           03  ZZFQL PIC X(21).
           03  ZZFLB PIC X(10).
           03  ZZFFL PIC X(10).
           03  ZZFMB PIC X(10).
           03  ZZCDB PIC X(18).
           03  ZZLDB PIC X(18).
           03  ZZTMS PIC X(26).
       01  ZZTIME.
           03  ZZHNS PIC S9(6).
           03  ZZHH PIC S9(2).
      *
       77  C-IND-OFF PIC 1(1) VALUE B'0'.
       77  C-IND-ON PIC 1(1) VALUE B'1'.
       77  W0STRNG PIC X(32766).
      *
       01  FILE-STATUS PIC X(2).
           88  C-IO-OK VALUE '00'.
           88  C-EOF VALUE '10' '46'.
           88  C-NO-MOD-SFLRCDS VALUE '12'.
           88  C-IO-ERR VALUE '21' '22' '24' '30' '34' '90' '91' '92' '9
      -     '4' '95' '9A' '9H' '9I' '9K' '9M' '9N' '9P'.
           88  C-NO-RECORD VALUE '23'.
           88  C-RECORD-LOCKED VALUE '9D'.
      *
       01  UNTIL-CONDITION PIC 1(1).
           88  C-UNTIL-FALSE VALUE B'0'.
           88  C-UNTIL-TRUE VALUE B'1'.
      *
       01  FOREVER PIC 1(1) VALUE B'1'.
           88  C-FOREVER VALUE B'1'.
      *
       01  WRK-IO-TRASH-AREA PIC X(1).
      *
       01  P2PARM.
      *    Run Number
           03  P2RUNNO PIC S9(3) COMP-3.
      *    Scheme Sequence
           03  P2SCMSTS PIC X(1).
      *    Achievement Band
           03  P2ACHBND PIC X(10).
      *    No of Registrations
           03  P2NOREG PIC S9(7) COMP-3.
      *    No of Order
           03  P2KENU PIC S9(7) COMP-3.
      *    No of Registrations cancl
           03  P2EONU PIC S9(7) COMP-3.
      *    No of Order Canceled
           03  P2KFNU PIC S9(7) COMP-3.
      *    Target Value Registration
           03  P2OEVB PIC S9(5) COMP-3.
      *    Target Value Order
           03  P2OFVB PIC S9(5) COMP-3.
      *    Total Count Registration
           03  P2KGNU PIC S9(5) COMP-3.
      *    Total Count Order
           03  P2KHNU PIC S9(5) COMP-3.
      *    Achieved Pre-Qualifier
           03  P2ACPRQ PIC X(1).
      *    Achieved Pre-Qualifier 2
           03  P2ACPRQ2 PIC X(1).
      *    PreQual Reg/Ord 1
           03  P2FNNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 2
           03  P2FONU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 3
           03  P2FPNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 4
           03  P2FQNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 5
           03  P2FRNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 6
           03  P2E9NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 7
           03  P2FANU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 8
           03  P2E0NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 9
           03  P2E1NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 10
           03  P2E2NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 11
           03  P2E3NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 12
           03  P2E6NU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 13
           03  P2JQNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 14
           03  P2JRNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 15
           03  P2JSNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 16
           03  P2JTNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 17
           03  P2JUNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 18
           03  P2JVNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 19
           03  P2JWNU PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 20
           03  P2JXNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 1
           03  P2H6NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 2
           03  P2H7NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 3
           03  P2H8NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 4
           03  P2H9NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 5
           03  P2IANU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 6
           03  P2IBNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 7
           03  P2ICNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 8
           03  P2IDNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 9
           03  P2IENU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 10
           03  P2FFNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 11
           03  P2FJNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 12
           03  P2FKNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 13
           03  P2JYNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 14
           03  P2JZNU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 15
           03  P2J0NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 16
           03  P2J1NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 17
           03  P2J2NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 18
           03  P2J3NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 19
           03  P2J4NU PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 20
           03  P2J5NU PIC S9(7) COMP-3.
      *    PreQual Target Reg/Ord 1
           03  P2NWVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 2
           03  P2NXVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 3
           03  P2NYVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 4
           03  P2NZVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 5
           03  P2N0VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 6
           03  P2N1VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 7
           03  P2N2VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 8
           03  P2N3VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 9
           03  P2N4VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 10
           03  P2FLNU PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 11
           03  P2FMNU PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 12
           03  P2NVVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 13
           03  P2N6VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 14
           03  P2N7VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 15
           03  P2N8VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 16
           03  P2N9VB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 17
           03  P2OAVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 18
           03  P2OBVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 19
           03  P2OCVB PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 20
           03  P2ODVB PIC S9(5) COMP-3.
      *    Run Mode
           03  P2ZKCF PIC X(1).
      *    Order Band Achieved
           03  P2ZLCF PIC S9(3) COMP-3.
      *    Registration Band Ach
           03  P2ZMCF PIC S9(3) COMP-3.
      *    Manual Override Band
           03  P2ZRCF PIC S9(3) COMP-3.
      *    Overall Combined Ach Band
           03  P2ZNCF PIC S9(3) COMP-3.
      *    Manual Override Penalty
           03  P2HSNU PIC S9(3).
      *    Overall Penalty
           03  P2I0NU PIC S9(3).
       01  W0RTN PIC X(7).
       01  W0RSF PIC X(1).
       01  W0ENV PIC X(3).
       01  W0RTW PIC S9(9) COMP-4.
       01  W0ICL PIC X(1).
      *    Define keylist
       01  KRSSA1.
      *    Bonus Scheme (8)
           03  BCBNSSCM PIC X(8).
      *    Dealer number (Num key)
           03  BCDLRNOKEY PIC S9(5) COMP-3.
      *    Define keylist
       01  KRSSA1-TMP.
      *    Bonus Scheme (8)
           03  BCBNSSCM PIC X(8).
      *    Dealer number (Num key)
           03  BCDLRNOKEY PIC S9(5) COMP-3.
      *
      *..............................................................
      *    Define Full Externally Described Keylist
       01  EXTSA1.
      *    Bonus Scheme (8)
           03  BCBNSSCM PIC X(8).
      *    Dealer number (Num key)
           03  BCDLRNOKEY PIC S9(5) COMP-3.
      *    Run Number
           03  BCRUNNO PIC S9(3) COMP-3.
      *..............................................................
       01  SBBNSDA2L3-OPEN.
           COPY DDS-ALL-FORMATS OF Y2IOPEN.
      *    Open feedback area
      *
       01  W0OPN PIC X(1).
       01  W0PMT PIC X(1).
      *    PreQual Net Reg/Ord 1
       01  WORK-CONTEXT.
           03  YN0001 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 2
           03  YN0002 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 3
           03  YN0003 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 4
           03  YN0004 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 5
           03  YN0005 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 6
           03  YN0006 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 7
           03  YN0007 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 8
           03  YN0008 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 9
           03  YN0009 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 10
           03  YN0010 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 11
           03  YN0011 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 12
           03  YN0012 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 13
           03  YN0013 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 14
           03  YN0014 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 15
           03  YN0015 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 16
           03  YN0016 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 17
           03  YN0017 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 18
           03  YN0018 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 19
           03  YN0019 PIC S9(7) COMP-3.
      *    PreQual Net Reg/Ord 20
           03  YN0020 PIC S9(7) COMP-3.
      *    Dealer total bonus amount
           03  YN0021 PIC S9(9)V9(2) COMP-3.
      *
      *    Indicators
       01  INDICS.
           03  IND PIC 1(1) OCCURS 99 INDICATOR 1.
           88  C-INDICATOR-ON VALUE B'1'.
           88  C-INDICATOR-OFF VALUE B'0'.
      *
      /EJECT
      *    Parameter declarations
      /EJECT
      ***************************************************************
       LINKAGE SECTION.
      *    Return code
       01  P0RTN PIC X(7).
       01  P1PARM.
      *    Bonus Scheme (8)
           03  P1BNSSCM PIC X(8).
      *    Dealer number (Num key)
           03  P1DLRNOKEY PIC S9(5) COMP-3.
      *    Run Number
       01  WP0001 PIC S9(3) COMP-3.
      *    Scheme Sequence
       01  WP0002 PIC X(1).
      *    Achievement Band
       01  WP0003 PIC X(10).
      *    No of Registrations
       01  WP0004 PIC S9(7) COMP-3.
      *    No of Order
       01  WP0005 PIC S9(7) COMP-3.
      *    No of Registrations cancl
       01  WP0006 PIC S9(7) COMP-3.
      *    No of Order Canceled
       01  WP0007 PIC S9(7) COMP-3.
      *    Target Value Registration
       01  WP0008 PIC S9(5) COMP-3.
      *    Target Value Order
       01  WP0009 PIC S9(5) COMP-3.
      *    Total Count Registration
       01  WP0010 PIC S9(5) COMP-3.
      *    Total Count Order
       01  WP0011 PIC S9(5) COMP-3.
      *    Achieved Pre-Qualifier
       01  WP0012 PIC X(1).
      *    Achieved Pre-Qualifier 2
       01  WP0013 PIC X(1).
      *    PreQual Reg/Ord 1
       01  WP0014 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 2
       01  WP0015 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 3
       01  WP0016 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 4
       01  WP0017 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 5
       01  WP0018 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 6
       01  WP0019 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 7
       01  WP0020 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 8
       01  WP0021 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 9
       01  WP0022 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 10
       01  WP0023 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 11
       01  WP0024 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 12
       01  WP0025 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 13
       01  WP0026 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 14
       01  WP0027 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 15
       01  WP0028 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 16
       01  WP0029 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 17
       01  WP0030 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 18
       01  WP0031 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 19
       01  WP0032 PIC S9(7) COMP-3.
      *    PreQual Reg/Ord 20
       01  WP0033 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 1
       01  WP0034 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 2
       01  WP0035 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 3
       01  WP0036 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 4
       01  WP0037 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 5
       01  WP0038 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 6
       01  WP0039 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 7
       01  WP0040 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 8
       01  WP0041 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 9
       01  WP0042 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 10
       01  WP0043 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 11
       01  WP0044 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 12
       01  WP0045 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 13
       01  WP0046 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 14
       01  WP0047 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 15
       01  WP0048 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 16
       01  WP0049 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 17
       01  WP0050 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 18
       01  WP0051 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 19
       01  WP0052 PIC S9(7) COMP-3.
      *    PreQual De-Reg/Ord 20
       01  WP0053 PIC S9(7) COMP-3.
      *    PreQual Target Reg/Ord 1
       01  WP0054 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 2
       01  WP0055 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 3
       01  WP0056 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 4
       01  WP0057 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 5
       01  WP0058 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 6
       01  WP0059 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 7
       01  WP0060 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 8
       01  WP0061 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 9
       01  WP0062 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 10
       01  WP0063 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 11
       01  WP0064 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 12
       01  WP0065 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 13
       01  WP0066 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 14
       01  WP0067 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 15
       01  WP0068 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 16
       01  WP0069 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 17
       01  WP0070 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 18
       01  WP0071 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 19
       01  WP0072 PIC S9(5) COMP-3.
      *    PreQual Target Reg/Ord 20
       01  WP0073 PIC S9(5) COMP-3.
      *    Run Mode
       01  WP0074 PIC X(1).
      *    Order Band Achieved
       01  WP0075 PIC S9(3) COMP-3.
      *    Registration Band Ach
       01  WP0076 PIC S9(3) COMP-3.
      *    Manual Override Band
       01  WP0077 PIC S9(3) COMP-3.
      *    Overall Combined Ach Band
       01  WP0078 PIC S9(3) COMP-3.
      *    Manual Override Penalty
       01  WP0079 PIC S9(3).
      *    Overall Penalty
       01  WP0080 PIC S9(3).
      ***************************************************************
       PROCEDURE DIVISION USING
             P0RTN
      *    KEY: Bonus Sls-Suggest DlrAch2 Rtv seq des
      *    I : RST Bonus Scheme (8)
      *    I : RST Dealer number (Num key)
      *    FLD: Bonus Sls-Suggest DlrAch2
      *    O : MAP Run Number
      *    O : MAP Scheme Sequence
      *    O : MAP Achievement Band
      *    O : MAP No of Registrations
      *    O : MAP No of Order
      *    O : MAP No of Registrations cancl
      *    O : MAP No of Order Canceled
      *    O : MAP Target Value Registration
      *    O : MAP Target Value Order
      *    O : MAP Total Count Registration
      *    O : MAP Total Count Order
      *    O : MAP Achieved Pre-Qualifier
      *    O : MAP Achieved Pre-Qualifier 2
      *    O : MAP PreQual Reg/Ord 1
      *    O : MAP PreQual Reg/Ord 2
      *    O : MAP PreQual Reg/Ord 3
      *    O : MAP PreQual Reg/Ord 4
      *    O : MAP PreQual Reg/Ord 5
      *    O : MAP PreQual Reg/Ord 6
      *    O : MAP PreQual Reg/Ord 7
      *    O : MAP PreQual Reg/Ord 8
      *    O : MAP PreQual Reg/Ord 9
      *    O : MAP PreQual Reg/Ord 10
      *    O : MAP PreQual Reg/Ord 11
      *    O : MAP PreQual Reg/Ord 12
      *    O : MAP PreQual Reg/Ord 13
      *    O : MAP PreQual Reg/Ord 14
      *    O : MAP PreQual Reg/Ord 15
      *    O : MAP PreQual Reg/Ord 16
      *    O : MAP PreQual Reg/Ord 17
      *    O : MAP PreQual Reg/Ord 18
      *    O : MAP PreQual Reg/Ord 19
      *    O : MAP PreQual Reg/Ord 20
      *    O : MAP PreQual De-Reg/Ord 1
      *    O : MAP PreQual De-Reg/Ord 2
      *    O : MAP PreQual De-Reg/Ord 3
      *    O : MAP PreQual De-Reg/Ord 4
      *    O : MAP PreQual De-Reg/Ord 5
      *    O : MAP PreQual De-Reg/Ord 6
      *    O : MAP PreQual De-Reg/Ord 7
      *    O : MAP PreQual De-Reg/Ord 8
      *    O : MAP PreQual De-Reg/Ord 9
      *    O : MAP PreQual De-Reg/Ord 10
      *    O : MAP PreQual De-Reg/Ord 11
      *    O : MAP PreQual De-Reg/Ord 12
      *    O : MAP PreQual De-Reg/Ord 13
      *    O : MAP PreQual De-Reg/Ord 14
      *    O : MAP PreQual De-Reg/Ord 15
      *    O : MAP PreQual De-Reg/Ord 16
      *    O : MAP PreQual De-Reg/Ord 17
      *    O : MAP PreQual De-Reg/Ord 18
      *    O : MAP PreQual De-Reg/Ord 19
      *    O : MAP PreQual De-Reg/Ord 20
      *    O : MAP PreQual Target Reg/Ord 1
      *    O : MAP PreQual Target Reg/Ord 2
      *    O : MAP PreQual Target Reg/Ord 3
      *    O : MAP PreQual Target Reg/Ord 4
      *    O : MAP PreQual Target Reg/Ord 5
      *    O : MAP PreQual Target Reg/Ord 6
      *    O : MAP PreQual Target Reg/Ord 7
      *    O : MAP PreQual Target Reg/Ord 8
      *    O : MAP PreQual Target Reg/Ord 9
      *    O : MAP PreQual Target Reg/Ord 10
      *    O : MAP PreQual Target Reg/Ord 11
      *    O : MAP PreQual Target Reg/Ord 12
      *    O : MAP PreQual Target Reg/Ord 13
      *    O : MAP PreQual Target Reg/Ord 14
      *    O : MAP PreQual Target Reg/Ord 15
      *    O : MAP PreQual Target Reg/Ord 16
      *    O : MAP PreQual Target Reg/Ord 17
      *    O : MAP PreQual Target Reg/Ord 18
      *    O : MAP PreQual Target Reg/Ord 19
      *    O : MAP PreQual Target Reg/Ord 20
      *    O : MAP Run Mode
      *    O : MAP Order Band Achieved
      *    O : MAP Registration Band Ach
      *    O : MAP Manual Override Band
      *    O : MAP Overall Combined Ach Band
      *    O : MAP Manual Override Penalty
      *    O : MAP Overall Penalty
      *    KEY : Bonus Sls-Suggest DlrAch2
             P1PARM
      *    Run Number
             WP0001
      *    Scheme Sequence
             WP0002
      *    Achievement Band
             WP0003
      *    No of Registrations
             WP0004
      *    No of Order
             WP0005
      *    No of Registrations cancl
             WP0006
      *    No of Order Canceled
             WP0007
      *    Target Value Registration
             WP0008
      *    Target Value Order
             WP0009
      *    Total Count Registration
             WP0010
      *    Total Count Order
             WP0011
      *    Achieved Pre-Qualifier
             WP0012
      *    Achieved Pre-Qualifier 2
             WP0013
      *    PreQual Reg/Ord 1
             WP0014
      *    PreQual Reg/Ord 2
             WP0015
      *    PreQual Reg/Ord 3
             WP0016
      *    PreQual Reg/Ord 4
             WP0017
      *    PreQual Reg/Ord 5
             WP0018
      *    PreQual Reg/Ord 6
             WP0019
      *    PreQual Reg/Ord 7
             WP0020
      *    PreQual Reg/Ord 8
             WP0021
      *    PreQual Reg/Ord 9
             WP0022
      *    PreQual Reg/Ord 10
             WP0023
      *    PreQual Reg/Ord 11
             WP0024
      *    PreQual Reg/Ord 12
             WP0025
      *    PreQual Reg/Ord 13
             WP0026
      *    PreQual Reg/Ord 14
             WP0027
      *    PreQual Reg/Ord 15
             WP0028
      *    PreQual Reg/Ord 16
             WP0029
      *    PreQual Reg/Ord 17
             WP0030
      *    PreQual Reg/Ord 18
             WP0031
      *    PreQual Reg/Ord 19
             WP0032
      *    PreQual Reg/Ord 20
             WP0033
      *    PreQual De-Reg/Ord 1
             WP0034
      *    PreQual De-Reg/Ord 2
             WP0035
      *    PreQual De-Reg/Ord 3
             WP0036
      *    PreQual De-Reg/Ord 4
             WP0037
      *    PreQual De-Reg/Ord 5
             WP0038
      *    PreQual De-Reg/Ord 6
             WP0039
      *    PreQual De-Reg/Ord 7
             WP0040
      *    PreQual De-Reg/Ord 8
             WP0041
      *    PreQual De-Reg/Ord 9
             WP0042
      *    PreQual De-Reg/Ord 10
             WP0043
      *    PreQual De-Reg/Ord 11
             WP0044
      *    PreQual De-Reg/Ord 12
             WP0045
      *    PreQual De-Reg/Ord 13
             WP0046
      *    PreQual De-Reg/Ord 14
             WP0047
      *    PreQual De-Reg/Ord 15
             WP0048
      *    PreQual De-Reg/Ord 16
             WP0049
      *    PreQual De-Reg/Ord 17
             WP0050
      *    PreQual De-Reg/Ord 18
             WP0051
      *    PreQual De-Reg/Ord 19
             WP0052
      *    PreQual De-Reg/Ord 20
             WP0053
      *    PreQual Target Reg/Ord 1
             WP0054
      *    PreQual Target Reg/Ord 2
             WP0055
      *    PreQual Target Reg/Ord 3
             WP0056
      *    PreQual Target Reg/Ord 4
             WP0057
      *    PreQual Target Reg/Ord 5
             WP0058
      *    PreQual Target Reg/Ord 6
             WP0059
      *    PreQual Target Reg/Ord 7
             WP0060
      *    PreQual Target Reg/Ord 8
             WP0061
      *    PreQual Target Reg/Ord 9
             WP0062
      *    PreQual Target Reg/Ord 10
             WP0063
      *    PreQual Target Reg/Ord 11
             WP0064
      *    PreQual Target Reg/Ord 12
             WP0065
      *    PreQual Target Reg/Ord 13
             WP0066
      *    PreQual Target Reg/Ord 14
             WP0067
      *    PreQual Target Reg/Ord 15
             WP0068
      *    PreQual Target Reg/Ord 16
             WP0069
      *    PreQual Target Reg/Ord 17
             WP0070
      *    PreQual Target Reg/Ord 18
             WP0071
      *    PreQual Target Reg/Ord 19
             WP0072
      *    PreQual Target Reg/Ord 20
             WP0073
      *    Run Mode
             WP0074
      *    Order Band Achieved
             WP0075
      *    Registration Band Ach
             WP0076
      *    Manual Override Band
             WP0077
      *    Overall Combined Ach Band
             WP0078
      *    Manual Override Penalty
             WP0079
      *    Overall Penalty
             WP0080
           .
      *    Initialise work fields from entry parameters
           MOVE ZEROS TO P2RUNNO
           MOVE SPACES TO P2SCMSTS
           MOVE SPACES TO P2ACHBND
           MOVE ZEROS TO P2NOREG
           MOVE ZEROS TO P2KENU
           MOVE ZEROS TO P2EONU
           MOVE ZEROS TO P2KFNU
           MOVE ZEROS TO P2OEVB
           MOVE ZEROS TO P2OFVB
           MOVE ZEROS TO P2KGNU
           MOVE ZEROS TO P2KHNU
           MOVE SPACES TO P2ACPRQ
           MOVE SPACES TO P2ACPRQ2
           MOVE ZEROS TO P2FNNU
           MOVE ZEROS TO P2FONU
           MOVE ZEROS TO P2FPNU
           MOVE ZEROS TO P2FQNU
           MOVE ZEROS TO P2FRNU
           MOVE ZEROS TO P2E9NU
           MOVE ZEROS TO P2FANU
           MOVE ZEROS TO P2E0NU
           MOVE ZEROS TO P2E1NU
           MOVE ZEROS TO P2E2NU
           MOVE ZEROS TO P2E3NU
           MOVE ZEROS TO P2E6NU
           MOVE ZEROS TO P2JQNU
           MOVE ZEROS TO P2JRNU
           MOVE ZEROS TO P2JSNU
           MOVE ZEROS TO P2JTNU
           MOVE ZEROS TO P2JUNU
           MOVE ZEROS TO P2JVNU
           MOVE ZEROS TO P2JWNU
           MOVE ZEROS TO P2JXNU
           MOVE ZEROS TO P2H6NU
           MOVE ZEROS TO P2H7NU
           MOVE ZEROS TO P2H8NU
           MOVE ZEROS TO P2H9NU
           MOVE ZEROS TO P2IANU
           MOVE ZEROS TO P2IBNU
           MOVE ZEROS TO P2ICNU
           MOVE ZEROS TO P2IDNU
           MOVE ZEROS TO P2IENU
           MOVE ZEROS TO P2FFNU
           MOVE ZEROS TO P2FJNU
           MOVE ZEROS TO P2FKNU
           MOVE ZEROS TO P2JYNU
           MOVE ZEROS TO P2JZNU
           MOVE ZEROS TO P2J0NU
           MOVE ZEROS TO P2J1NU
           MOVE ZEROS TO P2J2NU
           MOVE ZEROS TO P2J3NU
           MOVE ZEROS TO P2J4NU
           MOVE ZEROS TO P2J5NU
           MOVE ZEROS TO P2NWVB
           MOVE ZEROS TO P2NXVB
           MOVE ZEROS TO P2NYVB
           MOVE ZEROS TO P2NZVB
           MOVE ZEROS TO P2N0VB
           MOVE ZEROS TO P2N1VB
           MOVE ZEROS TO P2N2VB
           MOVE ZEROS TO P2N3VB
           MOVE ZEROS TO P2N4VB
           MOVE ZEROS TO P2FLNU
           MOVE ZEROS TO P2FMNU
           MOVE ZEROS TO P2NVVB
           MOVE ZEROS TO P2N6VB
           MOVE ZEROS TO P2N7VB
           MOVE ZEROS TO P2N8VB
           MOVE ZEROS TO P2N9VB
           MOVE ZEROS TO P2OAVB
           MOVE ZEROS TO P2OBVB
           MOVE ZEROS TO P2OCVB
           MOVE ZEROS TO P2ODVB
           MOVE SPACES TO P2ZKCF
           MOVE ZEROS TO P2ZLCF
           MOVE ZEROS TO P2ZMCF
           MOVE ZEROS TO P2ZRCF
           MOVE ZEROS TO P2ZNCF
           MOVE ZEROS TO P2HSNU
           MOVE ZEROS TO P2I0NU
      ***************************************************************
           CONTINUE.
       MAINLINE SECTION.
      *    Initialize
           PERFORM ZZINIT
      *
      *    EXC Rtv Previous Run
      *    Information
           PERFORM UA1SUBR
      *    Utl @Copyright
      *    ------------------------------------------------------------
      *    COPYRIGHT
      *    (C) COPYRIGHT Renault UK Ltd. 2018
      *    Reproduction not allowed without prior permission
      *    ------------------------------------------------------------
      *    *This RTV program is maximum parameter for CBL need COBOL ILE
      *    * PGM what called this program must by COBOL ILE
      *    Rtv last record - Bonus Sls-Suggest DlrAch2  *
           PERFORM SA1RVGN
      *    *Return code
           MOVE W0RTN TO P0RTN
           PERFORM ZYEXPG
      *--------------------------------------------------------------
      *    Exit program
           CONTINUE.
       AAEXIT.
           MOVE SPACES TO P0RTN
           PERFORM ZYEXPG
      *==============================================================
      /EJECT
       SA1RVGN SECTION.
      *==============================================================
      *    Rtv last record - Bonus Sls-Suggest DlrAch2  *
      *==============================================================
      *    Initialize return code
           MOVE SPACES TO W0RTN
      *    Setup key
      *    Bonus Scheme (8)
           MOVE P1BNSSCM TO BCBNSSCM OF KRSSA1
      *    Dealer number (Num key)
           MOVE P1DLRNOKEY TO BCDLRNOKEY OF KRSSA1
      *    Initialise Full Externally Described Keylist
      *    Bonus Scheme (8)
           MOVE LOW-VALUES TO BCBNSSCM OF EXTSA1
      *    Dealer number (Num key)
           MOVE -99999 TO BCDLRNOKEY OF EXTSA1
      *    Run Number
           MOVE 999 TO BCRUNNO OF EXTSA1
           MOVE CORRESPONDING
             EXTSA1 TO
             FBNSDL9 OF SBBNSDA2L3-R
           MOVE CORRESPONDING
             KRSSA1 TO
             FBNSDL9 OF SBBNSDA2L3-R
           START SBBNSDA2L3 KEY NOT < EXTERNALLY-DESCRIBED-KEY
             FORMAT IS 'FBNSDL9'
           END-START
           IF (C-IO-ERR) THEN
               STOP RUN
           END-IF
           SET C-INDICATOR-OFF(90) TO TRUE
           READ SBBNSDA2L3 NEXT
             FORMAT IS 'FBNSDL9'
           END-READ
           IF (C-EOF) THEN
               SET C-INDICATOR-ON(90) TO TRUE
           ELSE
               IF (C-IO-ERR) THEN
                   STOP RUN
               ELSE
                   MOVE CORRESPONDING
                     FBNSDL9 OF SBBNSDA2L3-R TO
                     EXTSA1
                   MOVE EXTSA1 TO KRSSA1-TMP
                   IF (KRSSA1 NOT = KRSSA1-TMP) THEN
                       SET C-INDICATOR-ON(90) TO TRUE
                   END-IF
               END-IF
           END-IF
      *    Initialise Full Externally Described Keylist
      *    Bonus Scheme (8)
           MOVE LOW-VALUES TO BCBNSSCM OF EXTSA1
      *    Dealer number (Num key)
           MOVE -99999 TO BCDLRNOKEY OF EXTSA1
      *    Run Number
           MOVE 999 TO BCRUNNO OF EXTSA1
           IF (C-INDICATOR-ON(90)) THEN
      *        Data record not found
               MOVE 'USR7849' TO W0RTN
      *        USER: Processing if Data record not found
      *        PAR = CON By name
      *        Scheme Sequence
               MOVE SPACES TO P2SCMSTS
      *        Achievement Band
               MOVE SPACES TO P2ACHBND
      *        No of Registrations
               MOVE ZEROS TO P2NOREG
      *        No of Order
               MOVE ZEROS TO P2KENU
      *        No of Registrations cancl
               MOVE ZEROS TO P2EONU
      *        No of Order Canceled
               MOVE ZEROS TO P2KFNU
      *        Target Value Registration
               MOVE ZEROS TO P2OEVB
      *        Target Value Order
               MOVE ZEROS TO P2OFVB
      *        Total Count Registration
               MOVE ZEROS TO P2KGNU
      *        Total Count Order
               MOVE ZEROS TO P2KHNU
      *        Achieved Pre-Qualifier
               MOVE SPACES TO P2ACPRQ
      *        Achieved Pre-Qualifier 2
               MOVE SPACES TO P2ACPRQ2
      *        PreQual Reg/Ord 1
               MOVE ZEROS TO P2FNNU
      *        PreQual Reg/Ord 2
               MOVE ZEROS TO P2FONU
      *        PreQual Reg/Ord 3
               MOVE ZEROS TO P2FPNU
      *        PreQual Reg/Ord 4
               MOVE ZEROS TO P2FQNU
      *        PreQual Reg/Ord 5
               MOVE ZEROS TO P2FRNU
      *        PreQual Reg/Ord 6
               MOVE ZEROS TO P2E9NU
      *        PreQual Reg/Ord 7
               MOVE ZEROS TO P2FANU
      *        PreQual Reg/Ord 8
               MOVE ZEROS TO P2E0NU
      *        PreQual Reg/Ord 9
               MOVE ZEROS TO P2E1NU
      *        PreQual Reg/Ord 10
               MOVE ZEROS TO P2E2NU
      *        PreQual Reg/Ord 11
               MOVE ZEROS TO P2E3NU
      *        PreQual Reg/Ord 12
               MOVE ZEROS TO P2E6NU
      *        PreQual Reg/Ord 13
               MOVE ZEROS TO P2JQNU
      *        PreQual Reg/Ord 14
               MOVE ZEROS TO P2JRNU
      *        PreQual Reg/Ord 15
               MOVE ZEROS TO P2JSNU
      *        PreQual Reg/Ord 16
               MOVE ZEROS TO P2JTNU
      *        PreQual Reg/Ord 17
               MOVE ZEROS TO P2JUNU
      *        PreQual Reg/Ord 18
               MOVE ZEROS TO P2JVNU
      *        PreQual Reg/Ord 19
               MOVE ZEROS TO P2JWNU
      *        PreQual Reg/Ord 20
               MOVE ZEROS TO P2JXNU
      *        PreQual De-Reg/Ord 1
               MOVE ZEROS TO P2H6NU
      *        PreQual De-Reg/Ord 2
               MOVE ZEROS TO P2H7NU
      *        PreQual De-Reg/Ord 3
               MOVE ZEROS TO P2H8NU
      *        PreQual De-Reg/Ord 4
               MOVE ZEROS TO P2H9NU
      *        PreQual De-Reg/Ord 5
               MOVE ZEROS TO P2IANU
      *        PreQual De-Reg/Ord 6
               MOVE ZEROS TO P2IBNU
      *        PreQual De-Reg/Ord 7
               MOVE ZEROS TO P2ICNU
      *        PreQual De-Reg/Ord 8
               MOVE ZEROS TO P2IDNU
      *        PreQual De-Reg/Ord 9
               MOVE ZEROS TO P2IENU
      *        PreQual De-Reg/Ord 10
               MOVE ZEROS TO P2FFNU
      *        PreQual De-Reg/Ord 11
               MOVE ZEROS TO P2FJNU
      *        PreQual De-Reg/Ord 12
               MOVE ZEROS TO P2FKNU
      *        PreQual De-Reg/Ord 13
               MOVE ZEROS TO P2JYNU
      *        PreQual De-Reg/Ord 14
               MOVE ZEROS TO P2JZNU
      *        PreQual De-Reg/Ord 15
               MOVE ZEROS TO P2J0NU
      *        PreQual De-Reg/Ord 16
               MOVE ZEROS TO P2J1NU
      *        PreQual De-Reg/Ord 17
               MOVE ZEROS TO P2J2NU
      *        PreQual De-Reg/Ord 18
               MOVE ZEROS TO P2J3NU
      *        PreQual De-Reg/Ord 19
               MOVE ZEROS TO P2J4NU
      *        PreQual De-Reg/Ord 20
               MOVE ZEROS TO P2J5NU
      *        PreQual Target Reg/Ord 1
               MOVE ZEROS TO P2NWVB
      *        PreQual Target Reg/Ord 2
               MOVE ZEROS TO P2NXVB
      *        PreQual Target Reg/Ord 3
               MOVE ZEROS TO P2NYVB
      *        PreQual Target Reg/Ord 4
               MOVE ZEROS TO P2NZVB
      *        PreQual Target Reg/Ord 5
               MOVE ZEROS TO P2N0VB
      *        PreQual Target Reg/Ord 6
               MOVE ZEROS TO P2N1VB
      *        PreQual Target Reg/Ord 7
               MOVE ZEROS TO P2N2VB
      *        PreQual Target Reg/Ord 8
               MOVE ZEROS TO P2N3VB
      *        PreQual Target Reg/Ord 9
               MOVE ZEROS TO P2N4VB
      *        PreQual Target Reg/Ord 10
               MOVE ZEROS TO P2FLNU
      *        PreQual Target Reg/Ord 11
               MOVE ZEROS TO P2FMNU
      *        PreQual Target Reg/Ord 12
               MOVE ZEROS TO P2NVVB
      *        PreQual Target Reg/Ord 13
               MOVE ZEROS TO P2N6VB
      *        PreQual Target Reg/Ord 14
               MOVE ZEROS TO P2N7VB
      *        PreQual Target Reg/Ord 15
               MOVE ZEROS TO P2N8VB
      *        PreQual Target Reg/Ord 16
               MOVE ZEROS TO P2N9VB
      *        PreQual Target Reg/Ord 17
               MOVE ZEROS TO P2OAVB
      *        PreQual Target Reg/Ord 18
               MOVE ZEROS TO P2OBVB
      *        PreQual Target Reg/Ord 19
               MOVE ZEROS TO P2OCVB
      *        PreQual Target Reg/Ord 20
               MOVE ZEROS TO P2ODVB
      *        Run Mode
               MOVE SPACES TO P2ZKCF
      *        Order Band Achieved
               MOVE ZEROS TO P2ZLCF
      *        Registration Band Ach
               MOVE ZEROS TO P2ZMCF
      *        Manual Override Band
               MOVE ZEROS TO P2ZRCF
      *        Overall Combined Ach Band
               MOVE ZEROS TO P2ZNCF
      *        Manual Override Penalty
               MOVE ZEROS TO P2HSNU
      *        Overall Penalty
               MOVE ZEROS TO P2I0NU
      *        U:Number (3.0)
               MOVE ZEROS TO P2RUNNO
      *        *Return code
               MOVE 'Y2U0005' TO W0RTN
      *        U:Number (3.0)
               MOVE ZEROS TO P2RUNNO
               GO SA1EXIT
           END-IF
      *
           PERFORM UNTIL NOT (C-INDICATOR-OFF(90))
      *        USER: Process Data record
      *        PAR = DB1 By name
      *        Scheme Sequence
               MOVE BCSCMSTS OF FBNSDL9 OF SBBNSDA2L3-R TO P2SCMSTS
      *        Achievement Band
               MOVE BCACHBND OF FBNSDL9 OF SBBNSDA2L3-R TO P2ACHBND
      *        No of Registrations
               MOVE BCNOREG OF FBNSDL9 OF SBBNSDA2L3-R TO P2NOREG
      *        No of Order
               MOVE BCKENU OF FBNSDL9 OF SBBNSDA2L3-R TO P2KENU
      *        No of Registrations cancl
               MOVE BCEONU OF FBNSDL9 OF SBBNSDA2L3-R TO P2EONU
      *        No of Order Canceled
               MOVE BCKFNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2KFNU
      *        Target Value Registration
               MOVE BCOEVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2OEVB
      *        Target Value Order
               MOVE BCOFVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2OFVB
      *        Total Count Registration
               MOVE BCKGNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2KGNU
      *        Total Count Order
               MOVE BCKHNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2KHNU
      *        Achieved Pre-Qualifier
               MOVE BCACPRQ OF FBNSDL9 OF SBBNSDA2L3-R TO P2ACPRQ
      *        Achieved Pre-Qualifier 2
               MOVE BCACPRQ2 OF FBNSDL9 OF SBBNSDA2L3-R TO P2ACPRQ2
      *        PreQual Reg/Ord 1
               MOVE BCFNNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FNNU
      *        PreQual Reg/Ord 2
               MOVE BCFONU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FONU
      *        PreQual Reg/Ord 3
               MOVE BCFPNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FPNU
      *        PreQual Reg/Ord 4
               MOVE BCFQNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FQNU
      *        PreQual Reg/Ord 5
               MOVE BCFRNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FRNU
      *        PreQual Reg/Ord 6
               MOVE BCE9NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E9NU
      *        PreQual Reg/Ord 7
               MOVE BCFANU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FANU
      *        PreQual Reg/Ord 8
               MOVE BCE0NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E0NU
      *        PreQual Reg/Ord 9
               MOVE BCE1NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E1NU
      *        PreQual Reg/Ord 10
               MOVE BCE2NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E2NU
      *        PreQual Reg/Ord 11
               MOVE BCE3NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E3NU
      *        PreQual Reg/Ord 12
               MOVE BCE6NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2E6NU
      *        PreQual Reg/Ord 13
               MOVE BCJQNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JQNU
      *        PreQual Reg/Ord 14
               MOVE BCJRNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JRNU
      *        PreQual Reg/Ord 15
               MOVE BCJSNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JSNU
      *        PreQual Reg/Ord 16
               MOVE BCJTNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JTNU
      *        PreQual Reg/Ord 17
               MOVE BCJUNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JUNU
      *        PreQual Reg/Ord 18
               MOVE BCJVNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JVNU
      *        PreQual Reg/Ord 19
               MOVE BCJWNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JWNU
      *        PreQual Reg/Ord 20
               MOVE BCJXNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JXNU
      *        PreQual De-Reg/Ord 1
               MOVE BCH6NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2H6NU
      *        PreQual De-Reg/Ord 2
               MOVE BCH7NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2H7NU
      *        PreQual De-Reg/Ord 3
               MOVE BCH8NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2H8NU
      *        PreQual De-Reg/Ord 4
               MOVE BCH9NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2H9NU
      *        PreQual De-Reg/Ord 5
               MOVE BCIANU OF FBNSDL9 OF SBBNSDA2L3-R TO P2IANU
      *        PreQual De-Reg/Ord 6
               MOVE BCIBNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2IBNU
      *        PreQual De-Reg/Ord 7
               MOVE BCICNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2ICNU
      *        PreQual De-Reg/Ord 8
               MOVE BCIDNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2IDNU
      *        PreQual De-Reg/Ord 9
               MOVE BCIENU OF FBNSDL9 OF SBBNSDA2L3-R TO P2IENU
      *        PreQual De-Reg/Ord 10
               MOVE BCFFNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FFNU
      *        PreQual De-Reg/Ord 11
               MOVE BCFJNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FJNU
      *        PreQual De-Reg/Ord 12
               MOVE BCFKNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FKNU
      *        PreQual De-Reg/Ord 13
               MOVE BCJYNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JYNU
      *        PreQual De-Reg/Ord 14
               MOVE BCJZNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2JZNU
      *        PreQual De-Reg/Ord 15
               MOVE BCJ0NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J0NU
      *        PreQual De-Reg/Ord 16
               MOVE BCJ1NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J1NU
      *        PreQual De-Reg/Ord 17
               MOVE BCJ2NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J2NU
      *        PreQual De-Reg/Ord 18
               MOVE BCJ3NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J3NU
      *        PreQual De-Reg/Ord 19
               MOVE BCJ4NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J4NU
      *        PreQual De-Reg/Ord 20
               MOVE BCJ5NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2J5NU
      *        PreQual Target Reg/Ord 1
               MOVE BCNWVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2NWVB
      *        PreQual Target Reg/Ord 2
               MOVE BCNXVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2NXVB
      *        PreQual Target Reg/Ord 3
               MOVE BCNYVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2NYVB
      *        PreQual Target Reg/Ord 4
               MOVE BCNZVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2NZVB
      *        PreQual Target Reg/Ord 5
               MOVE BCN0VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N0VB
      *        PreQual Target Reg/Ord 6
               MOVE BCN1VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N1VB
      *        PreQual Target Reg/Ord 7
               MOVE BCN2VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N2VB
      *        PreQual Target Reg/Ord 8
               MOVE BCN3VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N3VB
      *        PreQual Target Reg/Ord 9
               MOVE BCN4VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N4VB
      *        PreQual Target Reg/Ord 10
               MOVE BCFLNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FLNU
      *        PreQual Target Reg/Ord 11
               MOVE BCFMNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2FMNU
      *        PreQual Target Reg/Ord 12
               MOVE BCNVVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2NVVB
      *        PreQual Target Reg/Ord 13
               MOVE BCN6VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N6VB
      *        PreQual Target Reg/Ord 14
               MOVE BCN7VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N7VB
      *        PreQual Target Reg/Ord 15
               MOVE BCN8VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N8VB
      *        PreQual Target Reg/Ord 16
               MOVE BCN9VB OF FBNSDL9 OF SBBNSDA2L3-R TO P2N9VB
      *        PreQual Target Reg/Ord 17
               MOVE BCOAVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2OAVB
      *        PreQual Target Reg/Ord 18
               MOVE BCOBVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2OBVB
      *        PreQual Target Reg/Ord 19
               MOVE BCOCVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2OCVB
      *        PreQual Target Reg/Ord 20
               MOVE BCODVB OF FBNSDL9 OF SBBNSDA2L3-R TO P2ODVB
      *        Run Mode
               MOVE BCZKCF OF FBNSDL9 OF SBBNSDA2L3-R TO P2ZKCF
      *        Order Band Achieved
               MOVE BCZLCF OF FBNSDL9 OF SBBNSDA2L3-R TO P2ZLCF
      *        Registration Band Ach
               MOVE BCZMCF OF FBNSDL9 OF SBBNSDA2L3-R TO P2ZMCF
      *        Manual Override Band
               MOVE BCZRCF OF FBNSDL9 OF SBBNSDA2L3-R TO P2ZRCF
      *        Overall Combined Ach Band
               MOVE BCZNCF OF FBNSDL9 OF SBBNSDA2L3-R TO P2ZNCF
      *        Manual Override Penalty
               MOVE BCHSNU OF FBNSDL9 OF SBBNSDA2L3-R TO P2HSNU
      *        Overall Penalty
               MOVE BCI0NU OF FBNSDL9 OF SBBNSDA2L3-R TO P2I0NU
      *        U:Number (3.0)
               MOVE BCRUNNO OF FBNSDL9 OF SBBNSDA2L3-R TO P2RUNNO
      *        *QUIT
               GO SA1EXIT
               SET C-INDICATOR-OFF(90) TO TRUE
               READ SBBNSDA2L3 NEXT
                 FORMAT IS 'FBNSDL9'
               END-READ
               IF (C-EOF) THEN
                   SET C-INDICATOR-ON(90) TO TRUE
               ELSE
                   IF (C-IO-ERR) THEN
                       STOP RUN
                   ELSE
                       MOVE CORRESPONDING
                         FBNSDL9 OF SBBNSDA2L3-R TO
                         EXTSA1
                       MOVE EXTSA1 TO KRSSA1-TMP
                       IF (KRSSA1 NOT = KRSSA1-TMP) THEN
                           SET C-INDICATOR-ON(90) TO TRUE
                       END-IF
                   END-IF
               END-IF
      *        Initialise Full Externally Described Keylist
      *        Bonus Scheme (8)
               MOVE LOW-VALUES TO BCBNSSCM OF EXTSA1
      *        Dealer number (Num key)
               MOVE -99999 TO BCDLRNOKEY OF EXTSA1
      *        Run Number
               MOVE 999 TO BCRUNNO OF EXTSA1
           END-PERFORM
      *==============================================================
           CONTINUE.
       SA1EXIT.
           EXIT.
      /EJECT
       UA1SUBR SECTION.
      *==============================================================
      *    Information
      *==============================================================
      *    ------------------------------------------------------------
      *      -----
      *    Application: UKS IRN-11947
      *    Author     : Jiri Loskot, TaskForce
      *    Date       : 2018-01-17
      *    Description: Retrive last record (last seqence numder) in
      *      RZ 2729
      *    ------------------------------------------------------------
      *      -----
      *==============================================================
           CONTINUE.
       UA1EXIT.
           EXIT.
      /EJECT
       ZXEXPG SECTION.
      *==============================================================
      *    Exit program: Normal
      *==============================================================
           PERFORM ZYEXPG
      *==============================================================
           CONTINUE.
       ZXEXIT.
           EXIT.
      /EJECT
       ZYEXPG SECTION.
      *==============================================================
      *    Exit program: Direct
      *==============================================================
           CLOSE SBBNSDA2L3
      *    Reset entry parameters as appropriate
           PERFORM ZZEXPM.
      *    Exit program
           CONTINUE.
       ZYEXPG-EXIT.
           GOBACK.
      *==============================================================
           CONTINUE.
       ZYEXIT.
           EXIT.
      /EJECT
       ZZEXPM SECTION.
      *==============================================================
      *    Return parameters from work fields
      *==============================================================
           MOVE P2RUNNO TO WP0001
           MOVE P2SCMSTS TO WP0002
           MOVE P2ACHBND TO WP0003
           MOVE P2NOREG TO WP0004
           MOVE P2KENU TO WP0005
           MOVE P2EONU TO WP0006
           MOVE P2KFNU TO WP0007
           MOVE P2OEVB TO WP0008
           MOVE P2OFVB TO WP0009
           MOVE P2KGNU TO WP0010
           MOVE P2KHNU TO WP0011
           MOVE P2ACPRQ TO WP0012
           MOVE P2ACPRQ2 TO WP0013
           MOVE P2FNNU TO WP0014
           MOVE P2FONU TO WP0015
           MOVE P2FPNU TO WP0016
           MOVE P2FQNU TO WP0017
           MOVE P2FRNU TO WP0018
           MOVE P2E9NU TO WP0019
           MOVE P2FANU TO WP0020
           MOVE P2E0NU TO WP0021
           MOVE P2E1NU TO WP0022
           MOVE P2E2NU TO WP0023
           MOVE P2E3NU TO WP0024
           MOVE P2E6NU TO WP0025
           MOVE P2JQNU TO WP0026
           MOVE P2JRNU TO WP0027
           MOVE P2JSNU TO WP0028
           MOVE P2JTNU TO WP0029
           MOVE P2JUNU TO WP0030
           MOVE P2JVNU TO WP0031
           MOVE P2JWNU TO WP0032
           MOVE P2JXNU TO WP0033
           MOVE P2H6NU TO WP0034
           MOVE P2H7NU TO WP0035
           MOVE P2H8NU TO WP0036
           MOVE P2H9NU TO WP0037
           MOVE P2IANU TO WP0038
           MOVE P2IBNU TO WP0039
           MOVE P2ICNU TO WP0040
           MOVE P2IDNU TO WP0041
           MOVE P2IENU TO WP0042
           MOVE P2FFNU TO WP0043
           MOVE P2FJNU TO WP0044
           MOVE P2FKNU TO WP0045
           MOVE P2JYNU TO WP0046
           MOVE P2JZNU TO WP0047
           MOVE P2J0NU TO WP0048
           MOVE P2J1NU TO WP0049
           MOVE P2J2NU TO WP0050
           MOVE P2J3NU TO WP0051
           MOVE P2J4NU TO WP0052
           MOVE P2J5NU TO WP0053
           MOVE P2NWVB TO WP0054
           MOVE P2NXVB TO WP0055
           MOVE P2NYVB TO WP0056
           MOVE P2NZVB TO WP0057
           MOVE P2N0VB TO WP0058
           MOVE P2N1VB TO WP0059
           MOVE P2N2VB TO WP0060
           MOVE P2N3VB TO WP0061
           MOVE P2N4VB TO WP0062
           MOVE P2FLNU TO WP0063
           MOVE P2FMNU TO WP0064
           MOVE P2NVVB TO WP0065
           MOVE P2N6VB TO WP0066
           MOVE P2N7VB TO WP0067
           MOVE P2N8VB TO WP0068
           MOVE P2N9VB TO WP0069
           MOVE P2OAVB TO WP0070
           MOVE P2OBVB TO WP0071
           MOVE P2OCVB TO WP0072
           MOVE P2ODVB TO WP0073
           MOVE P2ZKCF TO WP0074
           MOVE P2ZLCF TO WP0075
           MOVE P2ZMCF TO WP0076
           MOVE P2ZRCF TO WP0077
           MOVE P2ZNCF TO WP0078
           MOVE P2HSNU TO WP0079
           MOVE P2I0NU TO WP0080
      *==============================================================
           CONTINUE.
       ZZPEXT.
           EXIT.
      /EJECT
       ZZINIT SECTION.
      *==============================================================
      *    Initialisation
      *==============================================================
           IF (W0ICL = SPACES) THEN
      *        *Initial call
               MOVE 'Y' TO W0ICL
           ELSE
               MOVE 'N' TO W0ICL
           END-IF
           MOVE SPACES TO P0RTN
           MOVE SPACES TO W0RTN
           MOVE ZEROS  TO W0RTW
           MOVE SPACES TO W0RSF
           MOVE '400' TO W0ENV
           MOVE ALL B'0' TO INDICS
           MOVE SPACES TO ZZPGM OF JOB-CONTEXT
      *    Retrieve job attributes
           CALL 'Y2RTJCR' USING
             JOB-CONTEXT
           END-CALL
      *    Setup job date/time
           MOVE ZZSD7 OF JOB-CONTEXT TO ZZJDT
           ACCEPT ZZTIME FROM TIME
           MOVE ZZHNS TO ZZJTM OF JOB-CONTEXT
           MOVE 'SBA011010S' TO ZZPGM OF JOB-CONTEXT
      *    Open files
           OPEN INPUT SBBNSDA2L3
           ACCEPT SBBNSDA2L3-OPEN FROM OPEN-FEEDBACK-AREA FOR SBBNSDA2L3
      *    Move main file information to JOB context
           MOVE CORRESPONDING OPENFA OF SBBNSDA2L3-OPEN TO JOB-CONTEXT
           CALL 'Y2QLVNR' USING
             ZZFFL OF JOB-CONTEXT
             ZZFLB OF JOB-CONTEXT
             ZZFQL OF JOB-CONTEXT
           END-CALL
           MOVE 'Y' TO W0OPN
           MOVE 'N' TO W0PMT
      *    Define local work field PreQual Net Reg/Ord 1
           MOVE ZERO TO YN0001 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 2
           MOVE ZERO TO YN0002 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 3
           MOVE ZERO TO YN0003 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 4
           MOVE ZERO TO YN0004 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 5
           MOVE ZERO TO YN0005 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 6
           MOVE ZERO TO YN0006 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 7
           MOVE ZERO TO YN0007 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 8
           MOVE ZERO TO YN0008 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 9
           MOVE ZERO TO YN0009 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 10
           MOVE ZERO TO YN0010 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 11
           MOVE ZERO TO YN0011 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 12
           MOVE ZERO TO YN0012 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 13
           MOVE ZERO TO YN0013 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 14
           MOVE ZERO TO YN0014 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 15
           MOVE ZERO TO YN0015 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 16
           MOVE ZERO TO YN0016 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 17
           MOVE ZERO TO YN0017 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 18
           MOVE ZERO TO YN0018 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 19
           MOVE ZERO TO YN0019 OF WORK-CONTEXT
      *    Define local work field PreQual Net Reg/Ord 20
           MOVE ZERO TO YN0020 OF WORK-CONTEXT
      *    Define local work field Dealer total bonus amount
           MOVE ZERO TO YN0021 OF WORK-CONTEXT
      *==============================================================
           CONTINUE.
       ZZEXIT.
           EXIT.
